### ISSUE TITLE
Usage with the trial FortiVM

### ISSUE THREAD

**Issue by Kircheneer** [fortinetdev/terraform-provider-fortios#109]
Is it possible to use this provider with the trial FortiVM, that is with the following limitations:

- Only HTTP access?
- TLSv1.0?
- Behind a Reverse Proxy running TLSv1.2?

I didn't find any information on the two former and the latter fails with a HTTP 401 despite the URL parameter for the authentication being passed (as evident in a packet capture on the FortiGate). CLI debug output shows the following:

From the terraform host

`$ curl -kv https://$REVERSE_PROXY::8443/api/v2/cmdb/firewall/address?access_token=$CENSORED`

On the FortiGate (running v6.2.1)

```
FortiGate-VM64-KVM # diag debug enable

FortiGate-VM64-KVM # [httpsd 170 - 1603981649     info] ap_invoke_handler[569] -- new request (handler='api_cmdb_v2-handler', uri='/api/v2/cmdb/firewall/address', method='GET')
[httpsd 170 - 1603981649     info] ap_invoke_handler[573] -- User-Agent: curl/7.29.0
[httpsd 170 - 1603981649     info] ap_invoke_handler[576] -- Source: $REVERSE_PROXY:38638 Destination: $FORTIGATE:80
[httpsd 170 - 1603981649     info] api_cmdb_v2_handler[2132] -- received api_cmdb_v2_request from '$REVERSE_PROXY'
[httpsd 170 - 1603981649     info] api_access_check_for_api_key[910] -- Wrong login method.
[httpsd 170 - 1603981649  warning] _lock_out_check_and_lock_out[541] -- Failed api-key login attempt from $REVERSE_PROXY. (1/3 attempts within 240s).
[httpsd 170 - 1603981649     info] ap_invoke_handler[592] -- request completed (handler='api_cmdb_v2-handler' result==0)

```

**Comment by frankshen01** [comment]
Hi @Kircheneer, Thanks for raising this issue. The provider relies on the API service to interact with FortiOS, but in the trial version of FortiOS(including trial FortiVM), access to the API service through token is prohibited, therefore, for the trial version of FortiOS, the provider has no way to communicate with the API service to the support it. Thanks!

**Comment by Kircheneer** [comment]
Thanks for the heads-up!
