### ISSUE TITLE
Allow a blackhole or null interface so that blackhole routes don't want to re-add the interface on every apply

### ISSUE THREAD

**Issue by blkistsg** [fortinetdev/terraform-provider-fortios#111]
fortios_networking_route_static.blackhole_192 will be updated in-place  
~ resource "fortios_networking_route_static" "blackhole_192" {        
  blackhole = "enable"        
  comment   = "Blackhole Summary for Private IPs to prevent traffic from going out default route"      
+ device    = "wan1"        
  distance  = "10"        
  dst       = "192.168.0.0/16"        
  gateway   = "0.0.0.0"        
  id        = "1"        
  priority  = "0"        
  status    = "enable"        
  weight    = "0"    }

**Comment by frankshen01** [comment]
According to your configuration, you are using the old version: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_networking_route_static, we can see that there is a warning: The resource will be deprecated and replaced by fortios_router_static. Change your configuration to the new version: fortios_router_static https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_router_static, it will be ok. Let me know if you need any further information.
