### ISSUE TITLE
systemdhcp_server lease_time can not be 0

### ISSUE THREAD

**Issue by antonvdl** [fortinetdev/terraform-provider-fortios#112]
It should be possible to supply 0 for lease_time.
Documentation states: lease_time - Lease time in seconds, 0 means unlimited.

But when configuring 0 the following error is thrown:
Error: expected lease_time to be in the range (300 - 8640000), got 0

**Comment by frankshen01** [comment]
Hi @antonvdl, thanks for raising this issue, your suggestion is completely correct. The issue will be fixed and included in the next release (within a week). Thank you!

**Comment by frankshen01** [comment]
Supported and released, please see the latest version(v1.6.10): https://registry.terraform.io/providers/fortinetdev/fortios/latest and https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_systemdhcp_server for details.
