### ISSUE TITLE
255 character limit on autoscript

### ISSUE THREAD

**Issue by blkistsg** [fortinetdev/terraform-provider-fortios#114]
When using the "fortios_system_autoscript" resource, the configuration script is limited to 255 characters. Is there a workaround for this?

![image](https://user-images.githubusercontent.com/71094995/99722505-bec8ab00-2a7e-11eb-9454-62ddaafb496d.png)
![image](https://user-images.githubusercontent.com/71094995/99722533-c8521300-2a7e-11eb-82e6-4e8f59b2b449.png)

**Comment by frankshen01** [comment]
Hi @blkistsg, the 255 here is the limit specified by the FortiOS system. Your use-case can be achieved through the following three alternative methods:

**Option1:** When using fortios_system_autoscript, you can implement it in multiple stages. In the first stage, configure the necessary parameters. In subsequent stages, configure other optional parameters. Delete the spaces and tabs at the beginning of each line. The purpose of this is to try to meet the 255 limit. The dependencies between several stages need to be ensured. E.g:
```
resource "fortios_system_autoscript" "trname1" {
  interval    = 1
  name        = "1"
  output_size = 10
  repeat      = 1
  script      = <<EOF
config user saml
edit "sss"
set entity-id "https://1.1.1.1"
set single-sign-on-url "https://1.1.1.1/sign"
set idp-entity-id "https://1.1.1.1/acc"
set idp-single-sign-on-url "https://1.1.1.1/sou"
set idp-cert "11"
set user-name "ad111"
next
end
EOF
  start       = "auto"
}

resource "fortios_system_autoscript" "trname2" {
  interval    = 4
  name        = format("%s%s", fortios_system_autoscript.trname1.name, "extend")
  output_size = 10
  repeat      = 1
  script      = <<EOF
config user saml
edit "sss"
set cert "Fortinet_Factory"
set single-logout-url "https://1.1.1.1/logout"
set idp-single-logout-url "https://1.1.1.1/lo"
next
end
EOF
  start       = "auto"
}
```
**Option2:** Use fortios_json_generic_api
```
resource "fortios_json_generic_api" "genericapi" {
  path   = "/api/v2/cmdb/user/saml"
  method = "POST"
  json   = <<EOF
{
  "name": "testwebvpn",
  "cert": "Fortinet_Factory",
  "entity-id": "https://1.1.1.1",
  "single-sign-on-url": "https://1.1.1.1/sign",
  "single-logout-url": "https://1.1.1.1/logout",
  "idp-entity-id": "https://1.1.1.1/acc",
  "idp-single-sign-on-url": "https://1.1.1.1/sou",
  "idp-single-logout-url": "https://1.1.1.1/lo",
  "idp-cert": "11",
  "user-name": "ad111",
  "group-name": ""
}
EOF
}
```
**Option3:**  Use newly released resources: 
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_user_saml

**Comment by blkistsg** [comment]
Thank you so much for the solutions listed here! It helped me out a lot!
