### ISSUE TITLE
error when add user group to firewall policy

### ISSUE THREAD

**Issue by blkistsg** [fortinetdev/terraform-provider-fortios#115]
When I try to specify user groups with the "groups" argument under the "fortios_firewall_policy" resource, it gives me an error. Please advise. Thank you!
 
![image](https://user-images.githubusercontent.com/71094995/99863953-a5069100-2b6e-11eb-9131-72892ace8c6f.png)

![image](https://user-images.githubusercontent.com/71094995/99863916-77214c80-2b6e-11eb-917f-cce40e1d6c8b.png)

**Comment by frankshen01** [comment]
Hi @blkistsg , the groups argument is a terraform block which is a container for multiple group objects. It should be configured as a terraform block. E.g:

```
resource "fortios_firewall_policy" "trname1" {
  action             = "accept"
  logtraffic         = "utm"
  name               = "policys1"
  policyid           = 1
  schedule           = "always"
  wanopt             = "disable"
  wanopt_detection   = "active"
  wanopt_passive_opt = "default"
  wccp               = "disable"
  webcache           = "disable"
  webcache_https     = "disable"
  wsso               = "enable"
  session_ttl        = 333

  dstaddr {
    name = "all"
  }

  dstintf {
    name = "port4"
  }

  service {
    name = "HTTP"
  }

  srcaddr {
    name = "all"
  }

  srcintf {
    name = "port3"
  }

  groups {  # <======================================
    name = "SSO_Guest_Users"
  }

  groups {  # <======================================
    name = "Guest-group"
  }
}
```
You can find the description about the groups argument in： https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_policy :
```
The groups block supports:
name - Group name.
```
and https://docs.fortinet.com/document/fortigate/6.4.0/cli-reference/307620/firewall-policy, E.g:
```
config firewall policy
    edit 1
        set name "policys1"
        set uuid a6da8ae8-1bbc-51eb-4dc3-8631070fe5d2
        set srcintf "port3"
        set dstintf "port4"
        set srcaddr "all"
        set dstaddr "all"
        set action accept
        set schedule "always"
        set service "HTTP"
        set session-ttl 333
        set groups "SSO_Guest_Users" "Guest-group"     <========================
    next
end
```

The fortios_vpnssl_settings->groups in your error message also has the same configuration principle as fortios_firewall_policy->groups.

For more details about blocks of terraform, please see: Arguments and Blocks section in: https://www.terraform.io/docs/configuration/syntax.html



Thanks!

**Comment by blkistsg** [comment]
Oh yes, you are right. I must have been tired when I put in this issue. I
apologize for not taking a look at the syntax in the documentation more
closely. Thank you.

**Comment by frankshen01** [comment]
hi, no problem, I’m happy to help!

**Comment by blkistsg** [comment]
Hi, sorry I didn't catch this before you closed the issue, but I believe the documentation on this is wrong...
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_policy#ssh_filter_profile

The "groups" attribute is listed as an argument, not a block. I think that was my original logic when I opened the ticket.

**Comment by frankshen01** [comment]
See my reply at: https://github.com/fortinetdev/terraform-provider-fortios/issues/116#issuecomment-734383693
