### ISSUE TITLE
Hi, sorry I didn't catch this before you closed the issue, but I believe the documentation on this is wrong...

### ISSUE THREAD

**Issue by blkistsg** [fortinetdev/terraform-provider-fortios#116]
Hi, sorry I didn't catch this before you closed the issue, but I believe the documentation on this is wrong...
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_policy#ssh_filter_profile

The "groups" attribute is listed as an argument, not a block. I think that was my original logic when I opened the ticket.

_Originally posted by @blkistsg in https://github.com/fortinetdev/terraform-provider-fortios/issues/115#issuecomment-733188303_

**Comment by frankshen01** [comment]
Hi, in the terraform Provider documentation, the block is usually included in the description of Argument. Let us look at the usage habits of the two largest providers in Terraform: AWS provider and Azure provider:

https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cdn_endpoint
![11111](https://user-images.githubusercontent.com/49291382/100372567-64ae8380-3044-11eb-883a-176863d9f4bf.png)

https://registry.terraform.io/providers/hashicorp/aws/latest/docs/resources/spot_fleet_request
![222](https://user-images.githubusercontent.com/49291382/100372644-8445ac00-3044-11eb-8ff6-d59fcfb04e23.png)

We can see: First, the block identifier is briefly described, and then the members included in it are described later. This is done to be compatible with the old nesting structure of Terraform 0.11 and pre. FortiOS Provider also complies with this usage convention without exception. Thank you for your improvement suggestions. According to your suggestion, I have added block highlight description for all block identifiers, so as to improve the ease of use of the document.  See the new release: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_policy#groups

Does this make sense? Thanks!

**Comment by blkistsg** [comment]
Yes, this makes sense. Thank you!
