### ISSUE TITLE
Cannot set match_ip_address in fortios_router_routemap 

### ISSUE THREAD

**Issue by MilesTails** [fortinetdev/terraform-provider-fortios#121]
Cannot set match_ip_address in fortios_router_routemap 

To replicate run the following twice:

``` resource "fortios_router_routemap" "RM_LOOPBACK_UNDERLAY" {
  name = "RM_LOOPBACK_UNDERLAY"
  rule {
    id = 1
    action = "permit"
    match_ip_address = fortios_router_prefixlist.PL_LOOPBACK_UNDERLAY.name
  }
  rule{
      id = 2
      action = "deny"
  }
}
resource "fortios_router_prefixlist" "PL_LOOPBACK_UNDERLAY" {
  name = "PL_LOOPBACK_UNDERLAY"
  rule{
      id = 1
      action = "permit"
      prefix = "172.16.234.0 255.255.255.0"
      le = "32"
  }
}
```

Result on second run:
```
 ~ resource "fortios_router_routemap" "RM_LOOPBACK_UNDERLAY" {
        id   = "RM_LOOPBACK_UNDERLAY"
        name = "RM_LOOPBACK_UNDERLAY"

      ~ rule {
            action                                 = "permit"
            id                                     = 1
            match_community_exact                  = "disable"
            match_flags                            = 0
          + match_ip_address                       = "PL_LOOPBACK_UNDERLAY"
            match_metric                           = 0
```

**Comment by MilesTails** [comment]
Wow amazing thank you. Does the provider fully support 6.4?

I think we will be on 6.2 for quite some time.

**Comment by frankshen01** [comment]
Hi @MilesTails, the current version of the provider contains most of the parameters of 6.4. The Beta of the provider that fully supports 6.0, 6.2, 6.4 and 6.6 has been completed(https://github.com/frankshen-beta/terraform-provider-fortios-beta). It will be merged into the current provider after it has been continuously evaluated for a period of time. Thank you!

**Comment by latam-cse-dev** [comment]
@frankshen01 I'm testing the beta version but I don't see the datasource fortios_json_generic_api.

Would be possible to add it to the beta repo?

**Comment by mbdraks** [comment]
Hi @frankshen01 

I'm testing the beta but I don't see the datasource fortios_json_generic_api there.

Would be possible to include it on the beta repo?

**Comment by frankshen01** [comment]
@mbdraks , Thank you for raising this, the beta version will be merged into the current repo and released (1.9.0) within 1-2 weeks. Do I still need to add fortios_json_generic_api  to the beta repo? If you need this feature urgently, I will add this to the beta version this week. Thank you!

**Comment by mbdraks** [comment]
I can wait, no problem!

**Comment by frankshen01** [comment]
Status Update ~ support FortiOS 6.0 6.2 6.4 6.6:  https://registry.terraform.io/providers/fortinetdev/fortios/latest (v1.10.0)

**Comment by poroping** [comment]
@frankshen01 I'm running 6.2.6 and hitting this bug when trying to set LE and GE in prefix lists. Do you know the bugid so I can get my SE to check if an interim build is available that resolves this. 6.4.x is not available for our setup unfortunately.

**Comment by fgtdev-hblu** [comment]
Hi @poroping, thanks for raising the question. We are contacting the responsible team. We will get back to you as soon as we receive feedback from them. Thanks!

**Comment by frankshen01** [comment]
> @frankshen01 I'm running 6.2.6 and hitting this bug when trying to set LE and GE in prefix lists. Do you know the bugid so I can get my SE to check if an interim build is available that resolves this. 6.4.x is not available for our setup unfortunately.

Thanks for checking this @poroping , and sorry it still has not been fixed by the API team. I haven't their internal BUG ID for the problem. But we have reported the bug to the API team with BUG ID: 0713815. Thank you!
