### ISSUE TITLE
Firewall policyID value auto assign

### ISSUE THREAD

**Issue by murakest** [fortinetdev/terraform-provider-fortios#122]
Hello,
previous provider version 1.6.3 allowed to create resource "fortios_firewall_policy" without specifying policyid.

FortiOS version: v6.4.2 build1723 (GA)
Terraform version: 0.14.2
Fortios provider version: 1.6.16

After upgrade to 1.6.16 provider version now resource "fortios_firewall_policy" requires to specify policyid.
We do not sort the automation created rules, so policyid for us is not mandatory field.

Our infrastructure built is quite dynamic and we need to be able to specify firewall policyid by auto increasing as with previous provider 1.6.3. How can this be achieved with current provider 1.6.16?

**Comment by frankshen01** [comment]
@murakest , Thanks for raising this issue!  The issue has been fixed and will be included in the next release (this week). Thank you!

**Comment by frankshen01** [comment]
Fixed and released, please see the latest version(v1.6.17): https://registry.terraform.io/providers/fortinetdev/fortios/latest for details. Thanks!

**Comment by murakest** [comment]
Thank you, works fine now.
