### ISSUE TITLE
How to use FortiOS resources over Fortimanager

### ISSUE THREAD

**Issue by patrickpreuss** [fortinetdev/terraform-provider-fortios#124]
Hi There,
i have a few questions.  

- How to use FortiOS Resources over Fortimanger?

> Would the Solution?
provider "fortios" { 
           fmg_* = "EXAMPLE-MANAGER-SETTINGS"
           device_name = "myfirewall"
} 
resource "fortios_router_authpath" "trname" {
   - New Route values
}

How to assign a VDOM to an ADOM? 
  - With and without ADOM Locks

How to import a existing Policy from a device?

**Comment by frankshen01** [comment]
Hi, @patrickpreuss , Thanks for submitting this.  Regarding the questions you mentioned:

**_1 Patrickpreuss: How to use FortiOS Resources over Fortimanger?_**
A: They operate independently, and there is no "over" relationship between them.

**_2 Patrickpreuss: How to assign a VDOM to an ADOM? With and without ADOM Locks_**
These features are being developed and they will be included in the next FMG release. They are not supported in the current version. And as an alternative, we can also use fortios_fmg_jsonrpc_request to complete this task now:

2.1 Example without ADOM lock, as described in #74
> 
> **A. Enable fortigate vdom mode**
> ```
> provider "fortios" {
>   hostname = "192.168.52.177"
>   token    = "krs096zp3zhcqG8x6scxG1j3tHgnrg" # 6.2.0
>   insecure = "true"
> 
>   fmg_hostname = "192.168.52.178"
>   fmg_username = "admin"
>   fmg_passwd   = "admin"
>   fmg_insecure = true
> }
> 
> # enable vdom mode
> resource "fortios_system_global" "trname" {
>   admin_sport = 443
>   alias       = "FGVM02TM20003062"
>   hostname    = "myfirewall"
>   timezone    = "04"
>   vdom_admin  = "enable"
> }
> ```
> **B. Create new vdom**
> ```
> resource "fortios_system_vdom_setting" "test2" {
>   name       = "newvdom"
>   short_name = "newvdom"
>   temporary  = 0
> }
> 
> ```
> 
> **C. Create new FGT device and install**
> ```
> # create new device on root ADOM
> resource "fortios_fmg_devicemanager_device" "test1" {
>   userid      = "admin"
>   password    = "xxxxxxx"
>   ipaddr      = "192.168.52.177"
>   device_name = "myfirewall"
> }
> 
> # instal device
> resource "fortios_fmg_devicemanager_install_device" "test1" {
>   target_devname = fortios_fmg_devicemanager_device.test1.device_name
>   timeout        = 5
> }
> ```
> 
> **D. Remove newvdom vdom from the device of the root ADOM**
> ```
> resource "fortios_fmg_jsonrpc_request" "test3" {
>   json_content = <<JSON
> {
>   "method": "delete",
>   "params": [
>     {
>       "url": "/dvmdb/adom/root/device/myfirewall/vdom/newvdom"
>     }
>   ]
> }
> JSON
> }
> ```
> 
> **E. create new ADOM**
> ```
> resource "fortios_fmg_system_adom" "test1" {
>   name                                              = "adom02"
>   type                                              = "FortiGate"
>   central_management_vpn                            = false
>   central_management_fortiap                        = true
>   central_management_sdwan                          = false
>   mode                                              = "Normal"
>   perform_policy_check_before_every_install         = true
>   action_when_conflicts_occur_during_policy_check   = "Continue"
>   auto_push_policy_packages_when_device_back_online = "Enable"
>   status                                            = 1
> }
> ```
> 
> **F. Add newvdom vdom to ADOM adom02**
> ```
> resource "fortios_fmg_jsonrpc_request" "test6" {
>   json_content = <<JSON
> {
>   "method": "add",
>   "params": [
>     {
>       "data": [
>         {
>           "name": "newvdom"
>         }
>       ],
>       "url": "/dvmdb/adom/adom02/device/myfirewall/vdom"
>     }
>   ]
> }
> JSON
> }
> 
> ```
>


2.2 Example with ADOM lock(workspace-mode=normal)
>
> ```
> 
> provider "fortios" {
>   hostname = "192.168.52.177"
>   token    = "krs096zp3zhcqG8x6scxG1j3tHgnrg"
>   insecure = "true"
> 
>   fmg_hostname = "192.168.52.178"
>   fmg_username = "admin"
>   fmg_passwd   = "admin"
>   fmg_insecure = true
> }
> 
> resource "fortios_system_global" "res" {
>   admin_sport = 443
>   alias       = "FGVM02TM20003062"
>   hostname    = "myfirewall"
>   timezone    = "04"
>   vdom_admin  = "enable"
> }
> 
> resource "fortios_system_vdom_setting" "res" {
>   name       = "newvdom"
>   short_name = "newvdom"
>   temporary  = 0
> 
>   depends_on = [
>     fortios_system_global.res,
>   ]
> }
> 
> resource "fortios_fmg_jsonrpc_request" "lk1" {
>   json_content = <<JSON
> {
>   "method": "set",
>   "params": [
>     {
>       "data": {
>         "workspace-mode": "normal"
>       },
>       "url": "/cli/global/system/global"
>     }
>   ]
> }
> JSON
>   depends_on = [
>     fortios_system_vdom_setting.res,
>   ]
> }
> ```
>
> **Lock root ADOM**
>
> ```
> resource "fortios_fmg_jsonrpc_request" "lk2" {
>   comment      = "1"
>   json_content = <<JSON
> {
>   "method": "exec",
>   "params": [
>     {
>       "url": "/dvmdb/adom/root/workspace/lock"
>     }
>   ]
> }
> JSON
>   depends_on = [
>     fortios_fmg_jsonrpc_request.lk1,
>   ]
> }
> 
> 
> resource "fortios_fmg_devicemanager_device" "res" {
>   userid      = "admin"
>   password    = "admin"
>   ipaddr      = "192.168.52.177"
>   device_name = "myfirewall"
>   depends_on = [
>     fortios_fmg_jsonrpc_request.lk2,
>   ]
> }
> 
> resource "fortios_fmg_devicemanager_install_device" "res" {
>   target_devname = fortios_fmg_devicemanager_device.res.device_name
>   timeout        = 5
> }
> 
> 
> resource "fortios_fmg_jsonrpc_request" "res1" {
>   json_content = <<JSON
> {
>   "method": "delete",
>   "params": [
>     {
>       "url": "/dvmdb/adom/root/device/myfirewall/vdom/newvdom"
>     }
>   ]
> }
> JSON
>   depends_on = [
>     fortios_fmg_devicemanager_install_device.res,
>   ]
> }
> 
> resource "fortios_fmg_system_adom" "res" {
>   name                                              = "adom02"
>   type                                              = "FortiGate"
>   central_management_vpn                            = false
>   central_management_fortiap                        = true
>   central_management_sdwan                          = false
>   mode                                              = "Normal"
>   perform_policy_check_before_every_install         = true
>   action_when_conflicts_occur_during_policy_check   = "Continue"
>   auto_push_policy_packages_when_device_back_online = "Enable"
>   status                                            = 1
> 
>   depends_on = [
>     fortios_fmg_jsonrpc_request.res1,
>   ]
> }
> 
> ```
>
> **Unlock root ADOM**
> ```
> resource "fortios_fmg_jsonrpc_request" "lk3" {
>   comment      = "1"
>   json_content = <<JSON
> {
>   "method": "exec",
>   "params": [
>     {
>       "url": "/dvmdb/adom/root/workspace/unlock"
>     }
>   ]
> }
> JSON
>   depends_on = [
>     fortios_fmg_system_adom.res,
>   ]
> }
> ```
>
> **Lock adom02 ADOM**
> ```
> resource "fortios_fmg_jsonrpc_request" "lk4" {
>   comment      = "1"
>   json_content = <<JSON
> {
>   "method": "exec",
>   "params": [
>     {
>       "url": "/dvmdb/adom/adom02/workspace/lock"
>     }
>   ]
> }
> JSON
>   depends_on = [
>     fortios_fmg_jsonrpc_request.lk1,
>   ]
> }
> 
> 
> resource "fortios_fmg_jsonrpc_request" "lk5" {
>   json_content = <<JSON
> {
>   "method": "add",
>   "params": [
>     {
>       "data": [
>         {
>           "name": "newvdom"
>         }
>       ],
>       "url": "/dvmdb/adom/adom02/device/myfirewall/vdom"
>     }
>   ]
> }
> JSON
> 
>   depends_on = [
>     fortios_fmg_jsonrpc_request.lk4,
>   ]
> }
> 
> ```
> **Unlock adom02 ADOM**
> ```
>
> resource "fortios_fmg_jsonrpc_request" "lk6" {
>   comment      = "1"
>   json_content = <<JSON
> {
>   "method": "exec",
>   "params": [
>     {
>       "url": "/dvmdb/adom/adom02/workspace/unlock"
>     }
>   ]
> }
> JSON
>   depends_on = [
>     fortios_fmg_jsonrpc_request.lk5,
>   ]
> }
> 
> ```
> 

**_3 Patrickpreuss: How to import a existing Policy from a device?_**
A:  As far as I know, FortiManager currently does not provide an API that can run this function correctly, so terraform will not implement the feature until the API is provided correctly. Thank you!

**Comment by patrickpreuss** [comment]
Hi @frankshen01 
many thanks for the answers. 
For the adom part i will test this, many thanks. 

For Question1) just to be clear at this point. For me i looks like the the FortiOS resources needs to run on the Gateway directly? 
If this correct this would mean there is the need to create an api on every gateway. 

I want to avoid creating the API Keys on the gateways at all and use the  FortiManager connection to the gateway. 

One reason for this is that you might have access to the Manager but not the gateway from the system running terraform.

**Comment by frankshen01** [comment]
Hi @patrickpreuss, no problem. 

I can understand your concern and decision. Yes, you are right, the resources of the FortiOS part will directly control FortiGate. BTW: One thing to remind is that the full FortiManager terraform version will be launched in the next phase. At present, the functions of the FortiOS part of the Provider are much richer than the FortiManager part.
