### ISSUE TITLE
Creating an user with radius authentication is not possible, due to missing radius server assignment.

### ISSUE THREAD

**Issue by patrickpreuss** [fortinetdev/terraform-provider-fortios#125]
Hi, 

Creating an user with radius authentication is not possible, due to missing radius server assignment. 
Where as changing an existing user with radius server assigned is possible.

Error: Error creating System Admin User: CreateUpdateSystemAdminUser failed: status not right: code is 18446744073709490965, message is invalid value

 + resource "fortios_fmg_system_admin_user" "example" {
      + description = "Example User"
      + id          = (known after apply)
      + profileid   = "Example"
      + rpc_permit  = "read-write"
      + trusthost1  = "0.0.0.0 0.0.0.0"
      + trusthost2  = "255.255.255.255 255.255.255.255"
      + trusthost3  = "255.255.255.255 255.255.255.255"
      + user_type   = "radius"
      + userid      = "example"
    }

**Comment by frankshen01** [comment]
@patrickpreuss  thank you for creating this issue about FortiManager. The feature has been supported and the improvement will take effect in the next release(next week).

**Comment by frankshen01** [comment]
Feature supported and released, please see the latest version(v1.6.18): https://registry.terraform.io/providers/fortinetdev/fortios/latest and https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fmg_system_admin_user for details, Thanks!
