### ISSUE TITLE
Feature request: Fortigate as data source

### ISSUE THREAD

**Issue by poroping** [fortinetdev/terraform-provider-fortios#126]
Are there any plans to implement data sources with this provider?

**Comment by frankshen01** [comment]
Hi @poroping, Thanks for submitting this, your suggestion is valuable, I agree with you! Since we are developing FMG full resources support now, we currently have no plans to develop large-scale support for FOS data sources. If you have urgent needs for some data sources, please don't hesitate to let me know, I will give priority to doing my best to implement part of them. Thank you!

**Comment by poroping** [comment]
> Hi @poroping, Thanks for submitting this, your suggestion is valuable, I agree with you! Since we are developing FMG full resources support now, we currently have no plans to develop large-scale support for FOS data sources. If you have urgent needs for some data sources, please don't hesitate to let me know, I will give priority to doing my best to implement part of them. Thank you!

#127 would be preferable. Off the top of my head though data sources for the 'big ones' would be:
fortios_system_interface
fortios_firewall_address
fortios_firewall_addrgrp
fortios_firewall_policy
and the routing resources, bgp/ospf/static/rip

I assume this would be something you could generate programmatically for the majority of the resources (when you have time).

Is there a beta for these FMG resources? I'd be interested in checking that out. I have a whole bunch of Ansible plays but it became very tedious doing the dependencies manually.

**Comment by frankshen01** [comment]
_@poroping: Off the top of my head though data sources for the 'big ones' would be:fortios_system_interface
fortios_firewall_address
fortios_firewall_addrgrp
fortios_firewall_policy
and the routing resources, bgp/ospf/static/rip_
A: The above datasources will be gradually implemented, and the progress status will be updated here. BTW: Due to parallel tasks, the release may not be timely.

_@poroping: Is there a beta for these FMG resources?_
A:  Apologize there is no public beta yet. The beta version is expected to be available/public at the end of the first quarter/early second quarter of 2021. 

Thank you!

**Comment by poroping** [comment]
A data source for the generic json call that just returned the results as attributes would be a great interim solution if possible.

**Comment by frankshen01** [comment]
Hey, this is a pretty good idea. yes, it is a great interim solution. I will study it first after solving the previous issues.

**Comment by frankshen01** [comment]
Status Update:

Data source fortios_json_generic_api has been supported and released, please see the latest version(v1.7.0): https://registry.terraform.io/providers/fortinetdev/fortios/latest and https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/data-sources/fortios_json_generic_api

**Validation:**
```
# cat main.tf
provider "fortios" {
  hostname = "192.168.52.177"
  insecure = "true"
  token = "GNH7r40H65GNb46kd4rG8rtrmn0fr1"
}

data "fortios_json_generic_api" "example_1" {
  path = "/api/v2/cmdb/firewall/policy"
}

output "res_get_all_policy" {
  value = jsondecode(data.fortios_json_generic_api.example_1.response).results
}

data "fortios_json_generic_api" "example_2" {
  path          = "/api/v2/cmdb/firewall/policy"
  specialparams = "filter=policyid>=1"
}

output "res_get_specific_policy_name" {
  value = length(jsondecode(data.fortios_json_generic_api.example_2.response).results) >= 1 ? jsondecode(data.fortios_json_generic_api.example_2.response).results[0].name : "none"
}

data "fortios_json_generic_api" "example_3" {
  path = "/api/v2/cmdb/router/bgp"
}

output "res_get_bgp_redistribute" {
  value = jsondecode(data.fortios_json_generic_api.example_3.response).results.redistribute
}

# terraform apply

....................................

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

res_get_all_policy = [
  {
    "action" = "accept"
    "anti-replay" = "enable"
    "application-list" = ""
    "auth-cert" = ""
    "auth-path" = "disable"
    "auth-redirect-addr" = ""
    "auto-asic-offload" = "enable"
    "av-profile" = ""
    "block-notification" = "disable"
    "captive-portal-exempt" = "disable"
    "capture-packet" = "disable"
    "cifs-profile" = ""
    "comments" = "Teamcity-managed rule"
    "custom-log-fields" = []
    "decrypted-traffic-mirror" = ""
    "delay-tcp-npu-session" = "disable"
    "diffserv-forward" = "disable"
    "diffserv-reverse" = "disable"
    "diffservcode-forward" = "000000"
    "diffservcode-rev" = "000000"
    "disclaimer" = "disable"
    "dlp-sensor" = ""
    "dnsfilter-profile" = ""
    "dsri" = "disable"
    "dstaddr" = []
    "dstaddr-negate" = "disable"
    "dstaddr6" = []
    "dstintf" = [
      {
        "name" = "port1"
        "q_origin_key" = "port1"
      },
    ]
    "email-collect" = "disable"
    "emailfilter-profile" = ""
    "file-filter-profile" = ""
    "firewall-session-dirty" = "check-all"
    "fixedport" = "disable"
    "fsso-agent-for-ntlm" = ""
    "fsso-groups" = []
    "geoip-anycast" = "disable"
    "geoip-match" = "physical-location"
    "global-label" = ""
    "groups" = []
    "http-policy-redirect" = "disable"
    "icap-profile" = ""
    "identity-based-route" = ""
    "inbound" = "disable"
    "inspection-mode" = "flow"
    "internet-service" = "enable"
    "internet-service-custom" = []
    "internet-service-custom-group" = []
    "internet-service-group" = []
    "internet-service-name" = [
      {
        "name" = "Amazon-AWS"
        "q_origin_key" = "Amazon-AWS"
      },
      {
        "name" = "GitHub-GitHub"
        "q_origin_key" = "GitHub-GitHub"
      },
    ]
    "internet-service-negate" = "disable"
    "internet-service-src" = "disable"
    "internet-service-src-custom" = []
    "internet-service-src-custom-group" = []
    "internet-service-src-group" = []
    "internet-service-src-name" = []
    "internet-service-src-negate" = "disable"
    "ippool" = "disable"
    "ips-sensor" = ""
    "label" = ""
    "logtraffic" = "utm"
    "logtraffic-start" = "disable"
    "match-vip" = "disable"
    "match-vip-only" = "disable"
    "name" = "my-rule1"
    "nat" = "disable"
    "natinbound" = "disable"
    "natip" = "0.0.0.0 0.0.0.0"
    "natoutbound" = "disable"
    "ntlm" = "disable"
    "ntlm-enabled-browsers" = []
    "ntlm-guest" = "disable"
    "outbound" = "enable"
    "per-ip-shaper" = ""
    "permit-any-host" = "disable"
    "permit-stun-host" = "disable"
    "policyid" = 1
    "poolname" = []
    "poolname6" = []
    "profile-group" = ""
    "profile-protocol-options" = "default"
    "profile-type" = "single"
    "q_origin_key" = 1
    "radius-mac-auth-bypass" = "disable"
    "redirect-url" = ""
    "replacemsg-override-group" = ""
    "reputation-direction" = "destination"
    "reputation-minimum" = 0
    "rtp-addr" = []
    "rtp-nat" = "disable"
    "schedule" = "always"
    "schedule-timeout" = "disable"
    "send-deny-packet" = "disable"
    "service" = []
    "service-negate" = "disable"
    "session-ttl" = "0"
    "src-vendor-mac" = []
    "srcaddr" = [
      {
        "name" = "FABRIC_DEVICE"
        "q_origin_key" = "FABRIC_DEVICE"
      },
    ]
    "srcaddr-negate" = "disable"
    "srcaddr6" = []
    "srcintf" = [
      {
        "name" = "port2"
        "q_origin_key" = "port2"
      },
    ]
    "ssh-filter-profile" = ""
    "ssh-policy-redirect" = "disable"
    "ssl-ssh-profile" = "no-inspection"
    "status" = "enable"
    "tcp-mss-receiver" = 0
    "tcp-mss-sender" = 0
    "tcp-session-without-syn" = "disable"
    "timeout-send-rst" = "disable"
    "tos" = "0x00"
    "tos-mask" = "0x00"
    "tos-negate" = "disable"
    "traffic-shaper" = ""
    "traffic-shaper-reverse" = ""
    "users" = []
    "utm-status" = "disable"
    "uuid" = "dd2398e6-510a-51eb-a2d5-6ba7bb4d3e83"
    "vlan-cos-fwd" = 255
    "vlan-cos-rev" = 255
    "vlan-filter" = ""
    "voip-profile" = ""
    "vpntunnel" = ""
    "waf-profile" = ""
    "wanopt" = "disable"
    "wanopt-detection" = "active"
    "wanopt-passive-opt" = "default"
    "wanopt-peer" = ""
    "wanopt-profile" = ""
    "wccp" = "disable"
    "webcache" = "disable"
    "webcache-https" = "disable"
    "webfilter-profile" = ""
    "webproxy-forward-server" = ""
    "webproxy-profile" = ""
  },
]

res_get_bgp_redistribute = [
  {
    "name" = "connected"
    "q_origin_key" = "connected"
    "route-map" = ""
    "status" = "disable"
  },
  {
    "name" = "rip"
    "q_origin_key" = "rip"
    "route-map" = ""
    "status" = "disable"
  },
  {
    "name" = "ospf"
    "q_origin_key" = "ospf"
    "route-map" = ""
    "status" = "disable"
  },
  {
    "name" = "static"
    "q_origin_key" = "static"
    "route-map" = ""
    "status" = "disable"
  },
  {
    "name" = "isis"
    "q_origin_key" = "isis"
    "route-map" = ""
    "status" = "disable"
  },
]

res_get_specific_policy_name = "my-rule1"

```

Thanks!

**Comment by poroping** [comment]
Awesome, works great, thanks.

**Comment by frankshen01** [comment]
Status Update:

58 new datasources are supported, please see the latest version(v1.8.0): https://registry.terraform.io/providers/fortinetdev/fortios/latest 

* **New Data Source:** `fortios_system_interfacelist`
* **New Data Source:** `fortios_system_interface`
* **New Data Source:** `fortios_system_global`
* **New Data Source:** `fortios_routerbgp_neighborlist`
* **New Data Source:** `fortios_routerbgp_neighbor`
* **New Data Source:** `fortios_router_staticlist`
* **New Data Source:** `fortios_router_static6list`
* **New Data Source:** `fortios_router_static6`
* **New Data Source:** `fortios_router_static`
* **New Data Source:** `fortios_router_setting`
* **New Data Source:** `fortios_router_routemaplist`
* **New Data Source:** `fortios_router_routemap`
* **New Data Source:** `fortios_router_ripng`
* **New Data Source:** `fortios_router_rip`
* **New Data Source:** `fortios_router_prefixlistlist`
* **New Data Source:** `fortios_router_prefixlist6list`
* **New Data Source:** `fortios_router_prefixlist6`
* **New Data Source:** `fortios_router_prefixlist`
* **New Data Source:** `fortios_router_policylist`
* **New Data Source:** `fortios_router_policy6list`
* **New Data Source:** `fortios_router_policy6`
* **New Data Source:** `fortios_router_policy`
* **New Data Source:** `fortios_router_ospf6`
* **New Data Source:** `fortios_router_ospf`
* **New Data Source:** `fortios_router_multicastflowlist`
* **New Data Source:** `fortios_router_multicastflow`
* **New Data Source:** `fortios_router_multicast6`
* **New Data Source:** `fortios_router_multicast`
* **New Data Source:** `fortios_router_keychainlist`
* **New Data Source:** `fortios_router_keychain`
* **New Data Source:** `fortios_router_isis`
* **New Data Source:** `fortios_router_communitylistlist`
* **New Data Source:** `fortios_router_communitylist`
* **New Data Source:** `fortios_router_bgp`
* **New Data Source:** `fortios_router_bfd6`
* **New Data Source:** `fortios_router_bfd`
* **New Data Source:** `fortios_router_authpathlist`
* **New Data Source:** `fortios_router_authpath`
* **New Data Source:** `fortios_router_aspathlistlist`
* **New Data Source:** `fortios_router_aspathlist`
* **New Data Source:** `fortios_router_accesslistlist`
* **New Data Source:** `fortios_router_accesslist6list`
* **New Data Source:** `fortios_router_accesslist6`
* **New Data Source:** `fortios_router_accesslist`
* **New Data Source:** `fortios_firewall_policylist`
* **New Data Source:** `fortios_firewall_policy6list`
* **New Data Source:** `fortios_firewall_policy64list`
* **New Data Source:** `fortios_firewall_policy64`
* **New Data Source:** `fortios_firewall_policy6`
* **New Data Source:** `fortios_firewall_policy`
* **New Data Source:** `fortios_firewall_addrgrplist`
* **New Data Source:** `fortios_firewall_addrgrp6list`
* **New Data Source:** `fortios_firewall_addrgrp6`
* **New Data Source:** `fortios_firewall_addrgrp`
* **New Data Source:** `fortios_firewall_addresslist`
* **New Data Source:** `fortios_firewall_address6list`
* **New Data Source:** `fortios_firewall_address6`
* **New Data Source:** `fortios_firewall_address`
