### ISSUE TITLE
fortios_firewall_policy schedule required

### ISSUE THREAD

**Issue by so-jelly** [fortinetdev/terraform-provider-fortios#140]
Update docs or default schedule to "always" ?

**Comment by frankshen01** [comment]
Hi @so-jelly , thanks for the issue! All the designs of this Provider are based on FortiAPI, I have checked the version documents of FortiAPI 6.0, 6.2, 6.4, 6.6, none of them set the field to `required`, so I am not sure whether setting this field to `required` will cause other problem. Required and Optional have caused repeated contradictions in the issues list, but this is indeed beyond the scope of the Provider. We can only set the fields that should not be Required to Optional as much as possible, but setting Optional to Required may cause trouble for other existing users, at this time, the provider will have to follow FortiAPI's regulations. Thanks!

**Comment by so-jelly** [comment]
I would just default it to "always" in this provider and document it as such.

**Comment by so-jelly** [comment]
I haven't fully tested this, but I believe it is not required in 6.2.3 and is in 6.4.3 and 6.4.4.

**Comment by frankshen01** [comment]
> I would just default it to "always" in this provider and document it as such.

Agree with you! It will be added in the next release, thanks for the improvement!

**Comment by frankshen01** [comment]
@so-jelly Thanks for your suggestion, this has been released in version 1.10.3 of the Terraform FortiOS provider. Please see: https://registry.terraform.io/providers/fortinetdev/fortios/latest and https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_policy for details. Thanks!
