### ISSUE TITLE
fortios_router_static needs dst

### ISSUE THREAD

**Issue by so-jelly** [fortinetdev/terraform-provider-fortios#141]
when making a route with a dstaddress a dst is required.  I end up setting `dst = "0.0.0.0 0.0.0.0"` when not needed.

**Comment by frankshen01** [comment]
Hi @so-jelly , thanks for the issue, thank you for your very careful checking! Again, all the designs of this Provider are based on FortiAPI, as we described in https://github.com/fortinetdev/terraform-provider-fortios/issues/140#issuecomment-778799748 . I have checked the version documents of FortiAPI 6.0, 6.2, 6.4, 6.6, all of them mark the field as `required`. This is indeed a very frustrating thing. I apologize for this. I will set this field as optional in the next release. Setting it as optional will not affect any existing users. Thank you!

**Comment by so-jelly** [comment]
The api ultimately just passes CLI commands if I understand it correctly.   This is indeed odd as it is not required when using the CLI.  Perhaps the issue is with the API.

**Comment by frankshen01** [comment]
@so-jelly  Thanks for your suggestion, this has been released in version 1.10.3 of the Terraform FortiOS provider. Please see: https://registry.terraform.io/providers/fortinetdev/fortios/latest and https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_router_static for details. Thanks!
