### ISSUE TITLE
fortios_fmg_firewall_security_policy sorting support

### ISSUE THREAD

**Issue by fatesnz** [fortinetdev/terraform-provider-fortios#143]
When using the fortios_fmg_firewall_security_policy resource to create security policies in the fortimanager, is there any support for ordering the policies? I've used **count** and **for_each** in the resource to create the policies, but it seems the policies are added based on what terraform finish creating first.

I know the fortigate resources have support for re-ordering policies using **depends_on** and a resource for sorting. Is there an equivalent for the fortimanager?

**Comment by frankshen01** [comment]
Hi @fatesnz , Thanks for raising this issue. If depends_on is not used,  terraform's concurrency always causes disorder problems. Currently there is no equivalent in FortiManager, we will be looking into adding that feature in the future. The following is a workaround for adjusting the order of security policies in FortiManager:

```hcl
# create policies with count / for_each

# 1 list policies (adom=root, package=mysho)
resource "fortios_fmg_jsonrpc_request" "test1" {
  json_content = <<JSON
{
  "method": "get",
  "params": [
    {
      "fields": [
        "policyid",
        "action",
        "name"
      ],
      "url": "/pm/config/adom/root/pkg/mysho/firewall/policy/"
    }
  ]
}
JSON
}

output test1 {
  value = fortios_fmg_jsonrpc_request.test1.response
}

# 2 move policy with policyid=2 to after 3
resource "fortios_fmg_jsonrpc_request" "test2" {
  json_content = <<JSON
{
  "method": "move",
  "params": [
    {
      "option": "after",
      "target": "3",
      "url": "/pm/config/adom/root/pkg/mysho/firewall/policy/2"
    }
  ]
}
JSON

  depends_on = [fortios_fmg_jsonrpc_request.test1]
}

# ....

# n list policies agian for verification
resource "fortios_fmg_jsonrpc_request" "test3" {
  json_content = <<JSON
{
  "method": "get",
  "params": [
    {
      "fields": [
        "policyid",
        "action",
        "name"
      ],
      "url": "/pm/config/adom/root/pkg/mysho/firewall/policy/"
    }
  ]
}
JSON

  depends_on = [fortios_fmg_jsonrpc_request.test2]
}

output test3 {
  value = fortios_fmg_jsonrpc_request.test3.response
}
```
Thanks!

**Comment by fatesnz** [comment]
Thanks @frankshen01 !
