### ISSUE TITLE
fortios_systemdhcp_server dns_service does not unset dns-service if changed to null

### ISSUE THREAD

**Issue by jonwilliams84** [fortinetdev/terraform-provider-fortios#145]
When creating a dhcp server with `dns_service = local` or `dns_service = default` if you later change this to `dns_service = null` and set dns_server[1-4] to an IP, e.g. `dns_server1 = 192.168.1.53' then the setting is not applied until you manually unset the dns-service via fortigate cli and re-apply the terraform.

**Comment by jonwilliams84** [comment]
So...I am not sure this is a bug but if you set dns_service = "specify" then it will unset the dns-server and the value from dns_server[1-4] will be populated. 

In a creation scenario as opposed to updating a resource then just setting `dns_server1` to an IP will default 'dns_service` to "specify"

**Comment by frankshen01** [comment]
Hi @jonwilliams84 Thanks for raising this issue.  I spent several hours trying my best to understand your issue and verify it, but I am not sure whether I understood it correctly, and if there is a mistake in my understanding, please correct me.  Currently, the API interface does not support unset dns_service by setting dns_service to null.   _' jonwilliams84: but if you set dns_service = "specify" then it will unset the dns-server and the value from dns_server[1-4] will be populated.'_   I failed to reproduce the problem, can you please provide your FortiOS version number?  From my understanding, according to the application scenario you described, the solution below seems to work well:

**1 dhcp server: default mode**

```
# cat main.tf
provider "fortios" {
  hostname = "192.168.52.177"
  insecure = "true"
  token    = "GNH7r40H65GNb46kd4rG8rtrmn0fr1"
}

resource "fortios_systemdhcp_server" "trname" {
  fosid           = 1
  dns_service     = "local"
  default_gateway = "192.168.1.12"
  netmask         = "255.255.255.0"
  interface       = "port2"
  timezone_option = "default"
  ip_range {
    id       = 1
    start_ip = "192.168.1.1"
    end_ip   = "192.168.1.2"
  }
}

# terraform apply
.....

# show result on firewall
labfirewall (server) # show
path=system.dhcp, objname=server, tablename=(null), size=688
config system dhcp server
    edit 1
        set dns-service local
        set default-gateway 192.168.1.12
        set netmask 255.255.255.0
        set interface "port2"
        config ip-range
            edit 1
                set start-ip 192.168.1.1
                set end-ip 192.168.1.2
            next
        end
        set timezone-option default
    next
end

```

**2 dhcp server: change to specify mode and add dns_server**

```
# cat main.tf
provider "fortios" {
  hostname = "192.168.52.177"
  insecure = "true"
  token    = "GNH7r40H65GNb46kd4rG8rtrmn0fr1"
}

resource "fortios_systemdhcp_server" "trname" {
  fosid           = 1
  dns_service     = "specify"
  default_gateway = "192.168.1.12"
  netmask         = "255.255.255.0"
  interface       = "port2"
  timezone_option = "default"
  dns_server1     = "10.1.1.1"
  dns_server2     = "11.1.1.1"
  dns_server3     = "0.0.0.0"
  dns_server4     = "0.0.0.0"
  ip_range {
    id       = 1
    start_ip = "192.168.1.1"
    end_ip   = "192.168.1.2"
  }
}

# terraform apply
.....

labfirewall (server) # show
path=system.dhcp, objname=server, tablename=(null), size=688
config system dhcp server
    edit 1
        set default-gateway 192.168.1.12
        set netmask 255.255.255.0
        set interface "port2"
        config ip-range
            edit 1
                set start-ip 192.168.1.1
                set end-ip 192.168.1.2
            next
        end
        set timezone-option default
        set dns-server1 10.1.1.1
        set dns-server2 11.1.1.1
    next
end
```
How does this sound to you? Thanks

**Comment by jonwilliams84** [comment]
Hi,

Thanks, I tried this on fortios 6.2.2 and 6.4.5. I call my resource from a module, and have resolved it with a conditional on the two parameters:

`resource "fortios_systemdhcp_server" "this" {
  count              = var.dhcp_server ? 1 : 0
  depends_on         = [fortios_system_interface.this]
  auto_configuration = "enable"
  status             = "enable"
  # = condition               ? true_val : false_val
  dns_service     = var.default_dns != true ? "specify" : "local"
  dns_server1     = var.default_dns != false ? null : var.dns_server1
  fosid           = random_integer.this.result
  lease_time      = 604800
  interface       = fortios_system_interface.this.name
  default_gateway = var.gatewayip
  netmask         = var.netmask
  ip_mode         = "range"
  server_type     = "regular"
  timezone_option = "default"
  ip_range {
    end_ip   = var.dhcp_endip
    id       = 1
    start_ip = var.dhcp_startip
  }
  dynamic "reserved_address" {
    for_each = var.reserved_address

    content {
      action = "reserved"
      id     = reserved_address.key + 1
      ip     = lookup(reserved_address.value, "ip", null)
      mac    = lookup(reserved_address.value, "mac", null)
      type   = "mac"
    }
  }
}
`
Happy to close this issue as it was probably just my usage that was causing the issue.

**Comment by frankshen01** [comment]
That's great! Thanks for the update, feel free to contact me if you need any further information. Thank you!
