### ISSUE TITLE
Can this Terraform's module configure FortiWeb?

### ISSUE THREAD

**Issue by Theerapong** [fortinetdev/terraform-provider-fortios#149]
I'd like to change configurations (switching traffic of network interface) of FortiWeb (WAF VM) by Terraform.

I'm not sure that can this Terraform's module (https://registry.terraform.io/providers/fortinetdev/fortios/latest) configure FortitWeb?

I launched FortiWeb on AWS temporality. 
Then, I used this command to see an access token.
`curl -k -v -X POST https://35.155.168.72:8443/api/fabric/authenticate -H 'Content-Type: application/json' -d '{"username":"admin", "password":"12345" }'`

Then, I tried to use this **.tf** to configure FortiWeb ->
https://github.com/Theerapong/Terraform-and-AWS-FortiWeb/blob/main/main.tf

Then, nothing happened.

Could I have some suggestion and/or example for these?

**Comment by frankshen01** [comment]
Hi @Theerapong, thanks for the issue. The provider is only used for FortiGate and FortiManager, as described in https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs#versioning. Regarding FortiWeb provider support, I suggest you contact the FortiWeb SE serving you, they can provide professional answers and their plans. Thanks!

**Comment by Theerapong** [comment]
@frankshen01 Thank you so much.

**Comment by Theerapong** [comment]
> Hi @Theerapong, thanks for the issue. The provider is only used for FortiGate and FortiManager, as described in https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs#versioning. Regarding FortiWeb provider support, I suggest you contact the FortiWeb SE serving you, they can provide professional answers and their plans. Thanks!

@frankshen01  Thank you so much

**Comment by frankshen01** [comment]
@Theerapong It's my pleasure. Thank you!
