### ISSUE TITLE
fortios_firewall_centralsnatmap need a way to sort the snat entries via policyid

### ISSUE THREAD

**Issue by pacrutchet** [fortinetdev/terraform-provider-fortios#157]
Hello,

fortios_firewall_centralsnatmap allow us to create snat entries with a policyid but their order is in the order of creation.

Is it possible to create a ressource like fortios_firewall_security_policysort in order to sort the snat in ascending policyid?

Regards,
Pierre

**Comment by frankshen01** [comment]
Hi @pacrutchet, yes, it's possible! Thanks for the great `Feature Request`. We have added it to the list of requirements to be implemented. It will be available in the next second or third release. Thanks @pacrutchet !

**Comment by frankshen01** [comment]
Hi @pacrutchet Supported and released, please see the latest version: 
https://registry.terraform.io/providers/fortinetdev/fortios/latest 
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_centralsnatmap_move
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_centralsnatmap_sort

https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/data-sources/fortios_firewall_centralsnatmap
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/data-sources/fortios_firewall_centralsnatmaplist

for details. Thanks!

**Comment by pacrutchet** [comment]
It works thanks a lot!
