### ISSUE TITLE
fortios_firewall_proxypolicy need a way to sort the proxy policy entries via policyid

### ISSUE THREAD

**Issue by pacrutchet** [fortinetdev/terraform-provider-fortios#162]
Hello,

fortios_firewall_proxypolicy creates entries with a policyid but their order is in the order of creation.

Is it possible to create a ressource like fortios_firewall_security_policysort in order to sort the proxy rules in ascending policyid?

Regards,
Pierre

**Comment by frankshen01** [comment]
Hi @pacrutchet, Thanks for the Feature Request. It will be added in the next release together with #157

**Comment by frankshen01** [comment]
Hi @pacrutchet Supported and released, please see the latest version:
https://registry.terraform.io/providers/fortinetdev/fortios/latest
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_proxypolicy_move
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_proxypolicy_sort

https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/data-sources/fortios_firewall_proxypolicy
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/data-sources/fortios_firewall_proxypolicylist

for details. Thanks!

**Comment by pacrutchet** [comment]
It works thanks a lot!
