### ISSUE TITLE
Error creating SystemInterface resource when creating an interface resource

### ISSUE THREAD

**Issue by cs-amatziab** [fortinetdev/terraform-provider-fortios#165]
Hi
im trying to create an ipsec tunnel and add the tunnel to the interface at the end
i used the interface example as seen down here but i keep getting

**│ Error: Error creating SystemInterface resource: Resource Not Found - Unable to find the specified resource (404)
│
│   with fortios_system_interface.trname3,
│   on fortigate-vpn.tf line 172, in resource "fortios_system_interface" "trname3":
│  172: resource "fortios_system_interface" "trname3" {resource "fortios_vpnipsec_phase1interface" "trname1" {**

this is my configuration

`resource "fortios_vpnipsec_phase1interface" "trname1" {
  acct_verify               = "disable"
  add_gw_route              = "disable"
  add_route                 = "enable"
  assign_ip                 = "enable"
  assign_ip_from            = "range"
  authmethod                = "psk"
  auto_discovery_forwarder  = "disable"
  auto_discovery_psk        = "disable"
  auto_discovery_receiver   = "disable"
  auto_discovery_sender     = "disable"
  auto_negotiate            = "enable"
  cert_id_validation        = "enable"
  childless_ike             = "disable"
  client_auto_negotiate     = "disable"
  client_keep_alive         = "disable"
  comments                  = "test vpn"
  default_gw                = "0.0.0.0"
  default_gw_priority       = 0
  dhgrp                     = "14 5"
  digital_signature_auth    = "disable"
  distance                  = 15
  dns_mode                  = "manual"
  dpd                       = "on-demand"
  dpd_retrycount            = 3
  dpd_retryinterval         = "20"
  eap                       = "disable"
  eap_identity              = "use-id-payload"
  encap_local_gw4           = "0.0.0.0"
  encap_local_gw6           = "::"
  encap_remote_gw4          = "0.0.0.0"
  encap_remote_gw6          = "::"
  encapsulation             = "none"
  encapsulation_address     = "ike"
  enforce_unique_id         = "disable"
  exchange_interface_ip     = "disable"
  exchange_ip_addr4         = "0.0.0.0"
  exchange_ip_addr6         = "::"
  forticlient_enforcement   = "disable"
  fragmentation             = "enable"
  fragmentation_mtu         = 1200
  group_authentication      = "disable"
  ha_sync_esp_seqno         = "enable"
  idle_timeout              = "disable"
  idle_timeoutinterval      = 15
  ike_version               = "2"
  include_local_lan         = "disable"
  interface                 = var.wan_interface
  ip_version                = "4"
  ipv4_dns_server1          = "0.0.0.0"
  ipv4_dns_server2          = "0.0.0.0"
  ipv4_dns_server3          = "0.0.0.0"
  ipv4_end_ip               = "0.0.0.0"
  ipv4_netmask              = "255.255.255.255"
  ipv4_start_ip             = "0.0.0.0"
  ipv4_wins_server1         = "0.0.0.0"
  ipv4_wins_server2         = "0.0.0.0"
  ipv6_dns_server1          = "::"
  ipv6_dns_server2          = "::"
  ipv6_dns_server3          = "::"
  ipv6_end_ip               = "::"
  ipv6_prefix               = 128
  ipv6_start_ip             = "::"
  keepalive                 = 10
  keylife                   = 86400
  local_gw                  = "0.0.0.0"
  local_gw6                 = "::"
  localid_type              = "auto"
  mesh_selector_type        = "disable"
  mode                      = "main"
  mode_cfg                  = "disable"
  monitor_hold_down_delay   = 0
  monitor_hold_down_time    = "00:00"
  monitor_hold_down_type    = "immediate"
  monitor_hold_down_weekday = "sunday"
  name                      = "${var.site_name}-VPN"
  nattraversal              = "enable"
  negotiate_timeout         = 30
  net_device                = "enable"
  passive_mode              = "disable"
  peertype                  = "any"
  ppk                       = "disable"
  priority                  = 0
  proposal                  = "aes128-sha256 aes256-sha256 aes128-sha1 aes256-sha1"
  psksecret                 = "fdsjiewnciqwekroiwrewlkrjewqj"
  reauth                    = "disable"
  rekey                     = "enable"
  remote_gw                 = var.peer_ip
  remote_gw6                = "::"
  rsa_signature_format      = "pkcs1"
  save_password             = "disable"
  send_cert_chain           = "enable"
  signature_hash_alg        = "sha2-512 sha2-384 sha2-256 sha1"
  suite_b                   = "disable"
  tunnel_search             = "selectors"
  type                      = "static"
  unity_support             = "enable"
  wizard_type               = "custom"
  xauthtype                 = "disable"
}

resource "fortios_vpnipsec_phase2interface" "trname2" {
  add_route                = "phase1"
  auto_discovery_forwarder = "phase1"
  auto_discovery_sender    = "phase1"
  auto_negotiate           = "disable"
  comments                 = "test"
  dhcp_ipsec               = "disable"
  dhgrp                    = "14 5"
  dst_addr_type            = "name"
  dst_end_ip               = "0.0.0.0"
  dst_end_ip6              = "::"
  dst_name                 = "GCP-Fabric-Test"
  dst_port                 = 0
  dst_start_ip             = "0.0.0.0"
  dst_start_ip6            = "::"
  dst_subnet               = "0.0.0.0 0.0.0.0"
  dst_subnet6              = "::/0"
  encapsulation            = "tunnel-mode"
  keepalive                = "disable"
  keylife_type             = "seconds"
  keylifekbs               = 5120
  keylifeseconds           = 43200
  l2tp                     = "disable"
  name                     = "${var.site_name}-P2-VPN"
  pfs                      = "enable"
  phase1name               = fortios_vpnipsec_phase1interface.trname1.name
  proposal                 = "aes128-sha1 aes256-sha1 aes128-sha256 aes256-sha256 aes128gcm aes256gcm chacha20poly1305"
  protocol                 = 0
  replay                   = "enable"
  route_overlap            = "use-new"
  single_source            = "disable"
  src_addr_type            = "name"
  src_end_ip               = "0.0.0.0"
  src_end_ip6              = "::"
  src_name                 = "MFC0-Network"
  src_port                 = 0
  src_start_ip             = "0.0.0.0"
  src_start_ip6            = "::"
  src_subnet               = "0.0.0.0 0.0.0.0"
  src_subnet6              = "::/0"
}

resource "fortios_system_interface" "trname3" {
  vdom        = "root"
  name        = fortios_vpnipsec_phase2interface.trname2.name
  ip          = "0.0.0.0 0.0.0.0"
  remote_ip   = "0.0.0.0 0.0.0.0"
  interface   = var.wan_interface
  allowaccess = "ping"
  tcp_mss     = "1350"

  autogenerated = "auto"
  depends_on = [
    fortios_vpnipsec_phase2interface.trname2
  ]
}`

**Comment by lix-fortinet** [comment]
Hi,

You can try to use phase1's name in resource fortios_system_interface, like this:
```
resource "fortios_system_interface" "trname3" {
  vdom = "root"
  name = fortios_vpnipsec_phase1interface.trname1.name
  ip = "0.0.0.0 0.0.0.0"
  remote_ip = "0.0.0.0 0.0.0.0"
  interface = var.wan_interface
  allowaccess = "ping"
  tcp_mss = "1350"
  
  autogenerated = "auto"
  depends_on = [
      fortios_vpnipsec_phase1interface.trname1
  ]
}
```

FortiGate will create a tunnel interface based on phase1's name of VPN tunnel. So, FortiGate will return this error since no phase2's name in system interfaces.

Thanks,
Xing

**Comment by cs-amatziab** [comment]
@lix-fortinet thanks that resolved my issue
