### ISSUE TITLE
provider "fortios"  hostname

### ISSUE THREAD

**Issue by crougher** [fortinetdev/terraform-provider-fortios#171]
Hi,

Im using 40net-cloud github https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate/Terraform/Active-Passive-ELB-ILB/terraform for FTG in Azure by using terraform.

My goal is to use terraform to deploy FGT in Azure, and also use terraform fortios to apply configuration after FGT-VM is UP.
Im trying to feed hostname with following variable: azurerm_public_ip.fgtamgmtpip.ip_address

https://github.com/40net-cloud/fortinet-azure-solutions/blob/main/FortiGate/Terraform/Active-Passive-ELB-ILB/terraform/02-fortigate.tf#L214

I have inserted [provider "fortios"] into 00-general.tf  [can be find in same repo: github https://github.com/40net-cloud/fortinet-azure-solutions/tree/main/FortiGate/Terraform/Active-Passive-ELB-ILB/terraform]

Could you let me know why assigning "azurerm_public_ip.fgtamgmtpip.ip_address" into hostname at provider level does not work?

```
terraform {
  required_providers {
    fortios = {
      source  = "fortinetdev/fortios"
      version = "1.13.0"
    }
  }
}

provider "fortios" {
  hostname     = azurerm_public_ip.fgtamgmtpip.ip_address
  token        = "${var.api-token}"
  insecure     = "true"
}


The error i got is the following when running "terraform plan":


 Error: FortiOS or FortiManager, at least one of their hostnames should be set
│
│   with module.deazthub.provider["registry.terraform.io/fortinetdev/fortios"],
│   on ../../modules/connectivity-prod/00.general.tf line 20, in provider "fortios":
│   20: provider "fortios" {

**Comment by lix-fortinet** [comment]
Hi @crougher,

Based on your output, it seems like hostname not been assigned any value. Please try the following steps:
    1. Add "data" in front of "azurerm_public_ip.fgtamgmtpip.ip_address" and try it again, like this:
```hcl
        provider "fortios" {
          hostname     = data.azurerm_public_ip.fgtamgmtpip.ip_address
          token        = "${var.api-token}"
          insecure     = "true"
        }
```
    2. If previous step not work, please check whether IP address is existed for your FGT-VM in Azure.

Please let me know if it still not work after tried these steps.

Thanks,
Xing

**Comment by crougher** [comment]
Sorry for late reply.
Basicaly Im trying to run in one terraform flow the following:
1. Build FGT
2. Apply FGT configuration

I think i have to use DNS, not public IP - as public IP is not known when i run terraform.
DNS is known so it should work.

Pleasee my config below:

`04_fortigate.tf
resource "azurerm_public_ip" "fgtbmgmtpip" {
  name                = "b-vm-fgt-mgmt-pip"
  location            = var.azure_region
  resource_group_name = azurerm_resource_group.rg.name
  allocation_method   = "Static"
  sku                 = "Standard"
  domain_name_label   = format("%s-%s", lower(var.azure_site_code), "fgtbmgmtpip")
  lifecycle {
    ignore_changes = [
      tags
    ]
  }
}


outputs.tf
data "template_file" "summary" {
  template = file("${path.module}/summary.tpl")
  vars = {
    username                        = var.USERNAME
    elb_ipaddress                   = data.azurerm_public_ip.elbpip.ip_address
    fgt_a_private_ip_address_ext    = azurerm_network_interface.fgtaifcext.private_ip_address
    fgt_a_private_ip_address_int    = azurerm_network_interface.fgtaifcint.private_ip_address
    fgt_a_private_ip_address_hasync = azurerm_network_interface.fgtaifchasync.private_ip_address
    fgt_a_private_ip_address_mgmt   = azurerm_network_interface.fgtaifcmgmt.private_ip_address
    fgt_a_public_ip_address         = data.azurerm_public_ip.fgtamgmtpip.ip_address
    fgt_a_public_fqdn               = azurerm_public_ip.fgtamgmtpip.fqdn
    fgt_b_private_ip_address_ext    = azurerm_network_interface.fgtbifcext.private_ip_address
    fgt_b_private_ip_address_int    = azurerm_network_interface.fgtbifcint.private_ip_address
    fgt_b_private_ip_address_hasync = azurerm_network_interface.fgtbifchasync.private_ip_address
    fgt_b_private_ip_address_mgmt   = azurerm_network_interface.fgtbifcmgmt.private_ip_address
    fgt_b_public_ip_address         = data.azurerm_public_ip.fgtbmgmtpip.ip_address
    fgt_b_public_fqdn               = azurerm_public_ip.fgtbmgmtpip.fqdn
    fgt_a_config                    = data.template_file.fgt_a_custom_data.rendered
    fgt_b_config                    = data.template_file.fgt_b_custom_data.rendered
  }
}

output "ftg_a_mgmt_ip" {
  value = azurerm_public_ip.fgtamgmtpip.ip_address
}

output "vnet_peerid" {
  value = azurerm_virtual_network.connectivity.id
}

output "fgt_a_public_fqdn" {
  value = azurerm_public_ip.fgtamgmtpip.fqdn
}

output "fgt_b_public_fqdn" {
  value = azurerm_public_ip.fgtbmgmtpip.fqdn
}


06_fgt_global.tf

provider "fortios" {
  hostname     = "${fgt_a_public_fqdn}:4434"
  token        = "mzsgqm1jGsGHcfycQxsndsmfhzpqks"
  insecure     = "true"
}

# GLB Settings
resource "fortios_system_global" "sysglobal" {
  admin_sport = 4434
  admintimeout  = "60"
  hostname    = "${var.azure_site_code}fwl1"
  timezone    = "${var.fgt_timezone}"
  fgd_alert_subscription  = "advisory latest-threat"
  two_factor_email_expiry = "300"
  two_factor_sms_expiry = "300"
  strong_crypto = "enable"
  gui_wireless_opensecurity = "enable"
  switch_controller = "enable"
}

resource "fortios_system_settings" "syssettings" {
  default_voip_alg_mode = "kernel-helper-based"
  gui_dns_database  = "enable"
  gui_ips = "enable"
  gui_local_in_policy = "enable"
  gui_multiple_utm_profiles = "enable"
}

`

I got following error when i run `terraform plan`:

`Error: Invalid reference
│ 
│   on ../../modules/connectivity-adv/06_fgt_global.tf line 2, in provider "fortios":
│    2:   hostname     = "${fgt_a_public_fqdn}:11443"
│ 
│ A reference to a resource type must be followed by at least one attribute access, specifying the resource name.
`

**Comment by lix-fortinet** [comment]
Hi @crougher,

The error you got is because of you are reference an output value in provider. You could reference a resource value in provider block, like `azurerm_public_ip.fgtamgmtpip.fqdn`. But this seems to be only available for arguments that configured by users. Terraform using key word `depends_on` to define processing sequence. But `depends_on` not applicable for provider block for now. Here is the reference: https://github.com/hashicorp/terraform/issues/2430. 

So, as my point of view, you need to have two separate Terrafrom deployment. 

Please let me know if you have any questions.

Thanks,
Xing

**Comment by crougher** [comment]
Hi @lix-fortinet,

Thank You for your feedback, i would have to go with two seperate terraform deployments.

Thx!
