### ISSUE TITLE
Error: expected vlan_cos_rev to be in the range (0 - 7), got 255

### ISSUE THREAD

**Issue by ccourson** [fortinetdev/terraform-provider-fortios#172]
Hello,

While performing `terraform plan -refresh=false`, having tf.policy.tf.json including lines as follows:

```
{
    "resource": {
        "fortios_firewall_policy": {
            "policyid_10": {
                ...,
                "vlan_cos_fwd": 255,
                "vlan_cos_rev": 255,
                ...
            }
        }
    }
}
```

I get the following errors:

> │Error: expected vlan_cos_rev to be in the range (0 - 7), got 255
> │
> │   on tf.policy.tf.json line 201, in resource.fortios_firewall_policy.policyid_10:
> │  201:             }
> │
>
> │ Error: expected vlan_cos_fwd to be in the range (0 - 7), got 255
> │
> │   on tf.policy.tf.json line 201, in resource.fortios_firewall_policy.policyid_10:
> │  201:             }
> │

Documentation states:

* vlan_cos_fwd - VLAN forward direction user priority: **255** passthrough, 0 lowest, 7 highest.
* vlan_cos_rev - VLAN reverse direction user priority: **255** passthrough, 0 lowest, 7 highest.

If I omit ```vlan_cos_fwd``` and ```vlan_cos_rev```, will they be treated as **passthrough**?

**Comment by lix-fortinet** [comment]
Hi @ccourson ，

Yes, if you omit ```vlan_cos_fwd``` and ```vlan_cos_rev```, they will be treated as passthrough.

Thanks,
Xing
