### ISSUE TITLE
Can not Add Realservers block in VIP

### ISSUE THREAD

**Issue by fariborzsaffari** [fortinetdev/terraform-provider-fortios#178]
hi ..
we i add realserver block to my code i got error 500
below is my sample code
i cant find any sample that shows how to add realservers block
######
resource "fortios_firewall_vip" "cloud_lb_test" {
  type                             = "server-load-balance"
  color                            = 0
  extintf                          = "any"
  extip                            = "My Public IP"
  extport                          = 80
  ldb_method                       = "static"
  name                             = "vips1"

  realservers {
      type="ip"
      ip="192.168.200.1"
      port=80
      status="active"
  }

}

**Comment by lix-fortinet** [comment]
Hi @fariborzsaffari ,

Thank you for raising this issue. Could I know which version of FOS do you use?

Thanks,
Xing

**Comment by fariborzsaffari** [comment]
I worked with the latest version of FortiOS, 7.0.1
I also noticed that some configurations do not apply, such as ldb-method, after any changes.
thanks in advance for your help

**Comment by lix-fortinet** [comment]
Hi @fariborzsaffari ,

Thank you for your information. Parameter `server_type` is required when `type` is set to `server-load-balance`. Could you add parameter `server_type` and try it again, like this:
```
resource "fortios_firewall_vip" "cloud_lb_test" {
  type = "server-load-balance"
  color = 0
  extintf = "any"
  extip = "<<YOUR IP>>"
  ldb_method = "static"
  server_type = "http"
  extport = 80
  name = "vips1"
  realservers {
    type="ip"
    ip="192.168.200.1"
    port=80
    status="active"
  }
}
```

Please let me know if it still not work.

Thanks,
Xing

**Comment by MaxxLiu22** [comment]
Hi @fariborzsaffari 

I will go ahead to close this case, if your question is still not solved, feel free to reopen it or another case.

Thanks,
Maxx
