### ISSUE TITLE
Data source to retrieve fortigate model

### ISSUE THREAD

**Issue by gmintoco** [fortinetdev/terraform-provider-fortios#180]
Hi,
I have searched through the documentation here but cannot find a datasource or resource that can give me the model of fortigate (essentially a data source for `get system status`) 

Does such a data source exist? If so what is it? If it doesn't is there any way of getting the model of the fortigate via terraform?

Thanks,
Gus

**Comment by lix-fortinet** [comment]
Hi @gmintoco ，

Thank you for raising this issue. `/api/v2/monitor/system/status` is a monitor API. Monitor APIs are stateless, and we do not provide resources for stateless APIs.

You could get the system status using generic resource:
`https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_json_generic_api`
Like this:
```
resource "fortios_json_generic_api" "test1" {
  path   = "/api/v2/monitor/system/status"
  method = "GET"
  json   = ""
}

output "response1" {
  value = "${fortios_json_generic_api.test1.response}"
}
```

Please let me know if you have any questions.

Thanks,
Xing

**Comment by gmintoco** [comment]
Thanks that worked for me :)
