### ISSUE TITLE
Policy Drift Detection

### ISSUE THREAD

**Issue by MrMinos** [fortinetdev/terraform-provider-fortios#181]
Hello,

I could not confirm details on policy drift detections, and would appreciate your help.

I've confirmed the drift detection in Firewall policies, if the rules created with `terraform` has been changed using Web GUI. However, if I create a new rule using the web GUI in between `terraform apply`, and `terraform plan`, I did not see the changes made. Is this an expected outcome? Thanks!

**Comment by lix-fortinet** [comment]
Hi @MrMinos ,

Thank you for raising this issue. I am not quite sure about your question. Do you mean `create by GUI` --> `make some changes by Terraform` --> `don't see the changes made`? I would appreciate it if you could provide some details of the issue, like the reproduce process and the .tf file.

Thanks,
Xing

**Comment by MrMinos** [comment]
Xing,

I meant `create a policy with terraform` --> `make some changes by GUI` --> `terraform doesn't see the changes made`. This now makes sense to me, and seems like an expected behavior. Thanks!
