### ISSUE TITLE
Sample List of Virtual IPs and Virtual Servers

### ISSUE THREAD

**Issue by martinimartinimartini** [fortinetdev/terraform-provider-fortios#183]
Hi guys!

I recent changed jobs and on the new organization people created vips and vservers for the wan income connections reach the DMZ.
The point is: I'm trying to use terraform to list all this public address used but I cant find a data fortios_firewall_vip|vserver(list)
like i have with address: data "fortios_firewall_addresslist".

Am I missing something or it's still not develop yet ?

**Comment by lix-fortinet** [comment]
Hi @martinimartinimartini ,

Thank you for raising this issue. 

I would appreciate it if you could specify which resource or API do you mean for vservers.

As for firewall vip, we do not have a data source to list all firewall vip yet. We will plan to add it in the future release. 

You could get the firewall vip using generic resource:
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/data-sources/fortios_json_generic_api
Like this:

```
data "fortios_json_generic_api" "example_1" {
  path = "/api/v2/cmdb/firewall/vip"
}

output res_get_all_policy {
  value = jsondecode(data.fortios_json_generic_api.example_1.response).results
}
```
Please let me know if you have any questions.

Thanks,
Xing

**Comment by martinimartinimartini** [comment]
Thanks for the advice!
I didn't know about the generic data, it will help a lot.
You can close now!! Really appreciated

**Comment by lix-fortinet** [comment]
Hi @martinimartinimartini ,

You are very welcome. Thank you for your issue, which makes our product and service better!

Thanks,
Xing
