### ISSUE TITLE
fortios_ips_sensor entries severity trailing space

### ISSUE THREAD

**Issue by MilesTails** [fortinetdev/terraform-provider-fortios#184]
Hi,

Looks like FortiGate's returns a trailing space at the end of a severity statement so you end up with constant change in place:

Resource:
```
resource "fortios_ips_sensor" "test_ips" {
  name                    = "test_ips"
  scan_botnet_connections = "block"
  block_malicious_url     = "enable"
  entries {
    id         = 1
    severity   = "high critical"
    log_packet = "enable"
    action     = "block"
  }
  entries {
    id       = 2
    severity = "info low medium"
    action   = "default"
  }
}
```

Snippet from plan post creation:
```
  ~ entries {
            id                 = 1
          ~ severity           = "high critical " -> "high critical"
```

Is this something that can be resolved in the module or do we need to always leave a trailing space in our severity variable.

**Comment by lix-fortinet** [comment]
Hi @MilesTails ,

Thank you for raising this issue. Team is working on this issue. We will reply to you ASAP.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @MilesTails ,

We will fix this issue in the next release. 

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @MilesTails,

FortiOS Terraform provider v1.14.0 fixed this issue and has been released. Please upgrade to the latest version of FortiOS Terraform provider and try it again.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @MilesTails,

We will close this issue since it has been fixed. Feel free to open a new issue if you have any other questions.

Thanks,
Xing
