### ISSUE TITLE
Enable STP on hardware-switches

### ISSUE THREAD

**Issue by xabinapal** [fortinetdev/terraform-provider-fortios#189]
Maybe I'm missing something, but it seems this provider does not support enabling STP on a hardware switch. Typically, I would execute the following on the console to create a new HW switch:

```
config system virtual-switch
  edit "myhwsw"
    set physical-switch "sw0"
    config port
      edit "internal6"
      next
      edit "internal7"
      next
    end
  next
end

config system interface
  edit "myhwsw"
    set role lan
    set ip 10.255.255.254 255.255.255.0
    set stp enable
  next
end
```

I'm currently working on migrating our provisioning scripts to Terraform, and the previous snippet translates (roughly) to:

```
resource "fortios_system_virtualswitch" "myhwsw" {
  name = "myhwsw"

  physical_switch = "sw0"

  port {
    name = "internal6"
  }

  port {
    name = "internal7"
  }
}

resource "fortios_system_interface" "myhwsw" {
  name = fortios_system_virtualswitch.myhwsw.name
  vdom = "root"

  autogenerated = "auto"

  role = "lan"
  mode = "static"

  ip = "10.255.255.254/24"
}
```

As per the docs, there is no `stp` parameter in `fortios_system_interface` resources. I also tried it in case it was undocumented, with no luck.

**Comment by lix-fortinet** [comment]
Hi @xabinapal,

FortiOS Terraform provider v1.14.0 fixed this issue and has been released. Please upgrade to the latest version of FortiOS Terraform provider and try it again.

Thanks,
Xing

**Comment by xabinapal** [comment]
Just verified in 1.14.1 that this is supported now. Thanks!

```
resource "fortios_system_interface" "myhwsw" {
  stp = "enable"
}
```
