### ISSUE TITLE
No helpful error output

### ISSUE THREAD

**Issue by kev-in-shu** [fortinetdev/terraform-provider-fortios#193]
When we try and apply an invalid configuration, terraform does not give any helpful message as to what the error is.

For example when creating a firewall policy with an incorrect source interface, this is all we get

`Error: Error creating FirewallPolicy resource: Internal Server Error - Internal error when processing the request (500)`

I tried to target the API directly, and it seems it gives some more useful details

```
node_check_object fail! for name port2032
value parse error before 'port2032'
Command fail. Return code -651

```

**Comment by lix-fortinet** [comment]
Hi @kev-in-shu,

Thank you for raising this issue. Team are working on this issue. We will improve this by identifying useful info from API response and output it to users. And we will let you know when we released the new version of Terraform FortiOS provider. 

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @kev-in-shu,

The latest version of FortiOS Terraform provider(v1.14.0) added the 'cli_error' from HTTP response to Terraform output. Hope this will give you some useful details. We will work with API team and continually improve our provider to satisfy users as much as we can. Thank you for raising this issue!

Thanks,
Xing

**Comment by kev-in-shu** [comment]
Hi Xing,

I could test the new release. This improvement in error handling is really useful!

Thanks
Kevin
