### ISSUE TITLE
Provide darwin/arm64 binaries for Apple M1 

### ISSUE THREAD

**Issue by movd** [fortinetdev/terraform-provider-fortios#194]
Enhancement: Add release binaries for Apple Silicon

**Comment by lix-fortinet** [comment]
Hi @movd,

Thank you for raising this issue. Team are working on it.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @movd,

The latest version of FortiOS Terraform provider(v1.14.0) added binary file of darwin/arm64. 

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @movd,

We will close this issue since it has been fixed. Feel free to open a new issue if you have any other questions.

Thanks,
Xing
