### ISSUE TITLE
Link monitor should support millisecond intervals

### ISSUE THREAD

**Issue by xabinapal** [fortinetdev/terraform-provider-fortios#195]
Currently, resource `fortios_system_linkmonitor` expects the `interval` parameter to be specified in seconds, with a range between `1` and `3600`:

https://github.com/fortinetdev/terraform-provider-fortios/blob/master/fortios/resource_system_linkmonitor.go#L121

This fails with newer firmware versions. Starting on FortiOS 6.2.1, this parameter should be specified in milliseconds, with a range between `500` and `3600000`: https://docs.fortinet.com/document/fortigate/6.2.1/cli-reference/101620/system-link-monitor

Terraform developer best practices state that this kind of validations should not be performed in the provider's code. Instead, the API call should fail if the value provided is not allowed. This would allow to support multiple FortiOS versions without requiring code changes.

**Comment by lix-fortinet** [comment]
Hi @xabinapal,

Thank you for raising this issue. Team are working on it. We will fix it in the next release.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @xabinapal,

FortiOS Terraform provider v1.14.0 fixed this issue and has been released. Please upgrade to the latest version of FortiOS Terraform provider and try it again.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @xabinapal,

We will close this issue since it has been fixed. Feel free to open a new issue if you have any other questions.

Thanks,
Xing
