### ISSUE TITLE
`fortios_router_ospf` router id and redistribution route map not removed

### ISSUE THREAD

**Issue by afmoreno1982** [fortinetdev/terraform-provider-fortios#196]
Resource `fortios_router_routemap.fgt01conf_rmap_01` can't be destroy, because `fortios_router_ospf.fgt01conf_rtospf` doesn't destroy `router-id` nor `routemap` inside `redistribute` block.

Using `fortinetdev/fortios/1.13.2`

Resourse applied:
```terraform
resource "fortios_router_ospf" "fgt01conf_rtospf" {
  provider         = fortios.fgt01

  depends_on = [
    fortios_system_interface.fgt01conf_int_loopback,
  ]

  router_id        = "169.254.12.5"
  area {
    id             = "0.0.0.0"
  }
  ospf_interface {
    name           = "OSPF-INT"
    interface      = module.fgt01conf_vpn_fgt01-fgt04.output.intf.name
    network_type   = "point-to-point"
    authentication = "message-digest"
    md5_keys {
      id           = 7
      key_string   = random_password.rnd_passwd_ospf["01"].result
    }
    
  }
  network {
    id             = 1
    prefix         = "169.254.12.4 255.255.255.252"
  }

  passive_interface { name = "fortilink" }
  passive_interface { name = "ssl.root" }
  passive_interface { name = "port3" }
  passive_interface { name = "Lo01" }

  redistribute {
    metric      = 0
    metric_type = "2"
    name        = "connected"
    status      = "enable"
    tag         = 0
    routemap    = fortios_router_routemap.fgt01conf_rmap_01.id
  }
  redistribute {
    metric      = 0
    metric_type = "2"
    name        = "static"
    status      = "disable"
    tag         = 0
  }
  redistribute {
    metric      = 0
    metric_type = "2"
    name        = "rip"
    status      = "disable"
    tag         = 0
  }
  redistribute {
    metric      = 0
    metric_type = "2"
    name        = "bgp"
    status      = "disable"
    tag         = 0
  }
  redistribute {
    metric      = 0
    metric_type = "2"
    name        = "isis"
    status      = "disable"
    tag         = 0
  }

}
```

Error during `terraform destroy`:
![image](https://user-images.githubusercontent.com/44612768/143659844-9368c595-e8c3-44d2-b41f-16deaf6197a0.png)

When reviewing the _Fortigate CLI_ configuration, the following persist
![image](https://user-images.githubusercontent.com/44612768/143659944-dc409aa4-7e47-42bb-9411-312dc974d79b.png)

**Comment by lix-fortinet** [comment]
Hi @afmoreno1982,

Thank you for raising this issue. Team are working on it. We will get back to you once it's resolved.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @afmoreno1982,

This issue has been fixed in the latest release of FortiOS Terraform provider v1.14.1. Please switch to the latest version of FortiOS Terraform provider and try it again.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @afmoreno1982,

We will close this issue since it has been fixed. Feel free to open a new issue if you have any other questions.

Thanks,
Xing
