### ISSUE TITLE
Cant create admin user with `fortios_system_admin`

### ISSUE THREAD

**Issue by ichasco-heytrade** [fortinetdev/terraform-provider-fortios#197]
Hi,

I am trying to create an admin user in fortigate but always get the same error:

```╷
│ Error: Error creating SystemAdmin resource: Internal Server Error - Internal error when processing the request (500)
│ 
│   with fortios_system_admin.devops,
│   on users.tf line 5, in resource "fortios_system_admin" "devops":
│    5: resource "fortios_system_admin" "devops" {
│ 
╵
```

Terraform code:
```
resource "fortios_system_admin" "devops" {
  name       = "devops"
  accprofile = "super_admin"
  password   = "XXXXXXXXXXXXXXXXXX"
}
```

I have also tried to create manually and then import and also got an error:

```
 terraform import fortios_system_admin.devops devops                                                  
Acquiring state lock. This may take a few moments...
fortios_system_admin.devops: Importing from ID "devops"...
fortios_system_admin.devops: Import prepared!
  Prepared fortios_system_admin for import
fortios_system_admin.devops: Refreshing state... [id=devops]
╷
│ Error: Cannot import non-existent remote object
│ 
│ While attempting to import an existing object to "fortios_system_admin.devops", the provider detected that no object exists with the given id. Only pre-existing objects can be imported; check that
│ the id is correct and that it is associated with the provider's configured region or endpoint, or use "terraform apply" to create a new remote object for this resource.
```

Fortigate version: `7.0.2`
Terraform provider version: `v1.13.2`

Thanks!

**Comment by alagoutte** [comment]
Do you have check the complexity of the password ?

do you have look on httpd debug log ?

**Comment by ichasco-heytrade** [comment]
I have tried the same password as the user I created.

I didn't see nothing in the logs :(

If you try, you can create an admin user? Can you pass me the code to see if there is something different?

Thanks

**Comment by alagoutte** [comment]
i don't yet try... 

can you try
```
diagnose debug enable
diagnose debug application httpsd -1
```

on FortiGate CLI ?

**Comment by ichasco-heytrade** [comment]
Here you have the errors in the log:
```
[httpsd 12075 - 1638301223    error] cmdb_save_with_children[285] -- saving failed for main node: 'admin' (err=-3)

[httpsd 12075 - 1638301223    error] cmdb_commit_from_json[1688] -- error saving request object to CLI (-3)
[httpsd 12075 - 1638301223    error] _api_cmdb_v2_config[1383] -- error editing object (nret=-3)
[httpsd 12075 - 1638301223  warning] api_return_http_result[1247] -- API error -3 raised
[httpsd 12075 - 1638301223     info] handle_cli_req_v2[3150] -- returning to original vdom "root"
[httpsd 12075 - 1638301223     info] fweb_debug_final[296] -- Completed POST request for "/api/v2/cmdb/system/admin" (HTTP 500)
```

**Comment by lix-fortinet** [comment]
Hi @ichasco-heytrade,

Thank you for raising this issue. Could you check whether the token that you used in the provider is using admin profile `super_admin`? It is required if you want to configure VDOM or resources related to administrator user permissions. Please check step3 of this guide of [Generate an API token for FortiOS](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/guides/fgt_token#:~:text=Note%3A%20If%20you%20want%20to%20configure%20VDOM%20or%20resources%20related%20to%20administrator%20user%20permissions%2C%20you%20need%20to%20set%20the%20field%20with%20the%20System%20predefined%20Administrator%20Profile%20super_admin%20by%20CLI.).

If this still not work, I will appreciate it if you could give me the following info, so that I can reproduce this issue:
1. What is your Terraform version? You could run `terraform version` in your terminal to check.
2. Is your FOS in multi-vdom mode?
3. Do you config the argument `vdom` in your provider block?

Please let me know if you have any questions.

Thanks,
Xing

**Comment by ichasco-heytrade** [comment]
Hi!
These are the permissions of the admin profile:
```
{
  "method": "POST",
  "url": "/api/v2/cmdb/system/accprofile",
  "params": {
    "vdom": "root"
  },
  "data": {
    "name": "terraform",
    "secfabgrp": "read-write",
    "ftviewgrp": "read-write",
    "authgrp": "read-write",
    "sysgrp": "read-write",
    "netgrp": "read-write",
    "loggrp": "read-write",
    "fwgrp": "read-write",
    "vpngrp": "read-write",
    "utmgrp": "read-write",
    "wanoptgrp": "read-write",
    "wifi": "read-write"
  }
}
```

Terraform version:

```
Terraform v1.0.11
on linux_amd64
+ provider registry.terraform.io/fortinetdev/fortios v1.13.2
+ provider registry.terraform.io/hashicorp/vault v3.0.1
```

I am not using multi-vdom

Thanks!

**Comment by lix-fortinet** [comment]
Hi @ichasco-heytrade,

Customized profile has lower permission then `super_admin`. You could not create an admin user with `super_admin` profile using a lower permission admin user. You could create an admin user with the same profile:
```
resource "fortios_system_admin" "devops" {
  name       = "devops"
  accprofile = "terraform"
  password   = "XXXXXXXXXXXXXXXXXX"
}
```

Please let me know if you have any questions.

Thanks,
Xing

**Comment by ichasco-heytrade** [comment]
And how can I create admin profile with super_admin permissions? In the REST api admin I can't associate with super_admin profile, only with I have created before.

Thanks!

**Comment by poroping** [comment]
> And how can I create admin profile with super_admin permissions? In the REST api admin I can't associate with super_admin profile, only with I have created before.
> 
> Thanks!

You need to do it in the CLI

**Comment by lix-fortinet** [comment]
Hi @ichasco-heytrade,

You could set profile to `super_admin` by CLI or API using an account with `super_admin` permission. But you could not set it by GUI.

Thanks,
Xing

**Comment by ichasco-heytrade** [comment]
Perfect thanks!

This is the code that has to be executed in forti CLI
```
config system api-user
    edit "API_USER"
        set accprofile "super_admin"
        end
    next
end
```
