### ISSUE TITLE
Disable SSLVPN in terraform 

### ISSUE THREAD

**Issue by rpuserh** [fortinetdev/terraform-provider-fortios#201]
Hi,

Im trying to disable SSLVPN with terraform 

In cli i will do 
```
config vpn ssl settings
    set status disable
end
```

but terraform dosent have status propertu for VPNSSL option

```
resource "fortios_vpnssl_settings" "trname" {
  port          = 4433
  status        = "disable"
}
```

Please advise what will be best way to disable SSLVPN

**Comment by lix-fortinet** [comment]
Hi @rpuserh,

Thank you for raising this issue. Team are working on this issue. We will fix it in the next release. Before that, you could use resource `fortios_system_autoscript` as alternatives:
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_system_autoscript
For example:
```
resource "fortios_system_autoscript" "auto" {
  interval    = 1
  name        = "myscript"
  output_size = 10
  repeat      = 1
  script      = <<EOF
config vpn ssl settings
    set status disable
end
EOF
  start       = "auto"
}
```

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @rpuserh,

FortiOS Terraform provider v1.14.0 fixed this issue and has been released. Please upgrade to the latest version of FortiOS Terraform provider and try it again.

Thanks,
Xing
