### ISSUE TITLE
fortios routerbgp neighbor destroy will remove other existing ones

### ISSUE THREAD

**Issue by mobilesuitzero** [fortinetdev/terraform-provider-fortios#202]
my Terraform configuration
Using fortinetdev/fortios/1.13.2

resource "fortios_router_bgp" "bgp" {
  depends_on           = [fortios_vpnipsec_phase2interface.vwan2phase2]
  as                   = "7224"
  cluster_id           = "169.254.24.24"
  ibgp_multipath       = "enable"
  network_import_check = "disable"

}

resource "fortios_routerbgp_neighbor" "neighbor1" {
  depends_on           = [fortios_router_bgp.bgp]
  ip                   = "1.1.1.1"
  remote_as            = "65515"
  soft_reconfiguration = "enable"
}

resource "fortios_routerbgp_neighbor" "neighbor2" {
  depends_on           = [fortios_router_bgp.bgp]
  ip                   = "1.1.1.2"
  remote_as            = "65515"
  soft_reconfiguration = "enable"
}

After apply, it will add the new neighbor.

config router bgp
    set as 7224
    set router-id 169.254.24.24
    set ibgp-multipath enable
    set network-import-check disable
    set cluster-id 169.254.24.24
    config neighbor
        edit "10.26.0.12"
            set remote-as 65515
        next
        edit "10.26.0.13"
            set remote-as 65515
        next
        edit "169.254.35.209"
            set soft-reconfiguration enable
            set remote-as 64512
            set local-as 65000
        next
        edit "169.254.74.221"
            set soft-reconfiguration enable
            set remote-as 64512
            set local-as 65000
        next
        edit "10.0.0.12"
            set soft-reconfiguration enable
            set remote-as 65515
        next
        edit "1.1.1.1"
            set soft-reconfiguration enable
            set remote-as 65515
        next
        edit "1.1.1.2"
            set soft-reconfiguration enable
            set remote-as 65515
        next
    end  
    config network
        edit 1
            set prefix 172.16.136.0 255.255.255.0
        next
    end
    config redistribute "connected"
    end
    config redistribute "rip"
    end
    config redistribute "ospf"
    end
    config redistribute "static"
    end
    config redistribute "isis"
    end
    config redistribute6 "connected"
    end
    config redistribute6 "rip"
    end
    config redistribute6 "ospf"
    end
    config redistribute6 "static"
    end
    config redistribute6 "isis"
    end
end

However, after destroy.
fortios_routerbgp_neighbor.neighbor1: Destroying... [id=1.1.1.1]
fortios_routerbgp_neighbor.neighbor2: Destroying... [id=1.1.1.2]
fortios_routerbgp_neighbor.neighbor1: Destruction complete after 0s
fortios_routerbgp_neighbor.neighbor2: Destruction complete after 0s
fortios_router_bgp.bgp: Destroying... [id=RouterBgp]
fortios_router_bgp.bgp: Destruction complete after 0s

BGP settings has lost all the neighbors and network.
config router bgp
    set as 7224
    set router-id 169.254.24.24
    set ibgp-multipath enable
    set network-import-check disable
    set cluster-id 169.254.24.24
    config redistribute "connected"
    end
    config redistribute "rip"
    end
    config redistribute "ospf"
    end
    config redistribute "static"
    end
    config redistribute "isis"
    end
    config redistribute6 "connected"
    end
    config redistribute6 "rip"
    end
    config redistribute6 "ospf"
    end
    config redistribute6 "static"
    end
    config redistribute6 "isis"
    end
end

Is there a way to work around and not destroy the existing settings?

Thanks.

**Comment by lix-fortinet** [comment]
Hi @mobilesuitzero,

Thank you for raising this issue. This issue is because you also destroyed resource `fortios_router_bgp`. Resource `fortios_router_bgp` is pre-existed in FortiOS, there is no `DELETE` operation for REST API `/api/v2/cmdb/router/bgp`. Our current logic for `destroy` or `delete` operation for resource `fortios_router_bgp` is to set all block arguments to empty. 

Here are two solutions:
1. Using `-target` to specify resources you want to destroy, and ignore resource `fortios_router_bgp`:
`$ terraform destroy --auto-approve -target fortios_routerbgp_neighbor.neighbor1 -target fortios_routerbgp_neighbor.neighbor2`

2. Delete the record of resource `fortios_router_bgp` from the state file. Then run `terraform destroy`.  In this way, Terraform will not destroy resource `fortios_router_bgp`:
`$ terraform state rm fortios_router_bgp.bgp`

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @mobilesuitzero,

We will close this issue since this is not an issue. Feel free to open a new issue if you have any other questions.

Thanks,
Xing
