### ISSUE TITLE
Firewall-vip import not importing all properties

### ISSUE THREAD

**Issue by tomelfring** [fortinetdev/terraform-provider-fortios#206]
We're currently running into issues when importing some Virtual Servers. The resulting terraform state doens't contain all values, resulting in updates when first applying the terrafom files.

In the [gist ](https://gist.github.com/tomelfring/2108f6afddc49f98c58a6b07736be942) can be found:
- fortigate.conf -> The commands to create the Virtual Server (VIP) through the CLI
- main.tf -> The terraform file used
- terraform.tfstate -> The resulting state
- trace.log -> Trace logging of the import

Steps taken:
- Create the resources through the CLI
- Run `TF_LOG=TRACE terraform import fortios_firewall_vip.test-vip VIP-172.0.0.1` to import (note, I've removed the api keys in main.tf)
- Observe that the terraform state doesn't contain `monitor` and `realserver` entries.

Info:
- Terraform v1.1.4 on linux_amd64 + provider registry.terraform.io/fortinetdev/fortios v1.13.2
- FortiGate VM64 v6.4.8 build1914 (GA)

**Comment by lix-fortinet** [comment]
Hi @tomelfring,

Thank you for raising this issue. Team are working on it. We will get back to you once it's resolved.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @tomelfring,

This issue has been fixed in the latest release of FortiOS Terraform provider v1.14.1. Please switch to the latest version of FortiOS Terraform provider and try it again.

Thanks,
Xing

**Comment by tomelfring** [comment]
Hi @lix-fortinet,

I can confirm the issue has been fixed.
