### ISSUE TITLE
Firewall-vip change in realserver triggers ldb-method change

### ISSUE THREAD

**Issue by tomelfring** [fortinetdev/terraform-provider-fortios#207]
We're currently running into issues when changing some Virtual Servers. When changing a setting of a `realserver`, the `ldb-method` changes.

In the [gist ](https://gist.github.com/tomelfring/0c7f9722760aefc333b1a0a3938af2ca) can be found:
- fortigate.conf -> The commands to create the Virtual Server (VIP) through the CLI
- initial_main.tf -> The initial terraform file
- initial_terraform.tfstate -> The initial terraform state file
- changed_main.tf -> The new terraform file (switched the `active`/`standby` on the `realservers`)
- tfplan.log -> Output of  `TF_LOG=TRACE terraform plan -out out.tfplan`
- tfapply.log -> Output of `TF_LOG=TRACE terraform apply "out.tfplan"`
- changed_terraform.tfstate -> The resulting terraform state file

Steps taken:
- Create the resources through the CLI
- Use `initial_main.tf` & `initial_terraform.tfstate` and observe with terraform plan that there are no changes
- Replace `initial_main.tf` with `changed_main.tf`
- Execute `TF_LOG=TRACE terraform plan -out out.tfplan` and observe only planned changes to realservers
- Execute `TF_LOG=TRACE terraform apply "out.tfplan"`
- Observe that the output of terraform apply & the terraform state contain `ldb-method` = `static` and the VirtualServer is also set to static loadbalancing

Expected:
- Only change the `realserver` objects, not the loadbalancing method

Info:
- Terraform v1.1.4 on linux_amd64 + provider registry.terraform.io/fortinetdev/fortios v1.13.2
- FortiGate VM64 v6.4.8 build1914 (GA)

**Comment by lix-fortinet** [comment]
Hi @tomelfring,

Thank you for raising this issue. We are working with REST API team to find a solution. A bug ticket has been created internally to track this issue, and we will get back to you once it's resolved. 

Thanks,
Xing

**Comment by MaxxLiu22** [comment]
Hi all,

I will go ahead and close this case due to inactivity, but please don’t hesitate to reach out or open a new case if you have any further questions.

Thanks,
Maxx
