### ISSUE TITLE
dynamic sort subtable issue for service groups

### ISSUE THREAD

**Issue by MilesTails** [fortinetdev/terraform-provider-fortios#217]
Hi, I think this is the same problem as #164, dynamic sort subtable is still showing mis-matched information for my service objects as it's assuming, for example, tcp_10511 should be before tcp_2002.

TF Provider 1.14.0

Example var:
```
variable "_promtheus" {
  type        = list(string)
  description = "prometheus"
  default = [
    "tcp_4002",
    "tcp_5002",
    "tcp_8080",
    "tcp_8106",
    "tcp_9100",
    "tcp_9121",
    "tcp_9168",
    "tcp_9182",
    "tcp_9183",
    "tcp_9236",
    "tcp_9252",
    "tcp_9253",
    "tcp_9256",
    "tcp_10511",
    "tcp_10515",
    "tcp_10518",
    "tcp_10599",
    "tcp_20002",
    "PING",
    "tcp_2002",
    "SNMP",
    "web",
  ]
}
```
Example TF:

```
resource "fortios_firewallservice_group" "_prometheus" {
  name                  = "prometheus"
  dynamic_sort_subtable = true
  dynamic "member" {
    for_each = toset(var._prometheus)

    content {
      name = member.value
    }
  }
}
```
Example TF Plan output:

```
  ~ resource "fortios_firewallservice_group" "_prometheus" {
        id                    = "prometheus"
        name                  = "prometheus"
        # (4 unchanged attributes hidden)
      ~ member {
          ~ name = "tcp_2002" -> "tcp_10511"
        }
      ~ member {
          ~ name = "tcp_4002" -> "tcp_10515"
        }
      ~ member {
          ~ name = "tcp_5002" -> "tcp_10518"
        }
      ~ member {
          ~ name = "tcp_8080" -> "tcp_10599"
        }
      ~ member {
          ~ name = "tcp_8106" -> "tcp_20002"
        }
      ~ member {
          ~ name = "tcp_9100" -> "tcp_2002"
        }
      ~ member {
          ~ name = "tcp_9121" -> "tcp_4002"
        }
      ~ member {
          ~ name = "tcp_9168" -> "tcp_5002"
        }
      ~ member {
          ~ name = "tcp_9182" -> "tcp_8080"
        }
      ~ member {
          ~ name = "tcp_9183" -> "tcp_8106"
        }
      ~ member {
          ~ name = "tcp_9236" -> "tcp_9100"
        }
      ~ member {
          ~ name = "tcp_9252" -> "tcp_9121"
        }
      ~ member {
          ~ name = "tcp_9253" -> "tcp_9168"
        }
      ~ member {
          ~ name = "tcp_9256" -> "tcp_9182"
        }
      ~ member {
          ~ name = "tcp_10511" -> "tcp_9183"
        }
      ~ member {
          ~ name = "tcp_10515" -> "tcp_9236"
        }
      ~ member {
          ~ name = "tcp_10518" -> "tcp_9252"
        }
      ~ member {
          ~ name = "tcp_10599" -> "tcp_9253"
        }
      ~ member {
          ~ name = "tcp_20002" -> "tcp_9256"
        }
        # (3 unchanged blocks hidden)
    }
```

**Comment by Bilalbc** [comment]
Hello, I am also experiencing a similar problem in which I use "dynamic_sort_subtable" to order the entries, but this seems to only work for the address groups, whereas the service groups show that there are changes to be made all the time.

**Comment by MilesTails** [comment]
Had a poke around, raised #218 as a suggested fix for this problem. Tested locally, looks good to me.

**Comment by MilesTails** [comment]
There are many objects it would seem that should be alpha numeric sorted rather than naturally sorted. I am not sure what the correct way to process and review all these objects would be. However I can see that source/destination subtables within the fortios_firewall_policy resource are also wrongly sorted. My merge has been updated to reflect this change.

**Comment by MilesTails** [comment]
Yes and on the cloned dynamic_sort_subtable function it has the natural sort removed.

**Comment by lix-fortinet** [comment]
Hi @MilesTails,

Thank you for raising this issue and contributing to Terraform FortiOS provider.  #164 was to request the natural sort for the resource, which is the opposite way to this issue. The reason of this issue is the mismatch of the sequence of list in .tf file and state file. `dynamic_sort_subtable` will sort the list returned from FortiOS, which means it sorted the list in Terraform state file. But the provider could not control the sequence in .tf file. It needs to be handled by users. So we use natural sort in `dynamic_sort_subtable` which is easier for user to make the sequence in Terraform configuration. For your scenario, you used function `toset()` which somehow seems like sorted the list in alphanumeric. But `set` do not have ordering, and we could not assume it is ordered by alphanumeric. Here is the definition of datatype `set` by Terraform: https://www.terraform.io/language/expressions/type-constraints#set.

We have some other issues about `dynamic_sort_subtable` in recent months. And this issue is in our improvement queue. Team are working on this issue, and we will have a solution in the next release. 

We investigated and discussed your code changes, and decide not to merge your request. Your PR looks great, but it overlapped with part of features we are working on. You are very welcome to download our code and make some changes based on your own working scenario. 

Please let me know if you have any questions.

Thanks,
Xing

**Comment by MilesTails** [comment]
Hi,

So after testing this in v1.15 I can see there is still a problem with alphanumeric sorting. Longer strings are sorted to the top but the API returns shorter strings sorted first.

```
  ~ resource "fortios_firewallservice_group" "prometheus" {
      ~ dynamic_sort_subtable = "true" -> "alphabetical"
        id                    = "prometheus"
        name                  = "prometheus"
        # (3 unchanged attributes hidden)

      ~ member {
          ~ name = "tcp_2002" -> "tcp_10511"
        }
      ~ member {
          ~ name = "tcp_4002" -> "tcp_10512"
        }
      ~ member {
          ~ name = "tcp_5002" -> "tcp_10513"
        }
      ~ member {
          ~ name = "tcp_8080" -> "tcp_10515"
        }
      ~ member {
          ~ name = "tcp_8106" -> "tcp_10518"
        }
      ~ member {
          ~ name = "tcp_9100" -> "tcp_10599"
        }
      ~ member {
          ~ name = "tcp_9121" -> "tcp_20002"
        }
      ~ member {
          ~ name = "tcp_9168" -> "tcp_2002"
        }
      ~ member {
          ~ name = "tcp_9182" -> "tcp_4002"
        }
      ~ member {
          ~ name = "tcp_9183" -> "tcp_5002"
        }
      ~ member {
          ~ name = "tcp_9236" -> "tcp_8080"
        }
      ~ member {
          ~ name = "tcp_9252" -> "tcp_8106"
        }
      ~ member {
          ~ name = "tcp_9253" -> "tcp_9100"
        }
      ~ member {
          ~ name = "tcp_9256" -> "tcp_9121"
        }
      ~ member {
          ~ name = "tcp_10511" -> "tcp_9168"
        }
      ~ member {
          ~ name = "tcp_10512" -> "tcp_9182"
        }
      ~ member {
          ~ name = "tcp_10513" -> "tcp_9183"
        }
      ~ member {
          ~ name = "tcp_10515" -> "tcp_9236"
        }
      ~ member {
          ~ name = "tcp_10518" -> "tcp_9252"
        }
      ~ member {
          ~ name = "tcp_10599" -> "tcp_9253"
        }
      ~ member {
          ~ name = "tcp_20002" -> "tcp_9256"
        }
```

**Comment by lix-fortinet** [comment]
Hi @MilesTails,

Thank you for your update. Could you try `terraform apply`, then run `terraform plan` to see whether it works? `dynamic_sort_subtable` will be applied and sort the list once you run `terraform apply`.

Thanks,
Xing

**Comment by MilesTails** [comment]
Yep that has fixed it.
