### ISSUE TITLE
escapeFilter incorrect escaping

### ISSUE THREAD

**Issue by zippanto** [fortinetdev/terraform-provider-fortios#220]
We have been experiencing this issue when trying to use the fortios_systemdhcp_serverlist data source, filtering on an interface name with a dot in the name. Please see below.

data "fortios_systemdhcp_serverlist" "dhcp_serverlist" {
  filter   = "interface==TEST.123"
}

It returns no results. However the below does work correctly and returns the results as expected.

resource "fortios_json_generic_api" "response1" {
  path   = "/api/v2/cmdb/system.dhcp/server"
  method = "GET"
  specialparams = "filter=interface==TEST.123"
}

Having a look at the code it seems there's incorrect escaping in the escapeFilter function. Not sure if this applies to escaping other characters than dot.

**Comment by lix-fortinet** [comment]
Hi @zippanto,

Thank you for raising this issue. Team are working on this issue, and we will fix it in the next release. We will get back to you once it's resolved.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @zippanto,

The latest version of FortiOS Terraform provider v1.14.1 fixed this issue. Please switch to v1.14.1 and try it again.

Please let me know if you have any questions.

Thanks,
Xing
