### ISSUE TITLE
fortios provider does not use HTTP proxy

### ISSUE THREAD

**Issue by stephaneclavel** [fortinetdev/terraform-provider-fortios#229]
Hi

fortios provider does not use proxy set under HTTP_PROXY and HTTPS_PROXY environment variables as azurerm provider does for example. 

Below the connections going via cntlm when running terraform plan command. 
 
$ journalctl -u cntlm.service -f
avril 27 15:12:56 yd-vm-vfpt7242-202110181414 cntlm[1255]: 172.31.0.2 CONNECT login.microsoftonline.com:443
avril 27 15:12:57 yd-vm-vfpt7242-202110181414 cntlm[1255]: 172.31.0.2 CONNECT management.azure.com:443
avril 27 15:12:58 yd-vm-vfpt7242-202110181414 cntlm[1255]: 172.31.0.2 CONNECT xxxxxxxxxxx.blob.core.windows.net:443 (using Azure blob storage for terraform remote state)

Terraform plan command:
 
vscode ➜ /wspace/az-tf/fortigate (feature/fortigate_tf ✗) $ terraform plan -var-file=terraform.tfvars-udr-tf  -out plan.out
╷
│ Error: Error create fortios client: connection error: cannot send request, lost connection to firewall with error: Get "[https://20.234.38.66/api/v2/cmdb/system/global?access_token=***************":](https://20.234.38.66/api/v2/cmdb/system/global?access_token=***************%22:) context deadline exceeded (Client.Timeout exceeded while awaiting headers)
│
│   with provider["registry.terraform.io/fortinetdev/fortios"],
│   on providers.tf line 15, in provider "fortios":
│   15: provider "fortios" {
│
╵
Releasing state lock. This may take a few moments...
 
20.234.38.66 is fortigate public IP address. 
 
hostname = "20.234.38.66"
token = "mcssxxxxxxxxxxxxxx0m7fH"

terraform {
 required_providers {
 fortios = {
 source = "fortinetdev/fortios"
 }
 azurerm = {
 source = "hashicorp/azurerm"
 version = "=2.89.0"
 }
 }
 backend "azurerm" {
 }
}
 
provider "fortios" {
 hostname = var.hostname
 token = var.token
 insecure = "true"
}

vscode ➜ /wspace/az-tf/fortigate (feature/fortigate_tf ✗) $ echo $HTTP_PROXY
http://10.0.2.15:3128
vscode ➜ /wspace/az-tf/fortigate (feature/fortigate_tf ✗) $ echo $HTTPS_PROXY
http://10.0.2.15:3128

Could it be similar to https://github.com/hashicorp/terraform/issues/8735 ?

**Comment by lix-fortinet** [comment]
Hi @stephaneclavel,

Thank you for raising this issue. Team is working on this issue. We will get back to you once we have any update.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @stephaneclavel,

This issue has been fixed in the latest release of FortiOS Terraform provider v1.15.0. We added a new parameter `http_proxy` to provider configuration. You could specify it in provider configuration. Also, you could configure it in environment variables `HTTP_PROXY` or `HTTPS_PROXY`.  Please switch to the latest version of FortiOS Terraform provider and try it again.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @stephaneclavel,

We will close this issue since it has been fixed. Feel free to open a new issue if you have any other questions.

Thanks,
Xing
