### ISSUE TITLE
Cyclic dependency when deleting interfaces that are part of a zone resource

### ISSUE THREAD

**Issue by Isawan** [fortinetdev/terraform-provider-fortios#232]
Hi,

We've encountered an issue with the design of the fortios_system_zone resource when attempting to delete an interface in the interface list of the zone. Here's an example of a setup with the problem. Excuse the fake IP addresses as this is extracted from a larger set up. For context, we are using this internally to aggregate throughput of multiple IPSec tunnels.
```
resource "fortios_vpnipsec_phase1interface" "tunnel" {
  provider     = fortios
  name         = "tun${count.index}"
  interface    = "pub0"
  ike_version  = 2
  local_gw     = "192.168.0.{$count.index}"
  keylife      = 28800
  peertype     = "any"
  proposal     = "aes128-sha1"
  dhgrp        = "2"
  nattraversal = "disable"
  remote_gw    = 192.168.0.200
  psksecret    = "xxxxxx"
  count = 2
}

resource "fortios_vpnipsec_phase2interface" "tunnel" {
  provider       = fortios
  name           = fortios_vpnipsec_phase1interface.tunnel[count.index].name
  phase1name     = fortios_vpnipsec_phase1interface.tunnel[count.index].name
  proposal       = "aes128-sha1"
  dhgrp          = "2"
  auto_negotiate = "enable"
  src_addr_type  = "subnet"
  dst_addr_type  = "subnet"
  src_subnet     = 0.0.0.0/0
  dst_subnet     = 0.0.0.0/0
  keylifeseconds = 3600
  count = 2
}

resource "fortios_system_interface" "interface" {
  name        = fortios_vpnipsec_phase2interface.tunnel.name
  description = "moo"
  ip          = "10.0.0.${count.index} 255.255.255.255"
  remote_ip   = "10.0.0.1${count.index} 255.255.255.252"
  type        = "tunnel"
  autogenerated = "auto"
  allowaccess = "ping"
  status      = "up"
  interface   = "pub0"
  lifecycle {
    ignore_changes = [
      ipv6
    ]
  }
  count = 2
}

resource "fortios_system_zone" "zone" {
  name      = "internal_allow"
  intrazone = "allow"
  interface {
    interface_name = "sw0"
  }
  interface {
    interface_name = "sw1"
  }
  dynamic interface {
    for_each = fortios_system_interface.interface.name
    iterator = interface
    content {
        interface_name = interface.value.name
   }
  }
}
```

This type of setup creates the interface and associates the interface with the zone correctly. However when the number of IPSec tunnels needs to be reduced from 2 to 1; we are unable to delete the interfaces as terraform's plan performs deletions _before_ in-place update operations.

We are currently side-stepping this problem by explicitly creating multiple firewall rules to allow all combinations of interfaces to communication, although this is not ideal and we would prefer to use zones to reduce the number of rules.

The way that I would propose this be resolved is that another resource type is created to replace the interfaces attribute on the `fortios_system_zone`, potentially called `fortios_system_zone_member` which will look something like this.
```
resource "fortios_system_zone_member" "sw0" {
   zone = "internal_allow"
   interface = "sw0"
}
resource "fortios_system_zone_member" "sw1" {
   zone = "internal_allow"
   interface = "sw1"
}
resource "fortios_system_zone_member" "tunnel" {
   zone = "internal_allow"
   interface = "tun${count.index}"
   count = 2
}
```
This allows the membership of an interface to a zone to be de-coupled from the creation of the zone; thus resolving the dependency issue. I'm happy to work on and submit a patch to the issue if you are open to public contributions and are happy with the general approach.

Thanks.

**Comment by lix-fortinet** [comment]
Hi @Isawan,

Thank you for raising this issue. For create/delete resources that have references, set `create_before_destroy` to `true` in lifecycle will resolve it. It will put the `delete` operation after updated other resources. For your case, you could update resource `fortios_system_interface` like this:
```
resource "fortios_system_interface" "interface" {
  name        = fortios_vpnipsec_phase2interface.tunnel[count.index].name
  vdom         = "root"
  description = "moo"
  ip          = "10.0.0.${count.index} 255.255.255.255"
  remote_ip   = "10.0.0.1${count.index} 255.255.255.255"
  type        = "tunnel"
  autogenerated = "auto"
  allowaccess = "ping"
  status      = "up"
  interface   = "pub0"
  lifecycle {
    ignore_changes = [
      ipv6
    ]
    create_before_destroy = true
  }
  count = 2
}
```

Please let me know if you have any questions.

Thanks,
Xing

**Comment by pirum-isawan** [comment]
I ended up sticking the lifecycle policy on the fortios_system_zone resources and it seems to work. Thanks!

**Comment by lix-fortinet** [comment]
Hi @Isawan,

You are very welcome. I will close this issue. If you have other issues, feel free to reopen it or create another issue.

Thanks,
Xing
