### ISSUE TITLE
fortios_system_admin: attribute ssh-public-key* gets "tokenized"

### ISSUE THREAD

**Issue by mkolus** [fortinetdev/terraform-provider-fortios#234]
Hello,

 I'm trying to create an admin user with his SSH public key already configured, and I couldn't get it to work. This is what I got when running tf:

2022-05-19T18:05:18.493-0300 [ERROR] vertex "fortios_system_admin.tec_admin" error: Error creating SystemAdmin resource: Internal Server Error - Internal error when processing the request (500)
Cli response: 
**Invalid SSH public key.**
**node_check_object fail! for ssh-public-key1 ssh-rsa**
**Invalid SSH public key.**
**node_check_object fail! for ssh-public-key1** AAAAB3NzaC1yc2EAAAADAQABAAABAQDaqcBiM1MeB1YjiI1yd/syeNDrUl3U/o7kcTrkJecaJt4kln0cIqk9EHUM3lvp2e5dCfiRwJXJsMVbFLqksyElAImC4xVluZGE4N7MKqJcDclblP/VQKAS24vFB97Vw3iscB47exoJttx9cJiGRirEcw1hv9/H7rzcbZva1jtCw8F17sfsiJoCTctPKJegoQ9Tylqz0K1VKXg7ey8AOX0EvUqgL2Ux+bUsuXQ57x5GsYBFlq+ZfMKtaHm81AV+k2TpbjTsW6x3D/NB/D2FQCF4fDkaXeogHNLNcSwbuNTm3mYXMiXCz0h8H6j6h7JSkmpTOsVTGwSjz0JChIPJTdE9
**Invalid SSH public key.**
**node_check_object fail! for ssh-public-key1 mkolus@tux-solutions.com-2021**
**SSH key is invalid.**
**SSH key is invalid.**
**SSH key is invalid.**
entry not found in datasource

 Notice that there are three errors, one for each space-sparated _field_.

 What's interesting is that if I enclose the ssh key between quotes -in the file-, I can avoid the error.

## Version
```
Terraform v1.1.7
on windows_amd64
+ provider registry.terraform.io/fortinetdev/fortios v1.14.1
```

## tec.tf

```
resource "fortios_system_admin" "tec_admin" {
  accprofile = "tux"
  name       = var.fortigate_tec_username
  password   = var.fortigate_tec_password

  ssh_public_key1 = fileexists("${path.module}/tec_ssh_public_key.txt") ? file("${path.module}/tec_ssh_public_key.txt") : null

  vdom {
    name = "root"
  }
}
```

## tec_ssh_public_key.txt

```
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDaqcBiM1MeB1YjiI1yd/syeNDrUl3U/o7kcTrkJecaJt4kln0cIqk9EHUM3lvp2e5dCfiRwJXJsMVbFLqksyElAImC4xVluZGE4N7MKqJcDclblP/VQKAS24vFB97Vw3iscB47exoJttx9cJiGRirEcw1hv9/H7rzcbZva1jtCw8F17sfsiJoCTctPKJegoQ9Tylqz0K1VKXg7ey8AOX0EvUqgL2Ux+bUsuXQ57x5GsYBFlq+ZfMKtaHm81AV+k2TpbjTsW6x3D/NB/D2FQCF4fDkaXeogHNLNcSwbuNTm3mYXMiXCz0h8H6j6h7JSkmpTOsVTGwSjz0JChIPJTdE9 mkolus@tux-solutions.com-2021
```

**Comment by lix-fortinet** [comment]
Hi @mkolus,

Thank you for raising this issue. The reason for this issue is that without quotes, CLI will consider the ssh public key content as multiple strings. So, CLI will not get the whole content of the ssh public key, and return an error of 'SSH Key is invalid'. We will fix this issue in the next release, and also will get back to you once the new version been released.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @mkolus,

This issue has been fixed in the latest release of FortiOS Terraform provider v1.15.0. Please switch to the latest version of FortiOS Terraform provider and try it again.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @mkolus,

We will close this issue since it has been fixed. Feel free to open a new issue if you have any other questions.

Thanks,
Xing
