### ISSUE TITLE
FortiOS provider `cabundlefile` configuration

### ISSUE THREAD

**Issue by afmoreno1982** [fortinetdev/terraform-provider-fortios#238]
Request for fortios provider configuration `cabundlefile` argument to accept input as variable content.

Actual `cabundlefile` argument only accepts the path of the file certificate
```terraform
provider "fortios" {
  hostname     = var.fqdn
  token        = var.token
  insecure     = "false"
  cabundlefile = "/tmp/file.crt"
}
```

Propose to be change to accept certificate content

if `cabundlefile` certificate has to readed from a file:
```terraform
provider "fortios" {
  hostname     = var.fqdn
  token        = var.token
  insecure     = "false"
  cabundlefile = file("/tmp/file.crt")
}
```

if `cabundlefile` certificate is stored as string inside a variable:
```terraform
provider "fortios" {
  hostname     = var.fqdn
  token        = var.token
  insecure     = "false"
  cabundlefile = var.cabundlefile 
}
```

**Comment by lix-fortinet** [comment]
Hi @afmoreno1982,

Thank you for raising this request. We will consider it, and will get back to you once we have any update.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @afmoreno1982,

This issue has been fixed in the latest release of FortiOS Terraform provider v1.15.0. Please switch to the latest version of FortiOS Terraform provider and try it again. To keep the compatibility of the project, we added a new parameter `cabundlecontent` to the provider configuration. 

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @afmoreno1982,

We will close this issue since it has been fixed. Feel free to open new issues if you have other questions.

Thanks,
Xing
