### ISSUE TITLE
fortios_system_interface dhcp_relay_ip always updated

### ISSUE THREAD

**Issue by jacksonwg** [fortinetdev/terraform-provider-fortios#239]
The value of the `dhcp_relay_ip` attribute on fortios_system_interface is wrapped with quotation marks after being set. This causes the plan and apply to indicate a change even when there is no actual change.

```
# fortios_system_interface.vlan_int["90"] will be updated in-place
  ~ resource "fortios_system_interface" "vlan_int" {
      ~ dhcp_relay_ip                              = "\"10.0.0.3\" " -> "10.0.0.3"
        id                                         = "90"
        name                                       = "90"
        # (163 unchanged attributes hidden)
```

When viewed in the GUI and CLI, the value displayed is just `10.0.0.3` without any quotes.

**Comment by lix-fortinet** [comment]
Hi @jacksonwg,

Thank you for raising this issue. The reason for this issue is that the response from REST API contains extra quotation. We will work with the related team to find a solution for it. And we will get back to you once it's resolved.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @jacksonwg,

This issue has been fixed in the latest release of FortiOS Terraform provider v1.15.0. Please switch to the latest version of FortiOS Terraform provider and try it again.

Thanks,
Xing

**Comment by jacksonwg** [comment]
Thanks very much for letting me know.

I've tried out the new provider version and verified I am no longer seeing the behaviour I initially described.
