### ISSUE TITLE
fortios_systemdhcp_serverlist - Internal Server Error (500)

### ISSUE THREAD

**Issue by mathgonzlez** [fortinetdev/terraform-provider-fortios#242]
Hi,

I am trying to configure the DHCP service, but when I try to apply it, I receive the following error:

> _│ Error: Error creating SystemDhcpServer resource: Internal Server Error - Internal error when processing the request (500)
> │ 
> │   with fortios_systemdhcp_server.trname,
> │   on 01_interfaces.tf line 15, in resource "fortios_systemdhcp_server" "trname":
> │   15: resource "fortios_systemdhcp_server" "trname" {_

Attached details of the terraform file:

```
resource "fortios_system_interface" "port10" {
  name         = "port10"
  mode         = "static"
  ip           = "192.168.60.0 0.0.0.0"
  type         = "physical"
  vdom         = "root"
  alias = "port10"
  description  = "puto"
  lldp_reception = "disable"
  lldp_transmission = "disable"
  # member {
  #   interface_name = "port10 port9"
  # }
}
resource "fortios_systemdhcp_server" "trname" {
  dns_service = "default"
  fosid       = 8
  interface   = "port10"
  netmask     = "0.0.0.0"
  status      = "disable"
  ntp_server1 = "192.168.52.22"
  timezone    = "00"

  ip_range {
    end_ip   = "192.168.60.2"
    id       = 10
    start_ip = "192.168.60.200"
  }
}

```

Thanks.

**Comment by lix-fortinet** [comment]
Hi @mathgonzlez,

Thank you for raising this issue. There are two errors that I can see: `netmask` should not be `0.0.0.0`, and `start_ip` should be smaller than `end_ip` in `ip_range`. Please correct these two errors and try it again. 

For instance:
```
resource "fortios_systemdhcp_server" "trname" {
  dns_service = "default"
  fosid       = 8
  interface   = "port10"
  netmask     = "255.255.0.0"
  status      = "disable"
  ntp_server1 = "192.168.52.22"
  timezone    = "00"

  ip_range {
    end_ip   = "192.168.60.200"
    id       = 10
    start_ip = "192.168.60.2"
  }
}
```

Thanks,
Xing

**Comment by mathgonzlez** [comment]
thank you very much for the help, the error was the ip range
