### ISSUE TITLE
Firewall Policy - PolicyID keeps forcing replacement

### ISSUE THREAD

**Issue by aarjbdea** [fortinetdev/terraform-provider-fortios#243]
When configuring a new firewall policy with policyid not set it will attempt to set the policyid to null on each terraform apply run and then will force a replacement of the firewall policy. From previous issues this shouldnt happen (https://github.com/fortinetdev/terraform-provider-fortios/issues/160) as the policyid is stored within the terraform state file. Any ideas?

This is one of the lines that appears in the terraform plan

- policyid                       = 11 -> null # forces replacement

**Comment by gmintoco** [comment]
We are having this issue too - every apply job all policies get recreated

**Comment by aarjbdea** [comment]
Ive done some testing today and it would appear that v1.15.0 has broken this - v1.14.1 is working correctly and is not recreating the firewall policies

**Comment by pedrojgsbraga** [comment]
Hi, @aarjbdea @gmintoco  
Apply this config on the firewall policy resource:

```
lifecycle {
    ignore_changes = [policyid]
  }
```

It work for me.

**Comment by lix-fortinet** [comment]
Hi @aarjbdea,

Thank you for raising this issue. Team are working on this issue. We will fix it in the next release.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @aarjbdea,

This issue has been fixed in the latest release of FortiOS Terraform provider v1.16.0. Please switch to the latest version of FortiOS Terraform provider and try it again.

Please let me know if you have any questions.

Thanks,
Xing
