### ISSUE TITLE
FortiManagerCloud usage

### ISSUE THREAD

**Issue by sebbbastien** [fortinetdev/terraform-provider-fortios#249]
Hi,

Is this provider able to work with the FortiManagerCloud?

Regards,

**Comment by lix-fortinet** [comment]
Hi @sebbbastien,

Thank you for raising this issue. This provider is for FortiOS. Once you have the API token of your FortiOS device, you can use this provider. As for FortiManager, please use the FortiManager Terraform provider. Here are the related links:
    Terraform registry: https://registry.terraform.io/providers/fortinetdev/fortimanager/latest;
    Github: https://github.com/fortinetdev/terraform-provider-fortimanager.

Please let me know if you have any questions.

Thanks,
Xing

**Comment by lix-fortinet** [comment]
Hi @sebbbastien,

I will close this issue since it's not a FortiOS issue. Fell free to open a new issue if you have any questions.

Thanks,
Xing
