### ISSUE TITLE
fortios_system_vdomlink errors when attempting to create

### ISSUE THREAD

**Issue by aarjbdea** [fortinetdev/terraform-provider-fortios#251]
When trying to create a VDOM-Link it always errors and the documentation doesn't have any further attributes I can test
`resource "fortios_system_vdomlink" "Test" {
  name = "Test"
  vcluster = "vcluster1"
  type = "PPP"
  vdomparam = "AUT-VDOM"
}`

**Error** - Error creating SystemVdomLink resource: Internal Server Error - Internal error when processing the request (500)
with fortios_system_vdomlink.Test,
│   on main.tf line 1, in resource "fortios_system_vdomlink" "Test":
│    1: resource "fortios_system_vdomlink" "Test" {

Is anyone else seeing this?

**Comment by MaxxLiu22** [comment]
Hi @aarjbdea 

Thank you for raising this issue. I can't reproduce this error by using the configuration like below, but you can try to set a different name that sometimes may conflict with existing items. We would appreciate it if you could provide the environment for your test case, like the FortiOS version, FortiOS Terraform provider version, Terraform version, etc. That would be very helpful for us to reproduce this issue.
```
resource "fortios_system_vdomlink" "Test" {
  name     = "Test"
  vcluster = "vcluster1"
  type     = "ppp"
  vdomparam = "AUT-VDOM"
}
```

Thanks,
Maxx

**Comment by aarjbdea** [comment]
Hi Maxx, 

We are running the latest version of the terraform provider (also tested on 1.14.1) & Terraform version is also the latest
FortiOS - 6.4.8

Regards

**Comment by MaxxLiu22** [comment]
Hi @aarjbdea ,

Sorry for the late reply, yes that is expected, now you can import these two interfaces into Terraform, and then edit them to connect any two vdoms. The following example just creates a link between vdom "root" and vdom "AUT-VDOM", feel free to use it and let me know if you still have issues.
```
resource "fortios_system_vdomlink" "Test" {
  name     = "Test"
  vcluster = "vcluster1"
  type     = "ppp"
}

run cmd: terraform import fortios_system_interface.trname Test0
run cmd: terraform import fortios_system_interface.trname1 Test1

resource "fortios_system_interface" "trname" {
  name        = "Test0"
  vdom        = "root"
  ip          = "1.1.1.1/24"
  allowaccess = "ping"
}

resource "fortios_system_interface" "trname1" {
  name        = "Test1"
  vdom        = "AUT-VDOM"
  ip          = "1.1.1.2/24"
  allowaccess = "ping"
}
```

Thanks,
Maxx
