### ISSUE TITLE
fortios_system_interface type=tunnel unnecessarily asks for vlanid

### ISSUE THREAD

**Issue by PatchMickle** [fortinetdev/terraform-provider-fortios#252]
I'm building a tunnel interface between my firewall and AWS. terraform plan passes, terraform apply asks for vlanid, whether the vlanid field is present or not.

resource "fortios_system_interface" "L2L-AWS-W1P3" {
  name                           = "L2L-AWS-W1P3"
  vdom                           = "root"
  ip                                 = "169.254.16.5 255.255.255.255"
  allowaccess                = "ping speed-test"
  device_identification = "enable"
  interface                     = "wan1"
  role                              = "Undefined"
  vlanid                          = 50
  type                            = "tunnel"
  vlan_protocol            = "dot1q"
}

Output:
╷
│ Error: Error creating SystemInterface resource: Internal Server Error - Internal error when processing the request (500)
│ Cli response: 
│ Please input vlanid.
│ object set operator error, -158 discard the setting
│ Command fail. Return code -158
│ 
│ 
│   with module.policies.module.subnets.fortios_system_interface.L2L-AWS-W1P3,
│   on ../../modules/warehouses/subnets/subnets.tf line 114, in resource "fortios_system_interface" "L2L-AWS-W1P3":
│  114: resource "fortios_system_interface" "L2L-AWS-W1P3" {
│ 

Fortios 7.0.0 on firewall
Fortios 1.14.0 provider
Terraform >=0.14

**Comment by MaxxLiu22** [comment]
Hi @PatchMickle ,

Thank you for raising this issue. For creating various tunnels, Terraform has different resources to create interface, such as fortios_system_ipiptunnel for creating IP-IP tunnel interface, fortios_system_gretunnel for creating GRE tunnel interface, fortios_system_sittunnel for creating IP-Sit tunnel interface, etc. Hope that is helpful for you, if you still have issues, feel free to let me know.

Thanks,
Maxx

**Comment by PatchMickle** [comment]
Thanks Maxx,

I should have been more specific. I'm trying to build the internal IP portion of the IPSec tunnel interface. The piece that holds the second IP in AWS' generated 169.254.x.x/30 network. Building the external portion that connects the two gateways has been solved.

Any help would be appreciated.

Just in case, here's something of a pathetic diagram of what I'm trying to do:

TUNNEL 1:-------------------------------------------------------------------------
Local-Gateway: 3.3.3.3==================Remote-Gateway: 4.4.4.4                                          
Local-IP: 169.254.2.2 255.255.255=========Remote-IP: 169.254.2.1 255.255.252
------------------------------------------------------------------------------------
It's the internal IPs I can't seem to figure out.

**Comment by MaxxLiu22** [comment]
Hi @PatchMickle ,

Thank you for your information, I get your problem. After you set up the fortios_vpnipsec_phase1interface and fortios_vpnipsec_phase2interface, FortiOS would automatically generate an IPsec tunnel interface with the same name as phase1 interface name, then you need to import this existing interface into Terraform by using cmd`` terraform import fortios_system_interface.labelname {{name}}`` and then to edit the IP or other arguments. Here is an example, you are free to use it, please let me know if you still have issues.
```
#step 1: create phase1interface & vpnipsec_phase2interface
resource "fortios_vpnipsec_phase1interface" "vpn" {
  name              = "ipsec_tunnel"
  local_gw          = "3.3.3.3"
  remote_gw         = "4.4.4.4"
  interface         = "port3"
  proposal          = "aes128-sha1"
  psksecret         = "eTGJ8Ly5OYp2zpAQF8FytnD5NPFiFgPf"
}

resource "fortios_vpnipsec_phase2interface" "test" {
  name           = "ipsec_interface2"
  phase1name     = "ipsec_tunnel"
  proposal       = "aes128-sha1"
  depends_on     = [fortios_vpnipsec_phase1interface.vpn] 
} 

#step 2: add an interface resource into terraform file
resource "fortios_system_interface" "vpn" {
  name        = "ipsec_tunnel"
  ip          = "169.254.2.2/32" 
  remote_ip   = "169.254.2.1 255.255.255.0"
  vdom        = "root"
  allowaccess = "ping"
}
#step 3: import ipsec tunnel interface into terraform, and then you are free to edit this interface
// at terminal run : terraform import fortios_system_interface.vpn ipsec_tunnel
```

Thanks,
Maxx

**Comment by PatchMickle** [comment]
@MaxxLiu22 you're a friggin genius. That worked. Thank you!!

**Comment by dbhagen** [comment]
This does seem a little counterintuitive to have deploy the first half of the config, deploy it, then build the second half while importing it to start.

**Comment by MaxxLiu22** [comment]
Hi all, I will go ahead to close this case, you are welcome to reopen it or another case.
