### ISSUE TITLE
Use of proxy evn't variables causing connectivity issues

### ISSUE THREAD

**Issue by leonardoauribe** [fortinetdev/terraform-provider-fortios#253]
I use hosts in an isolated environment to configure Fortigate firewalls via Terraform. I've upgraded to the latest provider v1.16.0 and noticed a change in behavior compared to the previous version I was running, 1.14.1. The latest version of fortios provider leverages proxy environment variables for forwarding traffic. It appears to have been introduced in v1.15. This configuration is fine for access to AWS services like S3, but traffic destined to the Fortigates themselves we want direct access. This traffic shouldn't require a proxy and is being denied at the proxy as designed. I would like to request the following; 

*  addition of no_proxy to provider
*  enable proxy config per provider 
* provider proxy config takes precedence over environment variables

We have rollback to v1.14.1 for the time being until we figure out a better solution.

Similar issues found: 
https://github.com/fortinetdev/terraform-provider-fortios/issues/229
https://github.com/hashicorp/terraform/issues/17386

```
Terraform v1.3.4
on darwin_amd64
+ provider registry.terraform.io/fortinetdev/fortios v1.14.1

FortiOS version: v6.4.9
```

Error
```
Error: Error create fortios client: connection error: cannot send request, lost connection to firewall with error: Get "https://fw3-lab.ops.lab.net:1234/api/v2/cmdb/system/global?access_token=********": proxyconnect tcp: dial tcp :0: connect: connection refused
```

**Comment by lix-fortinet** [comment]
Hi @leonardoauribe,

Thank you for raising this issue. Team is working on this issue. We will fix it in the next release. 

Thanks,
Xing

**Comment by leonardoauribe** [comment]
Has there been any progress made with this issue?

**Comment by lix-fortinet** [comment]
Hi @leonardoauribe,

We will have a new release in early Feb which will fix this issue.

Thanks,
Xing

**Comment by leonardoauribe** [comment]
Has there been a date identified for the new release? We are still running into issues. thanks!

**Comment by MaxxLiu22** [comment]
Hi @leonardoauribe, Terraform FOS provider version 1.17.0 has released, please check it out. If the issue still occurs, please let me know.
