### ISSUE TITLE
Reordering of members for fortios_firewallservice_group and fortios_firewall_addrgrp

### ISSUE THREAD

**Issue by mathieubrun** [fortinetdev/terraform-provider-fortios#256]
I defined the following resource :

``` terraform
resource "fortios_firewallservice_group" "test" {
  name = "test"

  member {
    name = "HTTP"
  }
  member {
    name = "SMB"
  }
  member {
    name = "HTTPS"
  }
}
```

Running `terraform apply` always results in the following:

``` terraform
fortios_firewallservice_group.test will be updated in-place

  ~ resource "fortios_firewallservice_group" "test" {
        id                    = "test"
        name                  = "test"
    # (4 unchanged attributes hidden)

  ~ member {
      ~ name = "HTTPS" -> "SMB"
    }
  ~ member {
      ~ name = "SMB" -> "HTTPS"
    }

    # (1 unchanged block hidden)
}
``` 

Expected behaviour : no changes should be performed, as the members have not changed.
As a workaround, I can declare the resource as:

``` terraform
resource "fortios_firewallservice_group" "test" {
  name = "test"

  member {
    name = "HTTP"
  }
  member {
    name = "HTTPS"
  }
  member {
    name = "SMB"
  }
}
```

The same behaviour occurs for `fortios_firewall_addrgrp`

**Comment by lix-fortinet** [comment]
Hi @mathieubrun,

Thank you for raising this issue. You could set `dynamic_sort_subtable` to 'true' to sort the sub-tables. Then run `terraform apply` to activate it. Here is the reference :https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewallservice_group#dynamic_sort_subtable. 
For instance:
```
resource "fortios_firewallservice_group" "test" {
  name = "test"

  member {
    name = "HTTP"
  }
  member {
    name = "HTTPS"
  }
  member {
    name = "SMB"
  }

  dynamic_sort_subtable = true
}
```
By default, `dynamic_sort_subtable` is set to 'false' which means do nothing for the sequence of table elements. But sometimes the order may change when we get the value from FortiOS. 

Thanks,
Xing

**Comment by mathieubrun** [comment]
Thanks, I did overlook the documentation on this one !
