### ISSUE TITLE
conditional_advertise - condition_routemap should be list and not string

### ISSUE THREAD

**Issue by kotchinet** [fortinetdev/terraform-provider-fortios#258]
In both resources `fortios_router_bgp` and `fortios_routerbgp_neighbor` the value for `condition_routemap` is defined as a string, but in the API documentation for fortigate it should be a list of strings. Since multiple route-maps can be assigned as a match condition.

**Provider Code**
```
"conditional_advertise": &schema.Schema{
  Type:     schema.TypeList,
  Computed: true,
  Elem: &schema.Resource{
	  Schema: map[string]*schema.Schema{
		  "advertise_routemap": &schema.Schema{
			  Type:     schema.TypeString,
			  Computed: true,
		  },
		  "condition_routemap": &schema.Schema{
			  Type:     schema.TypeString,
			  Computed: true,
		  },
		  "condition_type": &schema.Schema{
			  Type:     schema.TypeString,
			  Computed: true,
		  },
	  },
  },
},
```

**API Documentation**
```
conditional-advertise   [
maxItems: null
Conditional advertisement.
{
advertise-routemap  string
maxLength: 35
Name of advertising route map.
condition-routemap  [
maxItems: null
List of conditional route maps.
{
name    string
maxLength: 79
route map
}]
condition-type  string
Type of condition.
exist:True if condition route map is matched.
non-exist:True if condition route map is not matched.
Enum:
[ exist, non-exist ]
```

If i try setting a single route-map as a string and applying it with Terraform it creates the `conditional_advertise` block but skips the `advertise_routemap` attribute.
While running `diagnose debug application httpsd -1` i cant see any reference to `conditional_advertise` so it seems to not be passed correctly.

Please let me know if i need to provide some more information.

**Comment by MaxxLiu22** [comment]
Hi @kotchinet ，

Thank you for raising this issue, I can reproduce this issue on my side and have reported it to the development team. I will let you know if there is any update. 

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @kotchinet ， Terraform FOS provider version 1.17.0 has released, please check it out. If the issue still occurs, please let me know.
