### ISSUE TITLE
fortios_system_global  vdom_mode

### ISSUE THREAD

**Issue by sergey-ostrovskiy** [fortinetdev/terraform-provider-fortios#260]
Unable to activate multi-vdom on fortigate 100F software version 7.0.9
provider fortios
providers version 1.16.0
Terraform version  1.3.7
We do it in two ways:

1. 
resource "fortios_system_global" "default_global" {
     hostname="test1"
     vdom_admin="enable"
}

variable vdom_mode {
   type = string
   default = "multi-vdom" #"no-vdom", "split-vdom", "multi-vdom"
}

resource "fortios_json_generic_api" "test2" {
    path = "/api/v2/cmdb/system/global"
    method = "PUT"
    json = <<EOF
{
     "vdom-mode": "${var.vdom_mode}"
}
EOF
}

In this case, only the hostname changes.

2. resource "fortios_system_global" "default_global" {
     hostname="test1"
     vdom_admin="enable"
     vdom_mode = "multi vdom"
}
in this example, we get the error "Error updating SystemGlobal resource: Internal Server Error - Internal error when processing the request (500)"

Please tell me how to solve this problem

**Comment by MaxxLiu22** [comment]
Hi @sergey-ostrovskiy ,

Thank you for raising this issue, your code looks good to me, "vdom_mode" would be set to  "multi-vdom" to enable vdom mode. I am wondering do you see any CLI returned error msg under "Error updating SystemGlobal resource: Internal Server Error - Internal error when processing the request (500)"? and could you help me try to enable multi-vdom mode through GUI System -> Settings -> Virtual Domains -> Multi VDOM to see if there is any error? Sorry for any inconvenience, and looking for your response.

Thanks,
Maxx

**Comment by sergey-ostrovskiy** [comment]
Hi MaxxLiu22

Correctly I understood you, do you mean multi-vdom is enabled via CLI? If yes, then it turns on without errors.
Through GUI multi-vdom turns on without errors.

**Comment by MaxxLiu22** [comment]
Hi @sergey-ostrovskiy ,

I tried with varies version FGT, and not be able to reproduce this issue, could you help me to enable debugging in your CLI with[ debug](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/guides/fgt_debug), and run your script again to see what can be caught please.
```
$ diagnose debug enable
$ diagnose debug application httpsd -1
$ diagnose debug cli 8
```

Thanks,
Maxx

**Comment by minikenshin** [comment]
I find the issue (not me directly, thanks to the fortinet discord).
You need to put super_admin profile on your api user (in cli only).

```
config system api-user
edit "YOURUSERAPINAME"
set accprofile super_admin
next
```
