### ISSUE TITLE
Fortimanager module

### ISSUE THREAD

**Issue by apellini** [fortinetdev/terraform-provider-fortios#264]
We see that in documentation is missing of following resource module:

ADOM Lock State
Central SNAT
Central DNAT

It is normal or only a lack of documentation?

Also seems missing some data modules.

Regards,

Aldo Pellini

**Comment by MaxxLiu22** [comment]
Hi @apellini ,

Thank you for raising this issue, FMG terraform doesn't cover all resources now, we will add them in the future.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi I have moved this issue under FMG repo.

**Comment by lix-fortinet** [comment]
Hi @apellini,

FortiManager Terraform provider is a separate provider, and Liang has moved this issue to the target Github repository: https://github.com/fortinetdev/terraform-provider-fortimanager/issues/33. We will close this issue.

Thanks,
Xing
