### ISSUE TITLE
fortios_router_policy: Unable to specify multiple src/srcaddr dst/dstaddr internet_service_id

### ISSUE THREAD

**Issue by roofburner** [fortinetdev/terraform-provider-fortios#266]
Hi all,

I'm trying to configure a policy route using fortios_router_policy.

The GUI allows you to configure multiple "Incoming interfaces", "Source Addresses", "Destination Addresses"/"Internet services", but I'm unable to do so via the Terraform FortiOS provider.

I read there is block support, but no example explains how to specify multiple src, srcaddr, ...

Who can help me please?

Kind regards,

Stijn

**Comment by MaxxLiu22** [comment]
Hi @roofburner ,

Thank you for your question, here is an example for your reference. For checking internet_service_id, you can find them via GUI policy&objects -> internet service database or a more convenient way in CLI. Let me know if you still have questions.

```
FGVMULTM22003786 # config router policy 

FGVMULTM22003786 (policy) # edit 1
new entry '1' added

FGVMULTM22003786 (1) # set internet-service-id (input ?)
ID           Select available ID.
65537        Google-Web 
65538        Google-ICMP 
65539        Google-DNS 
65540        Google-Outbound_Email 
65542        Google-SSH 
65543        Google-FTP 
65544        Google-NTP 
65545        Google-Inbound_Email 
65550        Google-LDAP 
65551        Google-NetBIOS.Session.Service 
65552        Google-RTMP 
65560        Google-NetBIOS.Name.Service 
65536        Google-Other 
65641        Google-Google.Cloud 
65646        Google-Gmail 
131073       Meta-Web 
131074       Meta-ICMP 
131075       Meta-DNS 
131076       Meta-Outbound_Email 
--More-- 
``` 
```
resource "fortios_router_policy" "trname" {
  action  = "permit"
  gateway = "1.1.1.1"
  src {
    subnet = "1.2.3.0/255.255.255.0"
  }
  src {
    subnet = "5.6.0.0/255.255.0.0"
  }
  dstaddr {
    name = "FABRIC_DEVICE"
  }
  dstaddr {
    name = "gmail.com"
  }
  input_device {
    name = "port1"
  }
  internet_service_id{
    id = "65537"
  }
  internet_service_id{
    id = "65542"
  }
}
```

Thanks,
Maxx

**Comment by roofburner** [comment]
Hi Maxx,

Verry clear to me now. I can confirm it works.

Thanks!

Kind regards,

Stijn
