### ISSUE TITLE
Issue using SystemLinkMonitor resource

### ISSUE THREAD

**Issue by roofburner** [fortinetdev/terraform-provider-fortios#269]
Hi all,

Hope you're all doing well?!

I have two equal cost static routes to 0.0.0.0/0 over two IPSEC tunnels. The two tunnels can't be up (by design) at the same time.

```
config router static
    edit 1
        set device "UZG-P1"
    next
    edit 2
        set device "UZG-P1backup"
    next
end
```

I want the route to disappear when "their" tunnel is down.

Therefore I started to use link monitor, but trying to translate the Fortigate config into Terraform code I get this error:

```
Gateway is not unique for the same interface
```

It is correct, the gateway is the same, but the interface differs:

```
config system link-monitor
    edit "UZG-P1mon"
        set srcintf "UZG-P1"
        set server "192.168.83.254" "1.1.1.1" "8.8.8.8"
        set source-ip 10.255.0.38
        set interval 5000
    next
    edit "UZG-P1backupmon"
        set srcintf "UZG-P1backup"
        set server "192.168.83.254" "1.1.1.1" "8.8.8.8"
        set source-ip 10.255.0.38
        set interval 5000
    next
end
```

It looks like this config is allowed by FortiOS 7.2.4, but not via the provider v1.16.0

Please advise,

Stijn

**Comment by MaxxLiu22** [comment]
Hi @roofburner ，

Thank you for raising this issue, may I get the full error message? which module generates this error?

Thanks,
Maxx
