### ISSUE TITLE
Failed to query available provider packages

### ISSUE THREAD

**Issue by tkoeck** [fortinetdev/terraform-provider-fortios#270]
I'll get a strange error message. Isn't it in the official repository?

Terraform v1.4.5
on linux_amd64

```
provider "fortios" {
  hostname = "fg.someurl.de"
  token    = var.api-token
  vdom     = "root"
  insecure = true
}
```

```
tkoeck@tron-nb:~/gitlab/router-berlin$ terraform init

Initializing the backend...

Initializing provider plugins...
- Finding latest version of hashicorp/fortios...
╷
│ Error: Failed to query available provider packages
│ 
│ Could not retrieve the list of available versions for provider hashicorp/fortios:
│ provider registry registry.terraform.io does not have a provider named
│ registry.terraform.io/hashicorp/fortios
│ 
│ Did you intend to use fortinetdev/fortios? If so, you must specify that source
│ address in each module which requires that provider. To see which modules are
│ currently depending on hashicorp/fortios, run the following command:
│     terraform providers
```

**Comment by MaxxLiu22** [comment]
Hi @tkoeck,

Thank you for raising this question, before we use fortios provider, we need to import the provider first.
```
terraform {
  required_providers {
    fortios = {
      source  = "fortinetdev/fortios"
      version = "1.16.0"
    }
  }
}

provider "fortios" {
  hostname = "fg.someurl.de"
  token    = var.api-token
  vdom     = "root"
  insecure = true
}
```
then ``terraform init``. let me know if that doesn't work.
Thanks,
Maxx

**Comment by tkoeck** [comment]
Thanks, I will try it out.

You should probably update your official documentation so it will reflect that changes.

**Comment by tkoeck** [comment]
Nice. That seems to work.

IMHO you should update your official documentation at

https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs

to reflect this.

**Comment by MaxxLiu22** [comment]
Hi @tkoeck ,

Thank you for your suggestion, we are continuing improve our documentation. I will go ahead to close this case, feel free to reopen it if you still have this problem.

Thanks,
Maxx
