### ISSUE TITLE
can not set multiple destination interfaces in fortios_firewall_policy

### ISSUE THREAD

**Issue by danadeweerdx** [fortinetdev/terraform-provider-fortios#271]
terraform version = "1.4.0"
provider name = "fortinetdev/fortios"
provider version = "1.16.0"

I would like to set mulitple destination interfaces for this policy and i have tried different ways. Including:

```
resource "fortios_firewall_policy" "example" {
  name = "example"
  dstintf { name = ["Algemeen", "PO"] } 
  dstintf { name = "Algemeen, PO" } 
```

But it seems that only one string is required. Is there a way i can still accomplish this?

**Comment by MaxxLiu22** [comment]
Hi @danadeweerdx ,

Thank you for your question, you can set multiple dstintf blocks to set more interfaces, other block arguments can also use this method.
```
resource "fortios_firewall_policy" "test-policy" {
  name            = "test-policy"
  dstintf {
    name = "port1"
  }
  dstintf {
    name = "port2"
  }
  srcintf {
    name = "any"
  }
  srcaddr {
    name = "all"
  }
  dstaddr {
    name = "all"
  }
  service {
    name = "ALL"
  }
}
```
Thanks,
Maxx

**Comment by danadeweerdx** [comment]
Thank you so much!
