### ISSUE TITLE
Missing documentation and argument problems

### ISSUE THREAD

**Issue by tkoeck** [fortinetdev/terraform-provider-fortios#275]
Hi,

I just tried to set up an internal1 interface on the internal hardware switch. Won't work.

There also aren't any examples or further explanations in the documentation

E.g. for the argument 'type'

https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_system_interface#type

it just says ' Interface type'.

In the example above is only the argument 'physical' which won't work in that case. There are no other options shown. Also in the go code I didn't find anything.

I think you should improve your documentation so that at least it is possible to create or change an internal interface without having to try out a lot or 'guess' what parameters you need.

Additionally, it's not explained to what the argument 'name' do fit? To the internal interface name?

And as a remark, your argument 'secondary_ipaddress' is fine, but you can create more than one other. You should name it additional_ipaddress or something like that. Also in the GUI.

Greetings
Tobias

**Comment by tkoeck** [comment]
E.g. if I try to set the values of the hardware-switch with that IP

`resource fortios_system_interface "internal" {
  name                           = "internal"
  type                           = "hard-switch"
  vdom                           = "root"
  mode                           = "static"
  allowaccess                    = "ping https http"
  role                           = "lan"
  ip                             = " 192.168.68.1/24"
  secondary_ip = "enable"
  autogenerated = "true"
  member {
    interface_name = "internal1 internal internal3 internal4 internal5 internal6"
    #interface_name = "internal1"
  }
  secondaryip {
    ip = "192.168.69.1/24"
    allowaccess = "ping fgfm http https"
  }
  secondaryip {
    ip = "192.168.1.99/24"
    allowaccess = "ping fgfm http https"
  }
}`

I'll get

f

> ortios_system_interface.internal: Creating...
> 2023-05-11T13:38:20.818+0200 [ERROR] provider.terraform-provider-fortios_v1.16.0: Response contains error diagnostic: tf_req_id=2f011b06-512e-8e34-596f-4a511cfe673c tf_resource_type=fortios_system_interface tf_rpc=ApplyResourceChange @caller=github.com/hashicorp/terraform-plugin-go@v0.14.0/tfprotov5/internal/diag/diagnostics.go:55 diagnostic_severity=ERROR diagnostic_summary="Error creating SystemInterface resource: Internal Server Error - Internal error when processing the request (500)" @module=sdk.proto diagnostic_detail= tf_proto_version=5.3 tf_provider_addr=provider timestamp=2023-05-11T13:38:20.818+0200
> fortios_system_interface.wan1: Modifying... [id=wan1]
> 2023-05-11T13:38:20.860+0200 [ERROR] vertex "fortios_system_interface.internal" error: Error creating SystemInterface resource: Internal Server Error - Internal error when processing the request (500)
> fortios_system_interface.wan1: Modifications complete after 0s [id=wan1]
> ╷
> │ Error: Error creating SystemInterface resource: Internal Server Error - Internal error when processing the request (500)
> │ 
> │   with fortios_system_interface.internal,
> │   on interfaces.tf line 13, in resource "fortios_system_interface" "internal":
> │   13: resource fortios_system_interface "internal" {
> │ 
> 
>

**Comment by MaxxLiu22** [comment]
Hi @tkoeck ,

Thank you for your suggestions, our Terraform doc is not that detailed now, we will improve this part in the future, sorry for any inconvenience. The ``Internal error when processing the request (500) `` error msg is from CLI side, I will inform the corresponding team to improve this part, which usually mean inappropriate config, I only see an extra space before primary ``ip``, could you try to achieve this operation through CLI to see what is happening?

Thanks,
Maxx

**Comment by tkoeck** [comment]
Hi Maxx,

thanks for the detailed answer. Now it works. I don't know if it really was the extra space, but that could make problems. IMHO either the terraform provider should be more error tolerant for extra spaces or at least give a hint that this might be the issue. :)

For the arguments like 'type = "hard-switch"' I had to search for somewhere else some examples to be able to configure it.

For the documentation, I suggest writing down the possible options like 'physical' and 'hard-switch' so that one does not have to play Sherlock Holmes to find out how to do that.

I would also propose giving more examples of how to create some standard resources so that we as customers don't have to try so much until it works.

In our company, we bought several Fortigate devices instead of other brands, specifically because they have the advantage of supporting Infrastructure as Code. So, the Terraform provider should support (almost) all configuration options that the GUI supports, too. ;)

**Comment by MaxxLiu22** [comment]
Hi @tkoeck ,

We are continuing improve our documentation, thank you for your suggestion, I will go ahead to close this case, if you still have questions, feel free to ask anytime.

Thanks,
Maxx
