### ISSUE TITLE
Feature visibility

### ISSUE THREAD

**Issue by tkoeck** [fortinetdev/terraform-provider-fortios#278]
Hi,

the 'feature visibility' cannot be configured with the Terraform provider. At least I didn't find the option.

**Comment by MaxxLiu22** [comment]
Hi @tkoeck ,

Thank you for your question, feature visibility function can be edit in [system global resource](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_system_global#gui_ipv6), you can set enable to the argument begin with "gui_" to enable this feature showed on GUI.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @tkoeck 

I will go ahead to close this case, if you still have questions, you are welcome to reopen it or another case.

Thanks,
Maxx
