### ISSUE TITLE
service deletion doesn't work correctly

### ISSUE THREAD

**Issue by minikenshin** [fortinetdev/terraform-provider-fortios#279]
Hello team,

We found a little bug in the firewallservice_custom (v1.16.0).

Create a service with a tcp_portrange and a udp_portrange :

```
resource "fortios_firewallservice_custom" "port_22" {
  name                = "port_22"
  protocol            = "TCP/UDP/SCTP"
  tcp_portrange       = "22"
  udp_portrange       = "22"
}
```

It create an service with TCP/22 et UDP/22 as you ask.

Suppress the UDP/22 like this config : 
```
resource "fortios_firewallservice_custom" "port_22" {
  name                = "port_22"
  protocol            = "TCP/UDP/SCTP"
  tcp_portrange       = "22"
}
```
or this 
```
resource "fortios_firewallservice_custom" "port_22" {
  name                = "port_22"
  protocol            = "TCP/UDP/SCTP"
  tcp_portrange       = "22"
  udp_portrange       = ""
}
```
and a terraform plan tell you there is no change in your configuration.

Could you check how to correct this please ? 
Thanks

**Comment by MaxxLiu22** [comment]
Hi @minikenshin ,

Thank you for your question, could you type a space between the quotation marks like ``" "`` and try again, by this way Terraform would remove the existing value, let me know if that doesn't work.

Thanks,
Maxx

**Comment by minikenshin** [comment]
Hello @MaxxLiu22 ,

it works , tanks !
Is it a « normal » behavior ? Or a workaround ?

Regards

**Comment by MaxxLiu22** [comment]
Hi @minikenshin ,

That is expected, if that doesn't satisfy your need, please let me know. I will go ahead to close this, feel free to reopen it if you still have questions.
