### ISSUE TITLE
Unable to use VRF id range 64 - 251 for FortiOS 7.2.4+

### ISSUE THREAD

**Issue by Vokunne** [fortinetdev/terraform-provider-fortios#284]
Preface:

- Fortigate 200F (FortiOS v7.2.5)
- Terraform provider version 1.16.0

Resource description:

resource "fortios_router_static" "DEFAULT_MGMT_INTF" {
  seq_num = 2
  status = "enable"
  dst = "0.0.0.0/0"
  gateway = "10.10.10.1"
  vrf = 100              # Install default route into MGMT vrf 100 
}

Got error:
terraform plan

Error: expected vrf to be in the range (0 - 63), got 100

with module.static.fortios_router_static.DEFAULT_MGMT_INTF,
on modules/static/main.tf line 23, in resource "fortios_router_static" "DEFAULT_MGMT_INTF":
23:   vrf = 100              # Install default route into MGMT vrf

Meanwhile, in accordance with a tech documentation the VRF ID range has changed to 0 - 63, but this is applicable only for devices that are running FortiOS 7.2.1+. Starting from FortiOS v7.2.4, the number of VRFs per VDOMs has been increased to 251.

https://community.fortinet.com/t5/FortiGate/Technical-Tip-Virtual-routing-and-forwarding-ID-configuration/ta-p/195073

**Comment by alagoutte** [comment]
Need to change this line...

https://github.com/fortinetdev/terraform-provider-fortios/blob/master/fortios/resource_router_static.go#L150

**Comment by MaxxLiu22** [comment]
Hi @Vokunne ,

Thank you for raising this issue, in the next release, terraform will be compatible with fortios 7.2.4 and this issue will be solved.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @Vokunne， Terraform FOS provider version 1.17.0 has released, please check it out. If the issue still occurs, please let me know.
