### ISSUE TITLE
Code Crash  

### ISSUE THREAD

**Issue by RalphHolland** [fortinetdev/terraform-provider-fortios#291]
The below crash occurred when using username/password in the provider rather then token
╷
│ Error: Plugin did not respond
│
│   with provider["registry.terraform.io/fortinetdev/fortios"],
│   on providers.tf line 31, in provider "fortios":
│   31: provider "fortios" {
│
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ConfigureProvider call. The plugin logs may contain more        
│ details.
╵

Stack trace from the terraform-provider-fortios_v1.17.0.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x1c pc=0x166aa94]

goroutine 68 [running]:
github.com/terraform-providers/terraform-provider-fortios/sdk/request.(*Request).LoginSession(0x14629110)
        github.com/terraform-providers/terraform-provider-fortios/sdk/request/request.go:422 +0x3c4
github.com/terraform-providers/terraform-provider-fortios/sdk/request.(*Request).Send3(0x14629110, {0x0, 0x0})
        github.com/terraform-providers/terraform-provider-fortios/sdk/request/request.go:158 +0x7f
github.com/terraform-providers/terraform-provider-fortios/sdk/sdkcore.read(0x14791900, {0x291c92c, 0x3}, {0x2965792, 0x1d}, 0x1, {0x0, 0x0})
        github.com/terraform-providers/terraform-provider-fortios/sdk/sdkcore/sdkutils.go:80 +0xb0
github.com/terraform-providers/terraform-provider-fortios/sdk/sdkcore.(*FortiSDKClient).CheckUP(0x14791900)
        github.com/terraform-providers/terraform-provider-fortios/sdk/sdkcore/forticlient.go:77 +0x5e
github.com/terraform-providers/terraform-provider-fortios/fortios.createFortiOSClient(0x14799b08, 0x14155930)
        github.com/terraform-providers/terraform-provider-fortios/fortios/client.go:270 +0x126d
github.com/terraform-providers/terraform-provider-fortios/fortios.(*Config).CreateClient(0x14155930)
        github.com/terraform-providers/terraform-provider-fortios/fortios/client.go:62 +0xd5
github.com/terraform-providers/terraform-provider-fortios/fortios.providerConfigure(0x13f1d130)
        github.com/terraform-providers/terraform-provider-fortios/fortios/provider.go:1087 +0x78f
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Provider).Configure(0x13c860f0, {0x2b94f00, 0x1479d158}, 0x1479cac8)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/provider.go:287 +0x187
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ConfigureProvider(0x13c08aa0, {0x2b94f00, 0x1479c690}, 0x13c09280)    
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:557 +0x3b5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).Configure(0x13f1c230, {0x2b94f00, 0x13c89d28}, 0x14790ca0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:556 +0x2f7
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_Configure_Handler({0x28f78a0, 0x13f1c230}, {0x2b94f00, 0x13c89d28}, 0x14cddfc0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:331 +0x18a
google.golang.org/grpc.(*Server).processUnaryRPC(0x14010120, {0x2b96a80, 0x13d06120}, 0x14796320, 0x13c886f0, 0x346c69c, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xe22
google.golang.org/grpc.(*Server).handleStream(0x14010120, {0x2b96a80, 0x13d06120}, 0x14796320, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa17
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0xb1
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x25f

Error: The terraform-provider-fortios_v1.17.0.exe plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

**Comment by freidenker** [comment]
same issue with you.

**Comment by mhca99** [comment]
Make sure FortiGate VM is reachable from the workstation or pipeline agent where you are executing the TF code.

**Comment by RalphHolland** [comment]
hi @lix-fortinet 

sorry should have updated the ticket, did workout that is was because I forgot to put the port number in (FortiGate runs on non standard port), however would be nice to see the provider handle that gracefully and provide an "unable to connect timeout" type message rather than a crash report

Thanks
Ralph

**Comment by lix-fortinet** [comment]
Hi @RalphHolland,

Thank you for your suggestion and sorry for the late response. We improved the provider to handle this issue.

I will close this issue since it has been resolved. Feel free to reopen it or create a new issue if you have any questions.

Thanks,
Xing
