### ISSUE TITLE
Data source fortios_system_interfacelist not able to filter on interface name

### ISSUE THREAD

**Issue by dbergstra** [fortinetdev/terraform-provider-fortios#293]
I would like to filter on interface name. By filtering on type I got the name "Loopback - NTP".
But when I filter on this name I got nothing... 

When using:
```
data "fortios_system_interfacelist" fortigate_interface_filter {
  filter = "type==loopback"
}
```
output:
```
Changes to Outputs:
  + value = [
      + "Loopback - NTP",
    ]
```

When I filter on this interface name I got "No changes.": 
```
data "fortios_system_interfacelist" fortigate_interface_filter {
  filter = "interface==Loopback - NTP"
}
```

**Comment by MaxxLiu22** [comment]
Hi @danadeweerdx ,

Thank you for raising this question, how about using ``filter = "name==Loopback - NTP"`` and giving a try which works well on my side, let me know if that doesn't work.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @dbergstra 

I will go ahead and close this case. If you have any further questions, feel free to reopen it or open a new case to let us know.

Thanks,
Maxx
