### ISSUE TITLE
Missing 'interface members' for the network interfaces

### ISSUE THREAD

**Issue by tkoeck** [fortinetdev/terraform-provider-fortios#30]
Hi,

I haven't found a Terraform resource to setup the Network -> Internfaces -> lan resource.

The 

'fortios_networking_interface_port' -> (source from https://www.terraform.io/docs/providers/fortios/r/fortios_networking_interface_port.html)

resource seems to be fitting somehow but I cannot see an option for setting up several 'Interface members' for the lan interface. E.g. we have 'internal' and 'wifi' as interface members in the Web gui.

Is it not possible to setup or am I missing a configuration option?

Greetings and thanks,
Tobias

**Comment by frankshen01** [comment]
Hi @tkoeck, the current version of Terraform Provider for FortiOS is limited to support the following features: https://www.terraform.io/docs/providers/fortios/index.html .

The feature will be implemented in the next release.

**Comment by gaozb01** [comment]
Hi @tkoeck , 

I am going to implement this feature which you need on my side now.  

if my understanding is right, the "interface members" option is only available when the interface type is "Software Switch", "802.3ad Aggregate" or "Redundant Interface", which type is the one you need?

Thanks,
Mark Gao

**Comment by pdomineaux** [comment]
Hi @gaozb01,

I would like to use it with "802.3ad Agreggate". 
Have you made any progress ? Is there a workaround?

Thanks,
Philippe Domineaux.

**Comment by gaozb01** [comment]
Hi @pdomineaux 

Sorry i am not work on this feature right now. as frankshen01 said and followed by the plan, it will be implemented in the next release.

**Comment by frankshen01** [comment]
Feature supported: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_system_interface
