### ISSUE TITLE
SSL VPN policy creation failed: node_check_object fail! for name ssl.root

### ISSUE THREAD

**Issue by mkolus** [fortinetdev/terraform-provider-fortios#300]
Hello,

I have a Terraform template that, among other things, enables and configures SSL VPN, a web portal and creates a firewall policy for VPN users.

When I first run it, it fails because there is no ssl.root interface. If I run it again, it works.

In the Terraform output, I see that the SSL VPN settings are applied **before** the policy creation.

Here's the output and the policy configuration part:

```
resource "fortios_firewall_policy" "sslvpn_management_policy" {
  name = "SSLVPN a management"
  srcintf {
    name = local.ssl_vpn_interface
  }
  srcaddr {
    name = fortios_firewall_address.sslvpn_pool[0].name
  }
  groups {
    name = fortios_user_group.tec_vpn_group[0].name
  }
  dstintf {
    name = fortios_system_interface.management_interface.name
  }
  dstaddr {
    name = fortios_firewall_address.management_interface.name
  }
  service {
    name = "ALL"
  }
  schedule = "always"
  action     = "accept"
  logtraffic = "all"
  count = var.sslvpn ? 1 : 0
}
```

[terraform-output.txt](https://github.com/fortinetdev/terraform-provider-fortios/files/13056400/terraform-output.txt)

**Comment by MaxxLiu22** [comment]
Hi @mkolus ,

Thank you for raising this issue, that issue may happened when dependent object hasn't been created when refer it, we can define [depends_on](https://developer.hashicorp.com/terraform/language/meta-arguments/depends_on) block to control creating order, like example below. Let me know if that doesn't solve your question.

Thanks,
Maxx
```
resource "fortios_firewall_object_vipgroup" "v11" {
  name       = "vipgrp"
  interface  = "port3"
  member     = ["vip1"]
  depends_on = [fortios_firewall_object_vip.v13]
}
resource "fortios_firewall_object_vip" "v13" {
  name        = "vip1"
  extip       = "12.1.1.1-22.1.1.1"
  mappedip    = ["23.2.2.2-33.2.2.2"]
  extintf     = "port3"
  portforward = "enable"
  protocol    = "tcp"
  extport     = "2-3"
  mappedport  = "4-5"
}
```

**Comment by mkolus** [comment]
@MaxxLiu22 Sorry, it took a while for me to reply. That **depends_on** did the trick; the template worked just fine in a 40F "out of the box".
