### ISSUE TITLE
Crash of fortios_firewall_centralsnatmap_sort in 1.18.0+

### ISSUE THREAD

**Issue by pacrutchet** [fortinetdev/terraform-provider-fortios#307]
Hello,

I have a crash when upgrading the provider to 1.18.1 (works on 1.17.0):

│ Error: Plugin did not respond
│ 
│   with fortios_firewall_centralsnatmap_sort.snat,
│   on firewall_central_nat.tf line 59, in resource "fortios_firewall_centralsnatmap_sort" "snat":
│   59: resource "fortios_firewall_centralsnatmap_sort" "snat" {
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵

Stack trace from the terraform-provider-fortios_v1.18.1 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 10416 [running]:
github.com/terraform-providers/terraform-provider-fortios/sdk/sdkcore.getPolicyListFirewallCentralsnatmap(0xc00164f6c8?, {0x0, 0x0})
        github.com/terraform-providers/terraform-provider-fortios/sdk/sdkcore/firewall_centralsnatmap_sort.go:65 +0x75b
github.com/terraform-providers/terraform-provider-fortios/sdk/sdkcore.(*FortiSDKClient).ReadFirewallCentralsnatmapSort(0x0?, {0xc00052ba78, 0x8}, {0xc00052ba90, 0x9}, {0x0?, 0x0?}, {0x27bf3c8, 0x0, 0x0})
        github.com/terraform-providers/terraform-provider-fortios/sdk/sdkcore/firewall_centralsnatmap_sort.go:272 +0x59
github.com/terraform-providers/terraform-provider-fortios/fortios.resourceFirewallCentralsnatmapSortRead(0xc000d73b00, {0x1b06ae0?, 0xc000118120})
        github.com/terraform-providers/terraform-provider-fortios/fortios/resource_firewall_centralsnatmap_sort.go:188 +0x3c9
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0x1ed4d60?, {0x1ed4d60?, 0xc001204e40?}, 0xd?, {0x1b06ae0?, 0xc000118120?})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:712 +0x178
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000ca0b60, {0x1ed4d60, 0xc001204e40}, 0xc0016a28f0, {0x1b06ae0, 0xc000118120})
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/resource.go:1015 +0x585
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc0001a0b70, {0x1ed4d60?, 0xc001204d20?}, 0xc000122b40)
        github.com/hashicorp/terraform-plugin-sdk/v2@v2.26.1/helper/schema/grpc_provider.go:613 +0x4a5
github.com/hashicorp/terraform-plugin-go/tfprotov5/tf5server.(*server).ReadResource(0xc0001a2320, {0x1ed4d60?, 0xc001204570?}, 0xc001dd5b00)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/tf5server/server.go:748 +0x4b1
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler({0x1c0d560?, 0xc0001a2320}, {0x1ed4d60, 0xc001204570}, 0xc00032a1c0, 0x0)
        github.com/hashicorp/terraform-plugin-go@v0.14.3/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:349 +0x170
google.golang.org/grpc.(*Server).processUnaryRPC(0xc0004e8000, {0x1ed8880, 0xc000bca680}, 0xc001201320, 0xc000c41350, 0x27811d0, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1340 +0xd23
google.golang.org/grpc.(*Server).handleStream(0xc0004e8000, {0x1ed8880, 0xc000bca680}, 0xc001201320, 0x0)
        google.golang.org/grpc@v1.51.0/server.go:1713 +0xa2f
google.golang.org/grpc.(*Server).serveStreams.func1.2()
        google.golang.org/grpc@v1.51.0/server.go:965 +0x98
created by google.golang.org/grpc.(*Server).serveStreams.func1
        google.golang.org/grpc@v1.51.0/server.go:963 +0x28a

Error: The terraform-provider-fortios_v1.18.1 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.

terraform code:

locals {
  snats = yamldecode(file("config/firewall_central_nat.yml"))
}

resource "fortios_firewall_centralsnatmap" "snat" {
  for_each  = local.snats.snat
  nat       = "enable"
  nat_port  = "0"
  orig_port = "0"
  policyid  = each.key
  protocol  = 0
  status    = "enable"

  dynamic "dst_addr" {
    for_each = toset(try(each.value.dst_addr, ["all"]))
    content {
      name = dst_addr.value
    }
  }

  dynamic "dstintf" {
    for_each = toset(try(each.value.dstintf, ["any"]))
    content {
      name = dstintf.value
    }
  }

  dynamic "orig_addr" {
    for_each = toset(try(each.value.orig_addr, ["all"]))
    content {
      name = orig_addr.value
    }
  }
  
  dynamic "srcintf" {
    for_each = toset(try(each.value.srcintf, ["any"]))
    content {
      name = srcintf.value
    }
  }

  dynamic "nat_ippool" {
    for_each = toset(try(each.value.nat_ippool, []))
    content {
      name = nat_ippool.value
    }
  }

  dynamic_sort_subtable = true
  depends_on = [
    fortios_firewall_address.address,
    fortios_firewall_addrgrp.addrgrp,
    fortios_firewall_ippool.ippool,
    fortios_firewallservice_custom.services,
    module.ipsec
  ]
}

resource "fortios_firewall_centralsnatmap_sort" "snat" {
  sortby        = "policyid"
  sortdirection = "ascending"

  depends_on = [
    fortios_firewall_centralsnatmap.snat
  ]

}

config file example:

snat:
  10:
    orig_addr:
      - dev1
    srcintf:
      - VPN-01
    dstintf:
      - port2
    nat_ippool:
      - dev1
  11:
    orig_addr:
      - dev2
    srcintf:
      - VPN-01
    dstintf:
      - port2
    nat_ippool:
      - dev2
  12:
    orig_addr:
      - dev3
    srcintf:
      - VPN-01
    dstintf:
      - port2
    nat_ippool:
      - dev3

**Comment by MaxxLiu22** [comment]
Hi @pacrutchet 

Thank you for raising this issue, I can reproduce that, crash happened when sort centralsnatmap items, I have reported this to the development team. will let you know once that has been fixed, Sorry for any inconvenience.

Thanks,
Maxx

**Comment by pacrutchet** [comment]
Thanks a lot for coming back to me!

**Comment by MaxxLiu22** [comment]
Hi @pacrutchet ,

This issue has been fixed in our latest Terraform FOS 1.19.0, thank you again for reporting this issue. I will go ahead to close this case, you are free to reopen it or another case if you have any other questions.

Thanks,
Maxx
