### ISSUE TITLE
active_flow_timeout - Timeout values 

### ISSUE THREAD

**Issue by fgloureiro222** [fortinetdev/terraform-provider-fortios#309]
On documentation states:
[active_flow_timeout](https://registry.terraform.io/providers/fortinetdev/fortios/1.18.0/docs/resources/fortios_system_netflow#active_flow_timeout) - Timeout to report active flows (1 - 60 min, default = 30).

When applying configuration to a FortiOS device getting internal server error:

Error: Error updating SystemNetflow resource: Internal Server Error - Internal error when processing the request (500)
Cli response: 
The active-flow-timeout **value 30 must be in the range of 60-3600**.

**Comment by MaxxLiu22** [comment]
Hi @fgloureiro222 ,

Thank you for raising this issue. Our Terraform provider is compatible with varies FOS systems, but the setting rule of some arguments in these FOS are slightly different that causing our Terraform doc is inaccurate for some FOS system, we are continuing improve our doc content, Sorry for any inconvenience.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @fgloureiro222 ,

We have fixed this typo in our latest doc, I will go ahead to close this case, but you are free to reopen it or another case if you still have questions.

Thanks,
Maxx

**Comment by fgloureiro222** [comment]
Thank you 👍
