### ISSUE TITLE
Wifi resources

### ISSUE THREAD

**Issue by tkoeck** [fortinetdev/terraform-provider-fortios#31]
Hi,
there seems to be no resources for Wifi configuration. Is it missing or have I overlooked it?

**Comment by frankshen01** [comment]
The feature will be implemented in the next release.

**Comment by gaozb01** [comment]
Hi @tkoeck ,

I am going to implement this feature that you want here, can you show me what functionality about wifi do you want? which arguments do you want to support? you can describe it by FortiGate GUI interface.

Thanks,
Mark

**Comment by tkoeck** [comment]
Hi Mark,

because the Terraform provider was rather incomplete for several topics (WLAN, VPN, ...) and we had some time constraints we had switched to do set it manually.

I know you develop the provider for yourself and a I respect you for it. The challenge to use the Terraform provider productively it is required that it supports (almost) all options the resource and options a resource has to offer. If half of the options aren't available that's a problem to use it in a production environment.

Greetings
Tobias

Greetings
Tobias

**Comment by gaozb01** [comment]
Hi Tobias,

Sorry about the inconvenient, since it is the first version of FortiOS provider, it just support the very basic functions for now. if you want some features, which are not supported, in hurry, i can do it for you in priority. if you want some resources with fully support(WLAN, VPN , ...) , it's better to wait for the next official release version.

We are developing the next version now, which will support all necessary arguments for most resources. 

Thanks for your understanding, please feel free to contact us if anyting relevant to FortiOS provider.

Regards,
Mark

**Comment by tkoeck** [comment]
Hi Mark,

thanks for the response. I suspect you're programming the provider in your free time? So respect to that effort.

I can take pictures from the Web GUI options if you want to know the options but unfortunately I can't try them out because the router is already in production.

If you want to develop further, especially the Wifi options, I suggest to buy a used FortiWifi 30E or higher for a few bucks. They should work with the newest FortiOS and should be fitting to try your newest options.

**Comment by gaozb01** [comment]
Hi Tobias,

I am working at Fortinet and focusing on Terraform project with Frank now, i am a new member of the team, nice to meet you :)

As always,  feel free to contact us if anyting relevant to FortiOS provider you need.

Thanks,
Mark

**Comment by tkoeck** [comment]
Hi Mark,

thanks for clarifying it. So it seems to be an official supported project after all. Getting test hardware from Fortinet shouldn't be a problem then. ;-)

I had especially contact with the WiFi and VPN options. To be usable as a Terraform provider IMHO the provider should be able to use Terraform for all options available in the Web GUI / Console. At least that works that way with in AWS, Azure and HetznerCloud provider.

As the other router companies don't really have complete Terraform implementations too it might be a unique selling point for Fortinet to provide a good and complete Terraform provider. And to push forward the Infrastructure as Code culture. :smiley: 

I can probably test the provider on a later stage again if required.

Greetings
Tobias

**Comment by gaozb01** [comment]
Hi Tobias,

Yes, we are trying to make it better: support more resources with all necessary arguments, easy to use and stable. 

I think the next version will cover your requirements on WIFI and VPN, you can test it when it is released if you want. 

Thanks,
Mark

**Comment by frankshen01** [comment]
Feature supported, please see "Wireless-Controller" part in https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs , Thanks!
