### ISSUE TITLE
template_tx_timeout - default values

### ISSUE THREAD

**Issue by fgloureiro222** [fortinetdev/terraform-provider-fortios#310]
[template_tx_timeout](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_system_netflow#template_tx_timeout) - Timeout for periodic template flowset transmission (1 - 1440 min, default = 30).

When applying configuration on a FortiOS device:

Error: Error updating SystemNetflow resource: Internal Server Error - Internal error when processing the request (500)
Cli response: 
The template-tx-timeout value 30 must be in the range of 60-86400.

**Comment by MaxxLiu22** [comment]
Hi @fgloureiro222 ,

Thank you for raising this issue and sorry for the confusing content. Like the explanation in your [last case](https://github.com/fortinetdev/terraform-provider-fortios/issues/309#issuecomment-1870537588) , I suggest using CLI returned error as an instruction to setting this argument, and we will continue to improve the documentation part, Thank you for this valuable issue.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
Hi @fgloureiro222 ,

We have fixed this typo in our latest doc, I will go ahead to close this case, but you are free to reopen it or another case if you still have questions.

Thanks,
Maxx

**Comment by fgloureiro222** [comment]
Thank you 👍
