### ISSUE TITLE
NFR - fortiflex equivalent of fortios_system_license_vm

### ISSUE THREAD

**Issue by AD-GenY** [fortinetdev/terraform-provider-fortios#313]
We should have fortiflex equivalent of this resource to update the license using fortiflex tokens

fortios_system_license_vm

Thanks !

**Comment by lix-fortinet** [comment]
Hi @AD-GenY,

Thank you for raising this request! We will support it on the next release.

Thanks,
Xing

**Comment by AD-GenY** [comment]
Thank you ! Appreciate that :)

**Comment by MaxxLiu22** [comment]
Hi @DanielAtella 

New resource [fortios_system_license_fortiflex](https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_system_license_fortiflex) has been added  in Terraform FOS 1.19.1. Please upgrade to this version and give it a try.

Thanks,
Maxx

**Comment by lix-fortinet** [comment]
Hi @AD-GenY,

I will close this issue since it has been fixed. Feel free to open a new issue if you have any questions.

Thanks,
Xing
