### ISSUE TITLE
After creating a 'fortios_vpnipsec_phase1interface' & 'fortios_vpnipsec_phase2interface', manual imports are needed for 'fortios_system_interface'

### ISSUE THREAD

**Issue by vxjohanforssell** [fortinetdev/terraform-provider-fortios#319]
After creating a 'fortios_vpnipsec_phase1interface' & 'fortios_vpnipsec_phase2interface', manual imports are needed for 'fortios_system_interface' which is auto created.

Apart from being quite odd behaviour from a Terraform point of view, this is not mentioned in the documentation at all. 

Please document this behavious properly. This little box at the bottom of https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_system_interface is not really helpful!
![Screenshot 2024-03-20 at 12 18 17](https://github.com/fortinetdev/terraform-provider-fortios/assets/133804877/8abc019b-ea52-44d9-9b91-7537eefc06d3)

This have been described in #252.

**Comment by MaxxLiu22** [comment]
Hi @vxjohanforssell ,

Thank you for your suggestion. It can be confusing for users deploying an IPsec tunnel for the first time. We will work on improving our documentation regarding this matter later.

Thanks,
Maxx

**Comment by MaxxLiu22** [comment]
I will proceed with closing this case. However, feel free to reopen it if you continue to experience this issue.
