### ISSUE TITLE
IKEv1 VPN in 'fortios_vpn_ipsec_phase1interface'

### ISSUE THREAD

**Issue by tkoeck** [fortinetdev/terraform-provider-fortios#32]
Hi,

as far as I have seen there is no resource for creating IKEv1 VPNS.

https://www.terraform.io/docs/providers/fortios/r/fortios_vpn_ipsec_phase1interface.html

Any idea why it is not supported?

Greetings
Tobias

**Comment by frankshen01** [comment]
Hi @tkoeck, we are analyzing the request.

**Comment by frankshen01** [comment]
Feature supported: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_vpnipsec_phase1interface
