### ISSUE TITLE
fortios_system_sdwan health_check

### ISSUE THREAD

**Issue by zippanto** [fortinetdev/terraform-provider-fortios#325]
Opening a new issue about the same issue that was reported in #98 as I'm not sure commenting on there will get the right attention.

Should this not be handled by the provider instead of expecting the user to do the escaping?

Thanks.

**Comment by MaxxLiu22** [comment]
Hi @zippanto,

Thank you for raising this issue, I can reproduce that and have reported it to the development team for fixing, sorry for any inconvenience.

Thanks,
Maxx

**Comment by zippanto** [comment]
Seems to be fixed in the latest release of FortiOS Terraform provider v1.20.0.

Thanks.
