### ISSUE TITLE
Can't unset interface allowaccess attribute

### ISSUE THREAD

**Issue by jzamanski-pm** [fortinetdev/terraform-provider-fortios#326]
HI, I'm unable to unset the "allowaccess" field of an interface via terraform. Passing an empty string or null leaves it unchanged. Is this expected?

**Comment by MaxxLiu22** [comment]
Hi @jzamanski-pm ,

Thank you for raising this issue. I can reproduce it. I found that the API sent ``null`` to unset allowaccess, but Terraform regards ``null`` as an empty value and ignores it. I have reported this to the development team for a fix. Sorry for any inconvenience.
Thanks,

Maxx

**Comment by MaxxLiu22** [comment]
Hi @jzamanski-pm 

I wanted to let you know that this issue has been resolved in Terraform FOS 1.21.0. Starting with this version, Terraform now supports the unset function if the argument is not set. Whenever you have a chance, please upgrade to this version, and feel free to reach out if you have any further questions.

Thank you,
Maxx

**Comment by MaxxLiu22** [comment]
I will proceed with closing this case. However, feel free to reopen it if you continue to experience this issue.
