### ISSUE TITLE
Missing arguments in the resources fortios_vpn_ipsec_phase{1,2}interface 

### ISSUE THREAD

**Issue by tkoeck** [fortinetdev/terraform-provider-fortios#35]
Hi,

I am trying to create a VPN connection with the resources

fortios_vpn_ipsec_phase{1,2}interface.

Unfortunately there seem to be no way to configure

- Diffie-Hellman Groups
- key lifetime

in phase1.

The same is for the phase2

- Enable Replay Detection
- Enable Perfect Forward Secrecy (PFS)
- Diffie-Hellman Groups

The other additional avanced options doesn't seem to be configurable as well.

At least DH Groups, PFD and Replay Detection is unfortunately required for a secure VPN.

Greetings
Tobias

**Comment by gaozb01** [comment]
Hi @tkoeck, 

This will be supported in the next release version, thanks for the information and please let me know if you have any other questions.

Regards,
Mark Gao

**Comment by frankshen01** [comment]
Feature supported: 
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_vpnipsec_phase1
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_vpnipsec_phase2
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_vpnipsec_phase1interface
https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_vpnipsec_phase2interface
