### ISSUE TITLE
Unable to define ikev2 under resource "fortios_vpn_ipsec_phase1interface" 

### ISSUE THREAD

**Issue by gav1n0** [fortinetdev/terraform-provider-fortios#38]
Trying to use ikev2 under resource "fortios_vpn_ipsec_phase1interface"  but not sure if any argument support it.

**Comment by gaozb01** [comment]
Hi @gav1n0 , this feature will be supported in the next release version. thanks.

**Comment by gaozb01** [comment]
@gav1n0 we can not estimate the time yet, but probably somewhere in 2020.

**Comment by frankshen01** [comment]
Feature supported: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_vpnipsec_phase1interface
