### ISSUE TITLE
Firewall VIP of type fqdn support

### ISSUE THREAD

**Issue by pmcevoy** [fortinetdev/terraform-provider-fortios#42]
I'm trying to create a firewall vip object of type FQDN.  This is the plan generated:

```
 # fortios_firewall_object_vip.vip["8870"] will be created
  + resource "fortios_firewall_object_vip" "vip" {
      + comment     = "Created by Terraform Provider for FortiOS"
      + extintf     = "port1"
      + extip       = "10.85.36.19"
      + extport     = "443"
      + id          = (known after apply)
      + mappedip    = [
          + "public-edts.app.aws",
        ]
      + mappedport  = "8870"
      + name        = "fqdn-vip-Edts-8870"
      + portforward = "enable"
      + protocol    = "tcp"
    }
```

But getting the following error:
```
Error: Error creating Firewall Object Vip: cannot get the right response
```

Is there plans to support FQDN VIPs?

**Comment by gaozb01** [comment]
Hi @pmcevoy 

Can you set that FQDN successfully on your FortiGate?
I have tried on my side, and seems that only IP address and address range are supported here.
If you can't set it through GUI, then it will not be supported here. thanks.

**Comment by pmcevoy** [comment]
I can do this:

```
edit "fqdn-vip-Edts-8870"
        set type fqdn
        set extip 10.80.36.19
        set extintf "port1"
        set portforward enable
        set mapped-addr "public-edts.app.aws"
        set extport 443
        set mappedport 8870
    next
```

**Comment by gaozb01** [comment]
Ok, thanks for the info. i will do some research to see whether it can be supported or not and will back to you when i get something.

**Comment by pmcevoy** [comment]
My appologies - the `mapped-addr` value is the **name** of an fqdn address object.
So I need to do this:
```
config firewall address
	edit "fqdn-scheduler"
		set type fqdn
		set associated-interface "port2"
		set fqdn "public-scheduler.app.aws"
	next
end
config firewall vip
	edit "fqdn-vip-scheduler-6501"
		set type fqdn
		set extintf "port1"
		set portforward enable
		set extip 10.85.36.13
		set extport 6501
		set mapped-addr "fqdn-scheduler"
		set mappedport 6501
	next
end
```

**Comment by gaozb01** [comment]
Hi @pmcevoy , this feature will be supported in the next version.  i will keep you updated when it is ready. thanks.

**Comment by frankshen01** [comment]
Feature supported: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_vip
