### ISSUE TITLE
Configuration FortiOs Token

### ISSUE THREAD

**Issue by khalilbo** [fortinetdev/terraform-provider-fortios#45]
Hello,

I need your help please!

I am looking to use FortiOs provider et when I make configuration in .tf file I don’t know where I can take token.

token = "jn3t3Nw7qckQzt955Htkfj5hwQ6jdb"

Can I generated token from my FortiGate or not ?

:)

**Comment by zx1986** [comment]
not work at all!

`Error: Error creating Firewall Object Address: cannot get the right response`

https://kb.fortinet.com/kb/documentLink.do?externalID=FD46329
this API need a username field,
but terraform fortios provider has no username field.

#37

**Comment by zx1986** [comment]
I think it is the fortiOS admin API user's token.
But, it had problems when I use it.
