### ISSUE TITLE
Environment variables

### ISSUE THREAD

**Issue by kevin-dfo** [fortinetdev/terraform-provider-fortios#47]
Hi,

Trying to setup my config to use environment variables instead of the token being saved in the script.  All three in the provider object works, if I set all three as environment variables I get 
Error: Error getting CA Bundle, CA Bundle should be set when insecure is false

  on providers.tf line 1, in provider "fortios":
   1: provider "fortios" {

And if I try to set only the insecure variable in the provider object I get
Error: Error reading Firewall Object Vip: cannot get the right response

provider "fortios" {
  hostname = "40.**.***.***"
  #token = "5zG****************NkQ"
  insecure = "true"
}

kevin@gibson:~/fortimanager/cac$ echo $FORTIOS_ACCESS_HOSTNAME
40.**.***.***
kevin@gibson:~/fortimanager/cac$ echo $FORTIOS_ACCESS_TOKEN
5zG****************NkQ
kevin@gibson:~/fortimanager/cac$ echo $FORTIOS_INSECURE
true
kevin@gibson:~/fortimanager/cac$ terraform --version
Terraform v0.12.17
+ provider.azuread v0.6.0
+ provider.azurerm v1.36.0
+ provider.fortios v1.1.0

**Comment by frankshen01** [comment]
hi @kevin-dfo   please try: 
`unset "FORTIOS_CA_CABUNDLE"`
it should solve your problem.

Successful test cases:

**Example 1:**
```
# export "FORTIOS_ACCESS_HOSTNAME"="192.168.52.177"
# export "FORTIOS_INSECURE"="true"
# export "FORTIOS_ACCESS_TOKEN"="mgyNnqh7t5fHwc1jQQnwp459kG6pNh"

# echo $FORTIOS_ACCESS_HOSTNAME
192.168.52.177
# echo $FORTIOS_INSECURE
true
# echo $FORTIOS_ACCESS_TOKEN
mgyNnqh7t5fHwc1jQQnwp459kG6pNh
# echo $FORTIOS_CA_CABUNDLE

#
```
```
provider "fortios" {

}

resource "fortios_log_fortianalyzer_setting" "test1" {
	status = "enable"
	server = "5.0.1.10"
	source_ip = "192.168.52.177"
	upload_option = "realtime"
	reliable = "enable"
	hmac_algorithm = "sha256"
	enc_algorithm = "high-medium"
}

```

**Exmaple 2:**
```
# export "FORTIOS_ACCESS_TOKEN"="mgyNnqh7t5fHwc1jQQnwp459kG6pNh"

# echo $FORTIOS_ACCESS_HOSTNAME

# echo $FORTIOS_INSECURE

# echo $FORTIOS_ACCESS_TOKEN
mgyNnqh7t5fHwc1jQQnwp459kG6pNh
# echo $FORTIOS_CA_CABUNDLE

#
```
```
provider "fortios" {
	hostname = "192.168.52.177"
	insecure = "true"
}

resource "fortios_log_fortianalyzer_setting" "test1" {
	status = "enable"
	server = "5.0.1.10"
	source_ip = "192.168.52.177"
	upload_option = "realtime"
	reliable = "enable"
	hmac_algorithm = "sha256"
	enc_algorithm = "high-medium"
}
```
Thanks!

**Comment by kdutt** [comment]
Thanks! 

the following worked for me.

```
provider "fortios" {
  hostname = "40..."
  insecure = "true"
}

unset "FORTIOS_CA_CABUNDLE"
export "FORTIOS_ACCESS_TOKEN"=$((az keyvault secret show --vault-name "valut" --name "RestAPI" --query 'value' -o json) | tr -d \")
```

**Comment by zx1986** [comment]
not work at all!

Error: Error creating Firewall Object Address: cannot get the right response

https://kb.fortinet.com/kb/documentLink.do?externalID=FD46329
this API need a username field,
but terraform fortios provider has no username field.

#37

**Comment by frankshen01** [comment]
Hi, @zx1986 , Thanks for your information, I can understand your troubles, let me help you solve the issue.

There are two ways that user can authenticate against the API :

- Session-based authentication
- Token-based authentication

Terraform FortiOS Provider uses the latter. For security reasons, the former one will be depreceated by FortiAPI in the future.

For complete instructions, please refer to:  https://kb.fortinet.com/kb/documentLink.do?externalID=FD45595


Next, Let me introduce the detailed steps to configure FortiOS Provider through CLI for you:

**1 Config API-USER:**
```
mytestFortiGate (testapiuser) # 
config system api-user
    edit "testapiuser"
        set accprofile "super_admin"
        set vdom "root"
        config trusthost
            edit 1
                set ipv4-trusthost 192.168.0.0 255.255.0.0
            next
        end
    next
end
```
There are two important things here:
(1) The accprofile should be set to super_admin
(2) Trusthost should include the network segment where the client running Terraform is located, FortiAPI will authorize these IP addresses for access rights;


**2 Get token for the API-USER:**
```
myFirewall #  execute api-user generate-key testapiuser
New API key: gt1ryQG3j96G7pz6ttzm8kynt6y5fH

```

**3 Write TF file**
```

root@sv:/aicetest/terraform/bin# cat main.tf
provider "fortios" {
        hostname = "192.168.52.177"
        token = "gt1ryQG3j96G7pz6ttzm8kynt6y5fH"
        insecure = true
}

resource "fortios_firewall_object_address" "s1" {
        name = "s1"
        type = "iprange"
        start_ip = "1.0.0.0"
        end_ip = "2.0.0.0"
        comment = "dd"
}

```
Remarks: The token here needs to be filled in with the token obtained in the second step.


**4 run terraform init**
```
root@sv:/aicetest/terraform/bin# terraform init

Initializing the backend...

Initializing provider plugins...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```


**5 run terraform plan**
```

root@sv:/aicetest/terraform/bin# terraform plan
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # fortios_firewall_object_address.s1 will be created
  + resource "fortios_firewall_object_address" "s1" {
      + comment                = "dd"
      + end_ip                 = "2.0.0.0"
      + id                     = (known after apply)
      + name                   = "s1"
      + show_in_address_list   = "enable"
      + start_ip               = "1.0.0.0"
      + static_route_configure = "disable"
      + subnet                 = "0.0.0.0 0.0.0.0"
      + type                   = "iprange"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.
```

**6 run terraform apply**
```
root@sv:/aicetest/terraform/bin# terraform apply

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # fortios_firewall_object_address.s1 will be created
  + resource "fortios_firewall_object_address" "s1" {
      + comment                = "dd"
      + end_ip                 = "2.0.0.0"
      + id                     = (known after apply)
      + name                   = "s1"
      + show_in_address_list   = "enable"
      + start_ip               = "1.0.0.0"
      + static_route_configure = "disable"
      + subnet                 = "0.0.0.0 0.0.0.0"
      + type                   = "iprange"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

fortios_firewall_object_address.s1: Creating...
fortios_firewall_object_address.s1: Creation complete after 0s [id=s1]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Additional:**
You can learn more about api-user from:
https://docs.fortinet.com/document/fortigate/6.0.6/cli-reference/883891/system-api-user
https://docs.fortinet.com/document/fortigate/6.0.6/cli-reference/474886/api-user

You can refer to page 10,11 of FortiOS - REST API Reference for more instructions for token
https://fndn.fortinet.net/index.php?/documents/file/149-fortios-60-rest-api-reference-603/


In fact, we have added detailed instructions on token configuration in the upcoming new version.

I hope this will help. Let me know if you have any questions, Thank you!

(BTW: Copied Comments has been hided)

Hi, @kevin-dfo , I'm sorry for taking up your space, please forgive me! Thanks!

**Comment by zx1986** [comment]
@frankshen01 thanks for you reply.
I follow the steps you wrote, and here's my envirnment:

```
Using Kubernetes executor with image hashicorp/terraform:0.12.24 ...
- Downloading plugin for provider "fortios" (terraform-providers/fortios) 1.1.0...
* provider.fortios: version = "~> 1.1"
```

`terraform plan` works fine.

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # fortios_firewall_object_address.dns1 will be created
  + resource "fortios_firewall_object_address" "dns1" {
      + comment  = "DNS Master Server"
      + end_ip   = "0.0.0.0"
      + id       = (known after apply)
      + name     = "tf_devops-dns1"
      + start_ip = "0.0.0.0"
      + subnet   = "192.168.101.1 255.255.255.255"
      + type     = "ipmask"
    }

  # fortios_firewall_object_address.dns2 will be created
  + resource "fortios_firewall_object_address" "dns2" {
      + comment  = "DNS Slave Server"
      + end_ip   = "0.0.0.0"
      + id       = (known after apply)
      + name     = "tf_devops-dns2"
      + start_ip = "0.0.0.0"
      + subnet   = "192.168.101.2 255.255.255.255"
      + type     = "ipmask"
    }
```


but `terraform apply` got the same error as usual:

```
Error: Error creating Firewall Object Address: cannot get the right response

  on main.tf line 24, in resource "fortios_firewall_object_address" "dns1":
  24: resource "fortios_firewall_object_address" "dns1" {



Error: Error creating Firewall Object Address: cannot get the right response

  on main.tf line 31, in resource "fortios_firewall_object_address" "dns2":
  31: resource "fortios_firewall_object_address" "dns2" {
```

**Comment by zx1986** [comment]
@frankshen01 Sorry, I change my API user to the "super_admin" profile, and it seems work. (still creating ...)

I had a "devops_admin" profile for terraform with all resource's Read/Write permission, but it won't work.
It had to be "super_admin" profile?

**Comment by frankshen01** [comment]
Hi @zx1986  It is good to see that you are almost at the point of success.

Now it seems that there is a problem with the connection between your client running Terraform and the Firewall. Please try the following command to debug the network connection to Firewall first:

```
curl -k 'https://192.168.52.177:1443/api/v2/cmdb/system/global?access_token=09m441wrwc10yGyrtQ4nk6mjbqcfz9'
```
Note: Change the **IP, admin-sport and token** here to **your IP, admin-sport and token** and make sure it can return results similar to the following (By the way, if your admin-sport is the default 443, you can ignore admin-sport, that means: `curl -k 'https://192.168.52.177/api/v2/cmdb.......'` ) :
```
{
  "http_method":"GET",
  "revision":"11.0.0.9541577349505417509.1587572705",
  "results":{
    "language":"english",
    "gui-ipv6":"disable",
    "gui-certificates":"enable",
    "gui-custom-language":"disable",
    "gui-wireless-opensecurity":"disable",
    "gui-display-hostname":"disable",
    "gui-lines-per-page":50,
    "admin-https-ssl-versions":"tlsv1-1 tlsv1-2",
    "admintimeout":65,
    ........
    "igmp-state-limit":3200,
    "cloud-communication":"enable"
  },
  "vdom":"root",
  "path":"system",
  "name":"global",
  "status":"success",
  "http_status":200,
  "serial":"FGVM02TM20003062",
  "version":"v6.2.0",
  "build":776
}

```
If it fails, check your network until the above command can successfully return the required value.

When it succeeds, run your terraform again, it should be okay. Note that if your admin-sport is not the default 443, you need to add admin-sport after the hostname, for example:

```
provider "fortios" {
	hostname = "192.168.52.177:1443"
	token = "09m441wrwc10yGyrtQ4nk6mjbqcfz9"
	insecure = true
}

```

BTW: Not all resources require super_admin, but some resources like add vdom require super_admin permissions, it is recommended that you use super_admin:

Also, yu can view admin-sport by the following command
```
myfirewall # config system global
myfirewall (global) # show
path=system, objname=global, tablename=(null), size=1272
config system global
    set admin-sport 1443
    set admintimeout 65
    set alias "FGVM02TM20003062"
    set hostname "myfirewall"
    set timezone 04
end
```

Thanks!

**Comment by zx1986** [comment]
@frankshen01 thank you so much for your patient. 
I ran the test and got 403 error, I am trying to figure it out:

➜ curl -v -k 'https://192.168.5.44:5443/api/v2/cmdb/system/global?access_token=MYTOKEN'

```
< HTTP/1.1 401 Authorization Required
< Date: Fri, 24 Apr 2020 02:14:04 GMT
< Server:
< Transfer-Encoding: chunked
< Content-Type: text/html; charset=iso-8859-1
< X-Frame-Options: SAMEORIGIN
< Content-Security-Policy: frame-ancestors 'self'
< X-XSS-Protection: 1; mode=block
< Strict-Transport-Security: max-age=0
< X-UA-Compatible: IE=Edge
<
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<HTML><HEAD>
<TITLE>401 Authorization Required</TITLE>
</HEAD><BODY>

<H1>Authorization Required</H1>
This server could not verify that you
are authorized to access the document
requested.  Either you supplied the wrong
credentials (e.g., bad password), or your
browser doesn't understand how to supply
the credentials required.<P>

<P>Additionally, a 401 Authorization Required
error was encountered while trying to use an ErrorDocument to handle the request.
</BODY></HTML>

* Connection #0 to host 192.168.5.44 left intact
* Closing connection 0
``` 

My fortiOS version: v6.2.2 build1010 (GA)

**Comment by frankshen01** [comment]
No problem. Until now,  the “401 Authorization Required” error should be caused by incorrect token or trust-host. Follow the steps below to find the problem:

**1 Turn on the firewall debug**
SSH to the Firewall and execute the following command (Close Firewall WEBUI, otherwise a lot of log information will be printed later)
```
diagnose debug enable
diagnose debug cli 8
diagnose debug application httpsd -1
```

**2 Execute your curl command again**
```
curl -v -k 'https://192.168.5.44:5443/api/v2/cmdb/system/global?access_token=MYTOKEN'
```

**3 View the debugging information printed by the firewall on SSH**
You can paste the information here, I will help locate which is wrong.  Or if you want, you can solve it yourself with the steps below: 

_(1) If it contains something like the following:_
```
[httpsd 2246 - 1587714906     info] api_access_check_for_api_key[919] -- Peer not trusted: 192.168.52.1.
```
This means that the trust-host config is wrong, 192.168.52.1 is not included in the trusted host. Usually, it is caused by **the intermediate network equipment doing NAT conversion to the client IP running terraform**, which causes the SIP seen by the firewall to be different from the client IP running Terraform. .  Solution: Add 192.168.52.1(you need use the IP print in your debug information) or its network segment to api-user's trusted host. 
```
myfirewall (api-user) # show
config system api-user
    edit "test-apiuser"
        set accprofile "SE"
        set vdom "root"
        config trusthost
            edit 1
                set ipv4-trusthost 192.168.0.0 255.255.0.0
            next
        end
    next
end
```

_(2) If it contains something like the following:_
```
[httpsd 2251 - 1587715091  warning] _lock_out_check_and_lock_out[533] -- Failed api-key login attempt from 192.168.52.1.
```
This means that the token is wrong and the token needs to be corrected.

Thanks!

**Comment by zx1986** [comment]
@frankshen01 It works!

```
< HTTP/1.1 200 OK
< Date: Fri, 24 Apr 2020 13:23:48 GMT
< Server:
< Cache-Control: no-cache, must-revalidate
< ETag: db4449be0aa17e8a9019774fd4ca1b6b
< Content-Length: 6500
< Content-Type: application/json
< X-Frame-Options: SAMEORIGIN
< Content-Security-Policy: frame-ancestors 'self'
< X-XSS-Protection: 1; mode=block
< Strict-Transport-Security: max-age=0
< X-UA-Compatible: IE=Edge
<
{
  "http_method":"GET",
  "revision":"db4449be0aa17e8a9019774fd4ca1b6b",
  "results":{
    "language":"english",
    "gui-ipv6":"disable",
    "gui-certificates":"enable",
    "gui-custom-language":"disable",
    "gui-wireless-opensecurity":"disable",
    "gui-display-hostname":"disable",
    "gui-fortisandbox-cloud":"disable",
    "gui-lines-per-page":50,
    "admin-https-ssl-versions":"tlsv1-1 tlsv1-2",
    "admintimeout":5,
    "admin-console-timeout":0,
    "admin-http-connection-receive-timeout":2,
    "ssd-trim-freq":"weekly",
```

oh my god .... my tears coming out of my eyes.

@frankshen01 Thank you so much for your useful & patient & kind replies!
