### ISSUE TITLE
Feature Request: Security Profiles/SSL inspection

### ISSUE THREAD

**Issue by liquid-cloud** [fortinetdev/terraform-provider-fortios#48]
Hello,

Is there a plan to implement support for SSL/SSH Inspection Profiles ? 

Is there a place where we can track the roadmap for the fortios provider ? 

Thank you ! :)

**Comment by frankshen01** [comment]
hi @liquid-cloud , I need to confirm this with my colleagues and then get back to you. Thank you!

**Comment by liquid-cloud** [comment]
Thank you very much :))

**Comment by hpernicha** [comment]
Hi @liquid-cloud 

I am product manager in Fortinet. 
We are developing more features to support FortiOS in Terraform and your request will be evaluated. Unfortunately we can't share any roadmap information.

Thanks,
Hugo

**Comment by yatanasov** [comment]
Hello @liquid-cloud , 
Do you know when can we expect the next release of the Fotrinet provider ? Currently we are building the provider from the master branch which is not optimal for our production environments. 

Thank you!

**Comment by hpernicha** [comment]
Hi,

We are working on adding more features. Unfortunately we can't share any roadmap or release schedules information here. Please reach out to you local Fortinet representatives to get more information.

Thanks,
Hugo

**Comment by frankshen01** [comment]
Feature supported:  https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_system_settings

**Comment by yatanasov** [comment]
Thank you very much for the development of this ! <3

**Comment by frankshen01** [comment]
It was my great pleasure! Thank you @yatanasov
