### ISSUE TITLE
Feature Request : Auto-negotiate and Autokey Keep Alive enable under fortios_vpn_ipsec_phase2interface

### ISSUE THREAD

**Issue by bharat109puri** [fortinetdev/terraform-provider-fortios#51]
I am looking for option to enable Auto-negotiate and Autokey Keep Alive, under fortios_vpn_ipsec_phase2interface.

@frankeinat : Do we have plans to add this feature.

**Comment by hpernicha** [comment]
Hi @bharat109puri 

Thanks for your input. We have plans to support more FortiOS features in Terraform. Extending ipsec VPN support is planned for futurte development.

Hugo

**Comment by frankshen01** [comment]
Feature supported: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_vpnipsec_phase2interface
