### ISSUE TITLE
Feature Request: Add ability to manage DNS server entries

### ISSUE THREAD

**Issue by danstis** [fortinetdev/terraform-provider-fortios#58]
I would love to see the ability to add DNS server entries added to this provider.

This should allow to create new DNS records under an existing DNS Zone (DNS Server).

**Comment by hpernicha** [comment]
Hi,

Thanks for you suggestion. We will be looking into adding that feature in the future.

Regards,
Hugo Pernicha

**Comment by frankshen01** [comment]
Feature supported: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_system_dnsserver
