### ISSUE TITLE
'make testacc' failing

### ISSUE THREAD

**Issue by hxvxt2** [fortinetdev/terraform-provider-fortios#59]
I am not able to run `make testacc` even after setting the correct value for  `FORTIOS_ACCESS_HOSTNAME` and `FORTIOS_ACCESS_TOKEN` in my `~/.zshrc` file.

Below is the output:

`➜  terraform-provider-fortios git:(master) ✗ make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?   	github.com/terraform-providers/terraform-provider-fortios	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestAccFortiOSFirewallObjectAddress_withIPRange
--- FAIL: TestAccFortiOSFirewallObjectAddress_withIPRange (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectAddress_withGeography
--- FAIL: TestAccFortiOSFirewallObjectAddress_withGeography (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectAddress_withFqdn
--- FAIL: TestAccFortiOSFirewallObjectAddress_withFqdn (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectAddressGroup_basic
--- FAIL: TestAccFortiOSFirewallObjectAddressGroup_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectIPPool_Overload
--- FAIL: TestAccFortiOSFirewallObjectIPPool_Overload (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectIPPool_OneToOne
--- FAIL: TestAccFortiOSFirewallObjectIPPool_OneToOne (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectService_Fqdn
--- FAIL: TestAccFortiOSFirewallObjectService_Fqdn (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectService_IPRange
--- FAIL: TestAccFortiOSFirewallObjectService_IPRange (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectServiceCategory
--- FAIL: TestAccFortiOSFirewallObjectServiceCategory (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectServiceGroup_basic
--- FAIL: TestAccFortiOSFirewallObjectServiceGroup_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectVip_basic
--- FAIL: TestAccFortiOSFirewallObjectVip_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallObjectVipGroup_basic
--- FAIL: TestAccFortiOSFirewallObjectVipGroup_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallSecurityPolicy_basic
--- FAIL: TestAccFortiOSFirewallSecurityPolicy_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSFirewallSecurityPolicySeq_basic
--- FAIL: TestAccFortiOSFirewallSecurityPolicySeq_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSLogFortiAnalyzerSetting_basic
--- FAIL: TestAccFortiOSLogFortiAnalyzerSetting_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSLogSyslogSetting_basic
--- FAIL: TestAccFortiOSLogSyslogSetting_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSNetworkingInterfacePort_Physical
--- FAIL: TestAccFortiOSNetworkingInterfacePort_Physical (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSNetworkingInterfacePort_Vlan
--- FAIL: TestAccFortiOSNetworkingInterfacePort_Vlan (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSNetworkingInterfacePort_Loopback
--- FAIL: TestAccFortiOSNetworkingInterfacePort_Loopback (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSNetworkingRouteStatic_basic
--- FAIL: TestAccFortiOSNetworkingRouteStatic_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSSystemAdminAdministrator_basic
--- FAIL: TestAccFortiOSSystemAdminAdministrator_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSSystemAdminProfiles_basic
--- FAIL: TestAccFortiOSSystemAdminProfiles_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSSystemAPIUserSetting_basic
--- FAIL: TestAccFortiOSSystemAPIUserSetting_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSSystemSettingDNS_basic
--- FAIL: TestAccFortiOSSystemSettingDNS_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSSystemSettingGlobal_basic
--- FAIL: TestAccFortiOSSystemSettingGlobal_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSSystemSettingNTP_basic
--- FAIL: TestAccFortiOSSystemSettingNTP_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSVPNIPsecPhase1Interface_basic
--- FAIL: TestAccFortiOSVPNIPsecPhase1Interface_basic (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSVPNIPsecPhase1Interface_basic2
--- FAIL: TestAccFortiOSVPNIPsecPhase1Interface_basic2 (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSVPNIPsecPhase2Interface_basic1
--- FAIL: TestAccFortiOSVPNIPsecPhase2Interface_basic1 (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
=== RUN   TestAccFortiOSVPNIPsecPhase2Interface_basic2
--- FAIL: TestAccFortiOSVPNIPsecPhase2Interface_basic2 (0.00s)
    provider_test.go:29: FORTIOS_ACCESS_HOSTNAME must be set for acceptance tests
FAIL
FAIL	github.com/terraform-providers/terraform-provider-fortios/fortios	0.070s
make: *** [testacc] Error 1`

**Comment by frankshen01** [comment]
Hi @hxvxt2, please follow the steps below to set it up, it should work well:
```
# pwd
/zamba/standard-terraform/src/github.com/terraform-providers/terraform-provider-fortios

# export GO111MODULE=off
# export GOPATH=/zamba/standard-terraform/
# export "FORTIOS_ACCESS_HOSTNAME"="192.168.52.177"
# export "FORTIOS_INSECURE"="true"
# export "FORTIOS_ACCESS_TOKEN"="hhjd3d1gwsbrj188ch55wpkb98tsws"

# echo $GO111MODULE
off
# echo $GOPATH
/zamba/standard-terraform/
# echo $FORTIOS_INSECURE
true
# echo $FORTIOS_ACCESS_HOSTNAME
192.168.52.177
# echo $FORTIOS_ACCESS_TOKEN
hhjd3d1gwsbrj188ch55wpkb98tsws


# make testacc
==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?       github.com/terraform-providers/terraform-provider-fortios       [no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestAccFortiOSFirewallObjectAddress_withIPRange
--- PASS: TestAccFortiOSFirewallObjectAddress_withIPRange (2.08s)
=== RUN   TestAccFortiOSFirewallObjectAddress_withGeography
--- PASS: TestAccFortiOSFirewallObjectAddress_withGeography (1.57s)
....

```
Thanks!

**Comment by hxvxt2** [comment]
Thanks for your reply @frankshen01 
I made sure the environment variables are set as you suggested. Here they are:-

`~/go/src/github.com/terraform-providers/terraform-provider-fortios`
`❯`                                                                                                                                                                                                      

`❯ echo $GO111MODULE`
off
`❯ echo $GOPATH`
/Users/koba/go
`❯ echo $FORTIOS_INSECURE`
true
`❯ echo $FORTIOS_ACCESS_HOSTNAME`
xx.xx.xx.xx
`❯ echo $FORTIOS_ACCESS_TOKEN`
9hq3qhyH6tGcN174rHb77QGrzfxmc6

Then I tried running the tests again. I now see, what seems like a better error than last time, but an error nevertheless. 

`❯ make testacc`
```==> Checking that code complies with gofmt requirements...
TF_ACC=1 go test $(go list ./... |grep -v 'vendor') -v  -timeout 120m
?   	github.com/terraform-providers/terraform-provider-fortios	[no test files]
=== RUN   TestProvider
--- PASS: TestProvider (0.00s)
=== RUN   TestAccFortiOSFirewallObjectAddress_withIPRange
--- FAIL: TestAccFortiOSFirewallObjectAddress_withIPRange (0.10s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating Firewall Object Address: cannot get the right response

          on /var/folders/kh/m16w2sgn10jd06jfxd58wl_c_2h4vh/T/tf-test504682562/main.tf line 2:
          (source code not available)


=== RUN   TestAccFortiOSFirewallObjectAddress_withGeography
--- FAIL: TestAccFortiOSFirewallObjectAddress_withGeography (0.11s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating Firewall Object Address: cannot get the right response

          on /var/folders/kh/m16w2sgn10jd06jfxd58wl_c_2h4vh/T/tf-test519432388/main.tf line 2:
          (source code not available)
....................................
A N D    S O    O N
....................................
=== RUN   TestAccFortiOSVPNIPsecPhase2Interface_basic2
--- FAIL: TestAccFortiOSVPNIPsecPhase2Interface_basic2 (0.10s)
    testing.go:568: Step 0 error: errors during apply:

        Error: Error creating VPN IPsec Phase1Interface: cannot get the right response

          on /var/folders/kh/m16w2sgn10jd06jfxd58wl_c_2h4vh/T/tf-test530056412/main.tf line 2:
          (source code not available)


FAIL
FAIL	github.com/terraform-providers/terraform-provider-fortios/fortios	7.803s
make: *** [testacc] Error 1.

**Comment by hxvxt2** [comment]
So, I also tried to run a sample scenario from TF quick start guide mentioned here.
[Example Usage for Iprange Service](https://www.terraform.io/docs/providers/fortios/r/fortios_firewall_object_service.html#example-usage-for-iprange-service)

`❯ terraform plan`
```
Refreshing Terraform state in-memory prior to plan...
The refreshed state will be used to calculate this plan, but will not be
persisted to local or remote state storage.


------------------------------------------------------------------------

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # fortios_firewall_object_service.v13 will be created
  + resource "fortios_firewall_object_service" "v13" {
      + category = "General"
      + comment  = "this is from fortios tf module"
      + fqdn     = "abc.com"
      + id       = (known after apply)
      + iprange  = "0.0.0.0"
      + name     = "servicetest1"
      + protocol = "TCP/UDP/SCTP"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

------------------------------------------------------------------------

Note: You didn't specify an "-out" parameter to save this plan, so Terraform
can't guarantee that exactly these actions will be performed if
"terraform apply" is subsequently run.

  ~/Documents/Lambda/Network/Automation/fortitf ··············  23:44:04 ─╮
❯
```

`❯ terraform apply`

```An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # fortios_firewall_object_service.v13 will be created
  + resource "fortios_firewall_object_service" "v13" {
      + category = "General"
      + comment  = "this is from fortios tf module"
      + fqdn     = "abc.com"
      + id       = (known after apply)
      + iprange  = "0.0.0.0"
      + name     = "servicetest1"
      + protocol = "TCP/UDP/SCTP"
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

fortios_firewall_object_service.v13: Creating...

Error: Error creating Firewall Object Service: cannot get the right response

  on service.tf line 7, in resource "fortios_firewall_object_service" "v13":
   7: resource "fortios_firewall_object_service" "v13"{
```
Needless to say, I'm new to TF and Fortinet, any help in right direction will be appreciated.
Thanks!

**Comment by frankshen01** [comment]
hi @hxvxt2,  It looks like there might be a problem with your api-user configuration. Can you check the configuration of your api-user as follows? 
```
myhostname # config system api-user

myhostname (api-user) # edit testapiuser
change table entry 'testapiuser'

myhostname (testapiuser) # show
config system api-user
    edit "testapiuser"
        set api-key ENC SH2nwNKyzHej+Y0pyImpbGQPZY...
        set accprofile "super_admin"
        set vdom "root"
        config trusthost
            edit 1
                set ipv4-trusthost 192.168.0.0 255.255.0.0
            next
        end
    next
end
```
Set accprofile to super_admin, and make sure that the IP address of the machine running Terraform is in the range of trusthost.

Thanks!
