### ISSUE TITLE
Feature to configure BGP

### ISSUE THREAD

**Issue by nickvth** [fortinetdev/terraform-provider-fortios#63]
Feature request: I need to configure bgp and that’s not possible with this provider at this moment

**Comment by hpernicha** [comment]
Hi @nickvth ,

Thanks for your feedback. We are working on supporting BGP and other features on upcoming provider versions.

Thanks,
Hugo

**Comment by frankshen01** [comment]
Feature supported: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_router_bgp
