### ISSUE TITLE
terraform-provider-fortios-beta integration

### ISSUE THREAD

**Issue by davedomainx** [fortinetdev/terraform-provider-fortios#72]
Apologies if this is not the right channel to ask this question:

- Is there any anticipated ETA for the merging of https://github.com/fortinet-terraform-dev/terraform-provider-fortios-beta ?

I would dearly like to switch over from ansible-galaxy fortios collection to terraform-provider-fortios, but the current lack of SD-WAN and DHCP scopes in the terraform provider is preventing that.

I've played around briefly with a local install of terraform-provider-fortios-beta and it seems to have a vast number of new features and improvements which I'm looking forward to investigating more thoroughly once it's merged.

**Comment by frankshen01** [comment]
Hi @davedomainx , no problem. Thank you for your attention, we will release the first merged version within two weeks.

**Comment by frankshen01** [comment]
Hi @davedomainx , the latest merged version(v1.5.3): https://registry.terraform.io/providers/fortinetdev/fortios/latest.  Let me know if you have any questions. Thanks!

**Comment by davedomainx** [comment]
Terrific thanks!  Will be testing this on the backup unit very shortly!
