### ISSUE TITLE
Feature Request: IPSEC VPN creation on Fortimanager

### ISSUE THREAD

**Issue by pacrutchet** [fortinetdev/terraform-provider-fortios#73]
Hello,

As the IPSEC VPN creation is supported on FortiOS, would it be possible to add it to Fortimanager ?

Thanks!

**Comment by frankshen01** [comment]
Hi @pacrutchet , Thanks for your feedback. We will consider adding this feature in the next version that is used to extend FMG features.

**Comment by pacrutchet** [comment]
Hi @frankshen01, thanks a lot for that great work! Do you have a roadmap for the FMG features ?

**Comment by frankshen01** [comment]
Hi, @pacrutchet, we are working on the terraform support for FMG now, including core features with full parameters support, they will be released in the next terraform release for FMG. But I applogize that I haven't more information about the roadmap at the moment. Thank you!
