### ISSUE TITLE
Can I suggest that fortios_vpnipsec_phase1interface does not need remote_gw as a required parameter?

### ISSUE THREAD

**Issue by Parahandy** [fortinetdev/terraform-provider-fortios#75]
Perhaps either one of "remote_gw" or "remotegw_ddns" be a required parameter. There's no way to enter both in the fortigate, so making remote_gw a required parameter may cause confusion - if I supply both, which one will be used? (We use DNS names rather then IPs in existing config)

Thanks.

**Comment by frankshen01** [comment]
Hi @Parahandy, Thank you for pointing out the problem. Your suggestion is very useful, the problem will be fixed in the release version within 2-3 days. Thank you!

**Comment by frankshen01** [comment]
Fixed and released, please see the latest version(v1.5.3): https://registry.terraform.io/providers/fortinetdev/fortios/latest, Thanks!
