### ISSUE TITLE
Don't seem to be able to create ssl_exempt block in firewall_sslsshprofile

### ISSUE THREAD

**Issue by Parahandy** [fortinetdev/terraform-provider-fortios#76]
This code works:
resource "fortios_firewall_sslsshprofile" "testing" {
  name = "testing"
  whitelist = "enable"
  ssl {
    inspect_all = "deep-inspection"
  }
}

But If I add an ssl_exempt block, it fails:
resource "fortios_firewall_sslsshprofile" "testing" {
  name = "testing"
  whitelist = "enable"
  ssl {
    inspect_all = "deep-inspection"
  }
  ssl_exempt {
    id = 1:q

    type = wildcard_fqdn
    wildcard_fqdn = "wildcard.azure.com"
  }
}

Error: Error updating FirewallSslSshProfile resource: Internal Server Error - Internal error when processing the request (500)

  on onefile.tf line 24, in resource "fortios_firewall_sslsshprofile" "testing":
  24: resource "fortios_firewall_sslsshprofile" "testing" {

I have tested adding the ssl_exempt block on CLI, it works fine:
config firewall ssl-ssh-profile
    edit "testing"
 .
.
.
        set whitelist enable
        config ssl-exempt
            edit 1
                set type wildcard-fqdn
                set wildcard-fqdn "wildcard.azure.com"
            next
        end
    next
end

Running debug logs while applying looks like it all works:

[httpsd 1102 - 1599012374     info] fweb_debug_final[248] -- Completed GET request for "/api/v2/cmdb/firewall.wildcard-fqdn/custom/wildcard.azure.com" (HTTP 200)
[httpsd 1216 - 1599012374     info] fweb_debug_init[346] -- New PUT request for "/api/v2/cmdb/firewall/ssl-ssh-profile/testing" from "202.37.198.1:13042"
[httpsd 1216 - 1599012374     info] fweb_debug_init[347] -- User-Agent: "Go-http-client/1.1"
[httpsd 1216 - 1599012374     info] fweb_debug_init[349] -- Handler "api_cmdb_v2-handler" assigned to request
[httpsd 1216 - 1599012374  warning] api_access_check_for_api_key[975] -- API Key request authorized for apiadmin from 202.37.198.1.
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'access_token' (type=string)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'caname' (type=string)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'mapi-over-https' (type=string)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'name' (type=string)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'rpc-over-https' (type=string)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'server-cert-mode' (type=string)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'ssl' (type=object)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'ssl-anomalies-log' (type=string)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'ssl-exempt' (type=array)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'ssl-exemptions-log' (type=string)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'untrusted-caname' (type=string)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'use-ssl-server' (type=string)
[httpsd 1216 - 1599012374     info] api_store_parameter[240] -- add API parameter 'whitelist' (type=string)
[httpsd 1216 - 1599012374     info] handle_cli_req_v2_vdom[2319] -- new CMDB API request (vdom='root',user='apiadmin')
[httpsd 1216 - 1599012374     info] api_cmdb_request_init_by_path[1544] -- new CMDB query (path='firewall',name='ssl-ssh-profile')
[httpsd 1216 - 1599012374     info] api_cmdb_request_init_by_path[1573] -- querying CMDB entry (mkey='testing')
[httpsd 1216 - 1599012374     info] _api_cmdb_v2_config[1216] -- editing CLI object (append=0, auto_key=0, path=firewall, name=ssl-ssh-profile, mkey=testing, flags=0)

And then errors out apparently when saving:

[httpsd 1216 - 1599012374     info] cmdb_save_with_children[279] -- appended main node (nret=0, is_new=0)
[httpsd 1216 - 1599012374     info] cmdb_save_with_children[279] -- appended main node (nret=-89, is_new=1)
[httpsd 1216 - 1599012374    error] cmdb_save_with_children[285] -- saving failed for main node: 'ssl-exempt' (err=-89)

[httpsd 1216 - 1599012374    error] cmdb_commit_from_json[1601] -- error saving request object to CLI (-89)
[httpsd 1216 - 1599012374    error] _api_cmdb_v2_config[1251] -- error editing object (nret=-89)
[httpsd 1216 - 1599012374  warning] api_return_http_result[699] -- API error -89 raised
[httpsd 1216 - 1599012374     info] fweb_debug_final[248] -- Completed PUT request for "/api/v2/cmdb/firewall/ssl-ssh-profile/testing" (HTTP 500)

**Comment by frankshen01** [comment]
Hi @Parahandy , Thanks  for your  feedback!  Could you provide me your FortiGate firemware version? (GUI: Dashboard->Status->System Information->Fireware or CLI: get system status->Version)

**Comment by Parahandy** [comment]
Sure thing:

 # get sys stat
Version: FortiGate-VM64-AZUREONDEMAND v6.4.2,build1723,200729 (GA)
Virus-DB: 80.00064(2020-09-01 18:20)
Extended DB: 80.00064(2020-09-01 18:20)
Extreme DB: 1.00000(2018-04-09 18:07)
IPS-DB: 6.00741(2015-12-01 02:30)
IPS-ETDB: 6.00741(2015-12-01 02:30)
APP-DB: 6.00741(2015-12-01 02:30)
INDUSTRIAL-DB: 6.00741(2015-12-01 02:30)
Serial-Number: FGTAZRMO8EGQCAB4
IPS Malicious URL Database: 2.00754(2020-09-01 07:55)
License Status: Valid
VM Resources: 4 CPU, 7989 MB RAM
VM Instance ID: b4382526-8a7d-4970-a743-e7284b225ec3
Log hard disk: Available
Hostname: XXXX
Operation Mode: NAT
Current virtual domain: root
Max number of virtual domains: 1
Virtual domains status: 1 in NAT mode, 0 in TP mode
Virtual domain configuration: disable
FIPS-CC mode: disable
Current HA mode: a-p, master
Cluster uptime: 6 days, 22 hours, 3 minutes, 34 seconds
Cluster state change time: 2020-09-02 08:02:57
Branch point: 1723
Release Version Information: GA
FortiOS x86-64: Yes
System time: Wed Sep  2 14:55:45 2020

**Comment by frankshen01** [comment]
Hi @Parahandy , Sorry to say that currently the Provider only supports version 6.0 and 6.2 https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs#versioning.  6.4 is not supported. For 6.4 , we will release a separate version that supports 6.4 in a few weeks. Let me try to find a solution for you first, thanks!

**Comment by Parahandy** [comment]
Hi,
Oh, I see. I do remember seeing that now you mention it. My mistake. We've only just upgraded to 6.4 to get around some other issues we had with 6.2.3. Oh well,

Thanks for any help you can give - I wondered if the generic api module might be able to be used.

**Comment by frankshen01** [comment]
No problem, you are welcome. 

After careful checking, I found that there is a spelling error in your configuration file: type = wildcard_fqdn should be: type = "wildcard-fqdn"

Validation on FOS6.4.2:

**# cat maintst.tf**
```
provider "fortios" {
  hostname = "192.168.52.177"
  token = "GNH7r40H65GNb46kd4rG8rtrmn0fr1" # 6.4.2

  insecure = "true"
}

resource "fortios_firewall_sslsshprofile" "testing" {
  name = "testing"
  whitelist = "enable"
  ssl {
    inspect_all = "deep-inspection"
  }

  ssl_exempt {
    id = 3
    type = "wildcard-fqdn"
    wildcard_fqdn = "live.com"
  }
}
```

**# terraform plan**
...
**# terraform apply**
```

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # fortios_firewall_sslsshprofile.testing will be created
  + resource "fortios_firewall_sslsshprofile" "testing" {
      + caname             = (known after apply)
      + id                 = (known after apply)
      + mapi_over_https    = (known after apply)
      + name               = "testing"
      + rpc_over_https     = (known after apply)
      + server_cert        = (known after apply)
      + server_cert_mode   = (known after apply)
      + ssl_anomalies_log  = (known after apply)
      + ssl_exemptions_log = (known after apply)
      + untrusted_caname   = (known after apply)
      + use_ssl_server     = (known after apply)
      + whitelist          = "enable"

      + ssl {
          + client_cert_request   = (known after apply)
          + inspect_all           = "deep-inspection"
          + invalid_server_cert   = (known after apply)
          + sni_server_cert_check = (known after apply)
          + unsupported_ssl       = (known after apply)
          + untrusted_server_cert = (known after apply)
        }

      + ssl_exempt {
          + address             = (known after apply)
          + address6            = (known after apply)
          + fortiguard_category = (known after apply)
          + id                  = 3
          + regex               = (known after apply)
          + type                = "wildcard-fqdn"
          + wildcard_fqdn       = "live.com"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.

Do you want to perform these actions?
  Terraform will perform the actions described above.
  Only 'yes' will be accepted to approve.

  Enter a value: yes

fortios_firewall_sslsshprofile.testing: Creating...
fortios_firewall_sslsshprofile.testing: Creation complete after 0s [id=testing]

Apply complete! Resources: 1 added, 0 changed, 0 destroyed.

```

**Comment by Parahandy** [comment]
oh, excellent, thanks, I will try that.

**Comment by Parahandy** [comment]
And indeed that works a treat. In case it helps anyone else, this is the code to create multiple exemptions from a local map:


locals {
    exlist = {
        "wildcard.windows.net" = [50, "*.windows.net"],
        "wildcard.azure.com" = [51, "*.azure.com"],
        "wildcard.live.com" = [52, "*.live.com"]
    }
}

resource "fortios_firewallwildcardfqdn_custom" "testing" {
  for_each = local.exlist
  color         = 0
  name          = each.key
  visibility    = "enable"
  wildcard_fqdn = each.value[1]
}

resource "fortios_firewall_sslsshprofile" "testing" {
  name = "testing"
  whitelist = "enable"
  ssl {
    inspect_all = "deep-inspection"
  }
  dynamic "ssl_exempt" {
  for_each = local.exlist
   content {
     id = ssl_exempt.value[0]
     type = "wildcard-fqdn"
     wildcard_fqdn = ssl_exempt.key
    }
  }
}

Many thanks again.


P.S.
(In my defence, the spelling of the 'type=wildcard-fqdn' isn't given in the docs. But I could have looked it up in the code.)

Again, much appreciated.
