### ISSUE TITLE
Inconsistency throughout documentation regarding attribute reference/exported attributes

### ISSUE THREAD

**Issue by crawfs** [fortinetdev/terraform-provider-fortios#81]
Almost every single page in the documentation suggests that `id` iss the only attributed that is is exported from the various fortios resources, however in several example, such as fortios_firewall_addrgrp is shows the use of `name` for the export of attributes:

```
resource "fortios_firewall_address" "trname1" {
  allow_routing = "disable"
  cache_ttl     = 0
  color         = 0
  end_ip        = "255.0.0.0"
  name          = "1"
  start_ip      = "12.0.0.0"
  subnet        = "12.0.0.0 255.0.0.0"
  type          = "ipmask"
  visibility    = "enable"
  wildcard      = "12.0.0.0 255.0.0.0"
}

resource "fortios_firewall_addrgrp" "trname" {
  allow_routing = "disable"
  color         = 0
  exclude       = "disable"
  name          = "group1"
  visibility    = "enable"

  member {
    name = fortios_firewall_address.trname1.name
  }
}
```

https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_firewall_addrgrp

Could we get some clarification on which of these is the correct attribute to be used.

**Comment by frankshen01** [comment]
I don’t think I can agree with you. Below is my opinion:

1 The Attribute Reference field in each document indicates:
```
Argument Reference
The following arguments are supported:

name - (Required) Address group name.
uuid - Universally Unique Identifier (UUID; automatically assigned but can be manually reset).
member - (Required) Address objects contained within the group.
...
Attribute Reference
In addition to all the above parameters, the following attributes will be exported:
id-The identifier of the resource in the format {{name}}.
```
It is clearly stated here that its export contains all the above arguments, not just id.

2 For the example you mentioned:
In this example, each member obtains the name of the address by referring to the name attribute in the fortios_firewall_address block. Then send it to the firewall. On the firewall, it only cares about the name in the member, and then the firewall uses that name to access the configured address. Everyone can also get other attributes when necessary, such as fortios_firewall_address.trname1.color.  Please configure resources according to the Firewall manual. Please refer to the FortiGate documentation and the Accessing Resource Attributes section of the Terraform documentation https://www.terraform.io/docs/configuration/resources.html 

3 ID is the unique identification resource that terraform usually uses. It may be name or a combination of multiple fields. For example, ID = {{name}} xxx{{color}}} . Obviously, it is not appropriate for the above example.

**Comment by crawfs** [comment]
ah you're right actually, sorry.
