### ISSUE TITLE
fortios_vpnssl_settings missing argument ssl-min-proto-ver

### ISSUE THREAD

**Issue by crawfs** [fortinetdev/terraform-provider-fortios#82]
The ssl-min-proto-ver parameter is used to specify the minimum tls version for the ssl vpn to use and is currently not a valid parameter in the provider. Would be nice for this to be added.

**Comment by frankshen01** [comment]
Thanks @crawfs for the feedback. Supported in the source. It will be included in the next release (this week).

**Comment by frankshen01** [comment]
Fixed and released, please see the latest version(v1.6.1): https://registry.terraform.io/providers/fortinetdev/fortios/latest, Thanks!
