### ISSUE TITLE
Argument "password" should be optional for fortios_system_admin

### ISSUE THREAD

**Issue by crawfs** [fortinetdev/terraform-provider-fortios#83]
When an admin account is created on a fortigate device with `wildcard` and `remote-auth` set to `enable` the administrator account cannot be assigned a password as all authentication requests will be matched to remote users. The provider should reflect this by having the password argument be optional.

**Comment by frankshen01** [comment]
Thanks @crawfs for the feedback. Fixed in the source. It will be included in the next release (this week).

**Comment by frankshen01** [comment]
Fixed and released, please see the latest version(v1.6.1): https://registry.terraform.io/providers/fortinetdev/fortios/latest, Thanks!
