### ISSUE TITLE
Argument "extport" should be optional for resource fortios_firewall_vip

### ISSUE THREAD

**Issue by crawfs** [fortinetdev/terraform-provider-fortios#84]
When the argument "service" is specified for the fortios_firewall_vip resource a value for "extport" cannot be specified. As such the extport argument should be optional in order to reflect this.

**Comment by frankshen01** [comment]
Thanks for the feedback, it has been fixed and will be included in the next release.

**Comment by frankshen01** [comment]
Fixed and released, please see the latest version(v1.6.1): https://registry.terraform.io/providers/fortinetdev/fortios/latest, Thanks!
