### ISSUE TITLE
Feature request 'configure system sso-admin'

### ISSUE THREAD

**Issue by Parahandy** [fortinetdev/terraform-provider-fortios#88]
Our users use SAML/AD to login to fortigates, would be good if we could add specific sso-admin users via fortios provider.

Thanks!

**Comment by frankshen01** [comment]
Hi @Parahandy, thanks you for the feature request, it's a good FOS feature, we will discuss and evaulate it ASAP. Thank you!

**Comment by frankshen01** [comment]
Supported and released, please see the latest version(v1.6.2): https://registry.terraform.io/providers/fortinetdev/fortios/latest and https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_system_ssoadmin for details, Thanks!
