### ISSUE TITLE
Suggested improvement to fortios_router_static

### ISSUE THREAD

**Issue by Parahandy** [fortinetdev/terraform-provider-fortios#93]
I had cause to create a blackhole static route yesterday, using the above.

Just a suggestion, for a blackhole we don't need a device:

    edit 6
        set dst 10.169.5.144 255.255.255.248
        set distance 254
        set blackhole enable
    next

In fact in the GUI, 'Blackhole' comes up in the 'Interface' box.

As I say, not a big deal, just a thought.

**Comment by frankshen01** [comment]
@Parahandy, you are right. Thanks for your great suggestion which helps us keep improving. 'device' field will be marked as optional and the improvement will take effect in the next release.

**Comment by frankshen01** [comment]
Suggested improvement has been supported and released, please see the latest version(v1.6.5): https://registry.terraform.io/providers/fortinetdev/fortios/latest, Thanks!
