### ISSUE TITLE
Request for additional arguments to vpn_phase1_interface

### ISSUE THREAD

**Issue by Parahandy** [fortinetdev/terraform-provider-fortios#94]
Having recently hit on an issue when using Fortigates in the cloud, we had to manually set 'localid' and 'localid-type' in the phase1 interface to the external public IP to get the tunnel to come up. These arguments are not (yet?) available in the fortios provider. Could they be considered for inclusion in a future version? Thanks!

**Comment by frankshen01** [comment]
Hi @Parahandy , did you mean: https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_vpnipsec_phase1interface ?
but we can find that they have been supported:
```
localid - Local ID.
localid_type - Local ID type.
```
Could you check if you are actually using old resources that will be deprecated?(_https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fortios_vpn_ipsec_phase1interface , we can see that there is a warning: The resource will be deprecated and replaced by fortios_vpnipsec_phase1interface. We recommend that you use new resources: fortios_vpnipsec_phase1interface_)

Thanks!

**Comment by Parahandy** [comment]
Argh. As always, you are absolutely right. I must have looked at the docs for the deprecated resource. My apologies, and thanks for your patience once more.
