### ISSUE TITLE
FMG script execute for adom_database target

### ISSUE THREAD

**Issue by monikazi** [fortinetdev/terraform-provider-fortios#95]
Hello Team, 

Executing script fortios_fmg_devicemanager_script_execute created by resource fortios_fmg_devicemanager_script with target: **adom_database** fails with error: Invalid parameter.

The fortios_fmg_devicemanager_script_execute resource seem to miss parameter: **package** (Policy Package name), without which related API call is also failing. 

Thank you in advance for your feedback. 

Greetings,
Monika

**Comment by frankshen01** [comment]
Hi @monikazi , thanks for raising this issue, your suggestion is wonderful! The 'package' argument will be supported to fix the problem, it will be included in the next release (within a week). Thank you!

**Comment by monikazi** [comment]
Hello @frankshen01, that sounds great! Many thanks!

**Comment by frankshen01** [comment]
Fixed and released, please see the latest version(v1.6.6): https://registry.terraform.io/providers/fortinetdev/fortios/latest and https://registry.terraform.io/providers/fortinetdev/fortios/latest/docs/resources/fmg_devicemanager_script_execute for details, Thanks!
